// resources/js/Pages/Dashboard/Inventory/Create.vue
<template>
    <Head :title="__('Add Inventory Item')" />

    <vee-form
        :validation-schema="schema"
        @submit="submit"
        v-slot="{ meta, setErrors }"
    >
        <div class="tw-space-y-6">
            <!-- Header -->
            <div class="tw-flex tw-items-center tw-justify-between">
                <div>
                    <h2 class="tw-text-2xl tw-font-bold tw-tracking-tight">
                        {{ __("Add Inventory Item") }}
                    </h2>
                    <p class="tw-text-muted-foreground">
                        {{ __("Create new inventory record for a product") }}
                    </p>
                </div>
                <Button
                    variant="outline"
                    @click="goBack"
                >
                    <ArrowLeft class="tw-w-4 tw-h-4 tw-mr-2" />
                    {{ __("Back") }}
                </Button>
            </div>

            <!-- Form -->
            <div class="tw-grid tw-grid-cols-1 lg:tw-grid-cols-3 tw-gap-6">
                <!-- Main Form -->
                <div class="tw-lg:col-span-2 tw-space-y-6">
                    <!-- Product Selection -->
                    <Card>
                        <CardHeader>
                            <CardTitle>{{ __("Select Product") }}</CardTitle>
                            <CardDescription>
                                {{ __("Choose a product to add inventory tracking") }}
                            </CardDescription>
                        </CardHeader>
                        <CardContent class="tw-space-y-4">
                            <vee-field
                                name="product_id"
                                v-slot="{ field, errors }"
                            >
                                <div class="tw-space-y-2">
                                    <Label for="product_id">
                                        {{ __("Product") }}
                                        <span class="tw-text-destructive">*</span>
                                    </Label>
                                    <Select
                                        v-model="form.product_id"
                                        @update:model-value="(val) => form.product_id = val"
                                    >
                                        <SelectTrigger id="product_id">
                                            <SelectValue :placeholder="__('Select a product')" />
                                        </SelectTrigger>
                                        <SelectContent>
                                            <SelectItem 
                                                v-for="product in products" 
                                                :key="product.id" 
                                                :value="product.id"
                                            >
                                                {{ product.name }} - {{ product.category?.name }}
                                            </SelectItem>
                                        </SelectContent>
                                    </Select>
                                    <p v-if="errors.length" class="tw-text-sm tw-text-destructive">
                                        {{ errors[0] }}
                                    </p>
                                </div>
                            </vee-field>

                            <!-- Selected Product Preview -->
                            <div v-if="selectedProduct" class="tw-p-4 tw-rounded-lg tw-border tw-bg-muted/50">
                                <div class="tw-flex tw-items-center tw-gap-4">
                                    <div class="tw-w-16 tw-h-16 tw-rounded-lg tw-bg-muted tw-flex tw-items-center tw-justify-center tw-overflow-hidden">
                                        <img
                                            v-if="selectedProduct.image"
                                            :src="`/storage/${selectedProduct.image}`"
                                            :alt="selectedProduct.name"
                                            class="tw-w-full tw-h-full tw-object-cover"
                                        />
                                        <Package v-else class="tw-w-8 tw-h-8 tw-text-muted-foreground" />
                                    </div>
                                    <div class="tw-flex-1">
                                        <p class="tw-font-semibold">{{ selectedProduct.name }}</p>
                                        <p class="tw-text-sm tw-text-muted-foreground">
                                            {{ selectedProduct.category?.name }} • ${{ selectedProduct.price }}
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </CardContent>
                    </Card>

                    <!-- Stock Information -->
                    <Card>
                        <CardHeader>
                            <CardTitle>{{ __("Stock Information") }}</CardTitle>
                            <CardDescription>
                                {{ __("Set initial stock levels") }}
                            </CardDescription>
                        </CardHeader>
                        <CardContent class="tw-space-y-4">
                            <vee-field
                                name="quantity"
                                v-slot="{ field, errors }"
                            >
                                <div class="tw-space-y-2">
                                    <Label for="quantity">
                                        {{ __("Initial Quantity") }}
                                        <span class="tw-text-destructive">*</span>
                                    </Label>
                                    <Input
                                        id="quantity"
                                        type="number"
                                        min="0"
                                        v-bind="field"
                                        :model-value="form.quantity"
                                        @update:model-value="(val) => form.quantity = parseInt(val)"
                                        :class="{ 'tw-border-destructive': errors.length }"
                                        :placeholder="__('Enter initial stock quantity')"
                                    />
                                    <p v-if="errors.length" class="tw-text-sm tw-text-destructive">
                                        {{ errors[0] }}
                                    </p>
                                </div>
                            </vee-field>

                            <vee-field
                                name="minimum_stock"
                                v-slot="{ field, errors }"
                            >
                                <div class="tw-space-y-2">
                                    <Label for="minimum_stock">
                                        {{ __("Minimum Stock Threshold") }}
                                        <span class="tw-text-destructive">*</span>
                                    </Label>
                                    <Input
                                        id="minimum_stock"
                                        type="number"
                                        min="0"
                                        v-bind="field"
                                        :model-value="form.minimum_stock"
                                        @update:model-value="(val) => form.minimum_stock = parseInt(val)"
                                        :class="{ 'tw-border-destructive': errors.length }"
                                        :placeholder="__('Enter minimum stock level')"
                                    />
                                    <p v-if="errors.length" class="tw-text-sm tw-text-destructive">
                                        {{ errors[0] }}
                                    </p>
                                    <p class="tw-text-sm tw-text-muted-foreground">
                                        {{ __("Alert will trigger when stock reaches this level") }}
                                    </p>
                                </div>
                            </vee-field>

                            <!-- Stock Status Preview -->
                            <div v-if="form.quantity !== null && form.minimum_stock !== null" class="tw-p-4 tw-rounded-lg tw-bg-muted/50 tw-mt-6">
                                <Label class="tw-text-muted-foreground tw-text-sm">{{ __("Stock Status Preview") }}</Label>
                                <div class="tw-flex tw-items-center tw-gap-4 tw-mt-2">
                                    <div>
                                        <p class="tw-text-2xl tw-font-bold">{{ form.quantity || 0 }}</p>
                                        <p class="tw-text-xs tw-text-muted-foreground">{{ __("Initial") }}</p>
                                    </div>
                                    <div class="tw-text-muted-foreground">/</div>
                                    <div>
                                        <p class="tw-text-2xl tw-font-bold">{{ form.minimum_stock || 0 }}</p>
                                        <p class="tw-text-xs tw-text-muted-foreground">{{ __("Minimum") }}</p>
                                    </div>
                                    <div class="tw-ml-auto">
                                        <Badge :variant="getStatusVariant()">
                                            {{ getStatusText() }}
                                        </Badge>
                                    </div>
                                </div>
                            </div>
                        </CardContent>
                    </Card>
                </div>

                <!-- Sidebar -->
                <div class="tw-space-y-6">
                    <!-- Actions -->
                    <Card>
                        <CardHeader>
                            <CardTitle>{{ __("Actions") }}</CardTitle>
                        </CardHeader>
                        <CardContent class="tw-space-y-2">
                            <Button
                                type="submit"
                                class="tw-w-full"
                                :disabled="!meta.valid || form.processing"
                            >
                                <Loader2
                                    v-if="form.processing"
                                    class="tw-h-4 tw-w-4 tw-mr-2 tw-animate-spin"
                                />
                                <Plus v-else class="tw-h-4 tw-w-4 tw-mr-2" />
                                {{ __("Create Inventory") }}
                            </Button>
                            <Button
                                type="button"
                                variant="outline"
                                class="tw-w-full"
                                @click="goBack"
                            >
                                {{ __("Cancel") }}
                            </Button>
                        </CardContent>
                    </Card>

                    <!-- Tips -->
                    <Card>
                        <CardHeader>
                            <CardTitle>{{ __("Tips") }}</CardTitle>
                        </CardHeader>
                        <CardContent class="tw-text-sm tw-text-muted-foreground tw-space-y-2">
                            <p>• {{ __("Select a product without inventory") }}</p>
                            <p>• {{ __("Set minimum stock for alerts") }}</p>
                            <p>• {{ __("You can adjust quantities later") }}</p>
                        </CardContent>
                    </Card>
                </div>
            </div>
        </div>
    </vee-form>
</template>

<script setup>
import { computed } from "vue";
import { useForm } from "@inertiajs/vue3";
import { router, Head } from "@inertiajs/vue3";
import { Button } from "@/Components/ui/button";
import { Input } from "@/Components/ui/input";
import { Label } from "@/Components/ui/label";
import { Badge } from "@/Components/ui/badge";
import {
    Card,
    CardContent,
    CardDescription,
    CardHeader,
    CardTitle,
} from "@/Components/ui/card";
import {
    Select,
    SelectContent,
    SelectItem,
    SelectTrigger,
    SelectValue,
} from "@/Components/ui/select";
import { Loader2, Plus, ArrowLeft, Package } from "lucide-vue-next";
import { useToast } from "@/Components/ui/toast/use-toast";
import * as yup from "yup";

const { toast } = useToast();

const props = defineProps({
    products: {
        type: Array,
        default: () => [],
    },
});

const schema = yup.object({
    product_id: yup.string().required(__("Product is required")),
    quantity: yup.number().required(__("Quantity is required")).min(0, __("Quantity must be positive")),
    minimum_stock: yup.number().required(__("Minimum stock is required")).min(0, __("Minimum stock must be positive")),
});

const form = useForm({
    product_id: "",
    quantity: 0,
    minimum_stock: 0,
});

const selectedProduct = computed(() => {
    return props.products.find(p => p.id === form.product_id);
});

const getStatusVariant = () => {
    if ((form.quantity || 0) === 0) return 'destructive';
    if ((form.quantity || 0) <= (form.minimum_stock || 0)) return 'warning';
    return 'success';
};

const getStatusText = () => {
    if ((form.quantity || 0) === 0) return __("Out of Stock");
    if ((form.quantity || 0) <= (form.minimum_stock || 0)) return __("Low Stock");
    return __("In Stock");
};

const submit = (setErrors) => {
    form.post(route("dashboard.inventory.store"), {
        onSuccess: () => {
            toast({
                title: __("Success"),
                description: __("Inventory created successfully"),
            });
        },
        onError: (errors) => {
            setErrors(errors);
            toast({
                title: __("Error"),
                description: __("Failed to create inventory"),
                variant: "destructive",
            });
        },
    });
};

const goBack = () => {
    router.visit(route("dashboard.inventory.index"));
};
</script>

// resources/js/Pages/InventoryOrders/Create.tsx
import { FormEventHandler, useState } from 'react';
import { Head, Link, useForm } from '@inertiajs/react';
import AppLayout from '@/Layouts/AppLayout';
import { Product, Supplier } from '@/types';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { ArrowLeft, Plus, Trash2, ShoppingCart } from 'lucide-react';
import { formatPrice } from '@/lib/utils';

interface Props {
    products: Product[];
    suppliers: Supplier[];
}

interface OrderItem {
    product: Product;
    quantity: number;
    unit_cost: number;
}

export default function Create({ products, suppliers }: Props) {
    const [cart, setCart] = useState<OrderItem[]>([]);
    const [selectedSupplier, setSelectedSupplier] = useState('');

    const { post, processing } = useForm();

    const addItem = (product: Product) => {
        const existingItem = cart.find(item => item.product.id === product.id);
        if (existingItem) return;

        setCart([...cart, {
            product,
            quantity: product.inventory?.minimum_stock || 10,
            unit_cost: typeof product.price === 'string' ? parseFloat(product.price) : product.price
        }]);
    };

    const updateQuantity = (productId: number, quantity: number) => {
        setCart(cart.map(item =>
            item.product.id === productId ? { ...item, quantity: Math.max(1, quantity) } : item
        ));
    };

    const updateUnitCost = (productId: number, unitCost: number) => {
        setCart(cart.map(item =>
            item.product.id === productId ? { ...item, unit_cost: Math.max(0, unitCost) } : item
        ));
    };

    const removeItem = (productId: number) => {
        setCart(cart.filter(item => item.product.id !== productId));
    };

    const calculateTotal = () => {
        return cart.reduce((sum, item) => sum + (item.quantity * item.unit_cost), 0);
    };

    const submit: FormEventHandler = (e) => {
        e.preventDefault();

        post('/manager/inventory-orders', {
            data: {
                supplier_id: selectedSupplier,
                items: cart.map(item => ({
                    product_id: item.product.id,
                    quantity: item.quantity,
                    unit_cost: item.unit_cost,
                })),
            },
        });
    };

    return (
        <AppLayout>
            <Head title="Create Inventory Order" />

            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
                <Link href="/manager/inventory-orders">
                    <Button variant="outline" className="mb-6">
                        <ArrowLeft className="w-4 h-4 mr-2" />
                        Back to Orders
                    </Button>
                </Link>

                <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                    {/* Products Selection */}
                    <div className="lg:col-span-2">
                        <Card>
                            <CardHeader>
                                <CardTitle>Select Products</CardTitle>
                                <CardDescription>Add items to your order</CardDescription>
                            </CardHeader>
                            <CardContent>
                                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 max-h-[600px] overflow-y-auto">
                                    {products.map((product) => (
                                        <Card key={product.id}>
                                            <CardHeader className="p-4">
                                                <CardTitle className="text-sm">{product.name}</CardTitle>
                                                <p className="text-xs text-gray-500">{product.category?.name}</p>
                                                <p className="text-sm font-medium text-gray-700">
                                                    Current Stock: {product.inventory?.quantity || 0}
                                                </p>
                                            </CardHeader>
                                            <CardContent className="p-4 pt-0">
                                                <Button
                                                    size="sm"
                                                    className="w-full"
                                                    onClick={() => addItem(product)}
                                                    disabled={cart.some(item => item.product.id === product.id)}
                                                >
                                                    <Plus className="w-3 h-3 mr-1" />
                                                    {cart.some(item => item.product.id === product.id) ? 'Added' : 'Add'}
                                                </Button>
                                            </CardContent>
                                        </Card>
                                    ))}
                                </div>
                            </CardContent>
                        </Card>
                    </div>

                    {/* Order Summary */}
                    <div>
                        <form onSubmit={submit} className="space-y-4">
                            <Card>
                                <CardHeader>
                                    <CardTitle>Order Details</CardTitle>
                                </CardHeader>
                                <CardContent className="space-y-4">
                                    <div>
                                        <label className="text-sm font-medium mb-2 block">Supplier *</label>
                                        <Select value={selectedSupplier} onValueChange={setSelectedSupplier}>
                                            <SelectTrigger>
                                                <SelectValue placeholder="Select supplier" />
                                            </SelectTrigger>
                                            <SelectContent>
                                                {suppliers.map((supplier) => (
                                                    <SelectItem key={supplier.id} value={supplier.id.toString()}>
                                                        {supplier.name}
                                                    </SelectItem>
                                                ))}
                                            </SelectContent>
                                        </Select>
                                    </div>

                                    {cart.length === 0 ? (
                                        <div className="text-center py-8 text-gray-500">
                                            <ShoppingCart className="w-12 h-12 mx-auto mb-2 text-gray-400" />
                                            <p className="text-sm">No items added</p>
                                        </div>
                                    ) : (
                                        <div className="space-y-4">
                                            <p className="text-sm font-medium">{cart.length} item(s)</p>
                                            {cart.map((item) => (
                                                <div key={item.product.id} className="border rounded-md p-3 space-y-2">
                                                    <div className="flex justify-between items-start">
                                                        <p className="font-medium text-sm flex-1">{item.product.name}</p>
                                                        <Button
                                                            size="icon"
                                                            variant="ghost"
                                                            type="button"
                                                            onClick={() => removeItem(item.product.id)}
                                                        >
                                                            <Trash2 className="w-4 h-4 text-red-500" />
                                                        </Button>
                                                    </div>
                                                    <div className="space-y-2">
                                                        <div>
                                                            <label className="text-xs text-gray-600">Quantity</label>
                                                            <Input
                                                                type="number"
                                                                min="1"
                                                                value={item.quantity}
                                                                onChange={(e) => updateQuantity(item.product.id, parseInt(e.target.value) || 1)}
                                                            />
                                                        </div>
                                                        <div>
                                                            <label className="text-xs text-gray-600">Unit Cost ($)</label>
                                                            <Input
                                                                type="number"
                                                                step="0.01"
                                                                min="0"
                                                                value={item.unit_cost}
                                                                onChange={(e) => updateUnitCost(item.product.id, parseFloat(e.target.value) || 0)}
                                                            />
                                                        </div>
                                                        <div className="text-sm font-medium">
                                                            Subtotal: {formatPrice(item.quantity * item.unit_cost)}
                                                        </div>
                                                    </div>
                                                </div>
                                            ))}

                                            <div className="border-t pt-4">
                                                <div className="flex justify-between text-lg font-bold">
                                                    <span>Total:</span>
                                                    <span className="text-indigo-600">
                                                        {formatPrice(calculateTotal())}
                                                    </span>
                                                </div>
                                            </div>

                                            <Button
                                                type="submit"
                                                className="w-full"
                                                disabled={processing || !selectedSupplier || cart.length === 0}
                                            >
                                                Create Order
                                            </Button>
                                        </div>
                                    )}
                                </CardContent>
                            </Card>
                        </form>
                    </div>
                </div>
            </div>
        </AppLayout>
    );
}
