// resources/js/Pages/Dashboard/Suppliers/Show.vue
<template>
    <Head :title="`${supplier.name} - Supplier Details`" />

    <div class="tw-space-y-6">
        <!-- Header -->
        <div class="tw-flex tw-items-center tw-justify-between">
            <div>
                <h2 class="tw-text-2xl tw-font-bold tw-tracking-tight">
                    {{ supplier.name }}
                </h2>
                <p class="tw-text-muted-foreground">
                    {{ __("Supplier details and orders") }}
                </p>
            </div>
            <div class="tw-flex tw-gap-2">
                <Button
                    variant="outline"
                    @click="editSupplier"
                >
                    <Edit class="tw-w-4 tw-h-4 tw-mr-2" />
                    {{ __("Edit") }}
                </Button>
                <Button
                    variant="outline"
                    @click="goBack"
                >
                    <ArrowLeft class="tw-w-4 tw-h-4 tw-mr-2" />
                    {{ __("Back") }}
                </Button>
            </div>
        </div>

        <!-- Supplier Information -->
        <div class="tw-grid tw-grid-cols-1 lg:tw-grid-cols-3 tw-gap-6">
            <!-- Main Content -->
            <div class="tw-lg:col-span-2 tw-space-y-6">
                <!-- Details Card -->
                <Card>
                    <CardHeader>
                        <CardTitle>{{ __("Supplier Information") }}</CardTitle>
                    </CardHeader>
                    <CardContent class="tw-space-y-4">
                        <div class="tw-grid tw-grid-cols-2 tw-gap-4">
                            <div>
                                <Label class="tw-text-muted-foreground">{{ __("Company Name") }}</Label>
                                <p class="tw-text-lg tw-font-semibold">{{ supplier.name }}</p>
                            </div>
                            <div>
                                <Label class="tw-text-muted-foreground">{{ __("Contact Person") }}</Label>
                                <p class="tw-text-lg">{{ supplier.contact_person || __("Not specified") }}</p>
                            </div>
                        </div>

                        <div class="tw-grid tw-grid-cols-2 tw-gap-4">
                            <div>
                                <Label class="tw-text-muted-foreground">{{ __("Email") }}</Label>
                                <p class="tw-flex tw-items-center tw-gap-2">
                                    <Mail class="tw-w-4 tw-h-4" />
                                    <a :href="`mailto:${supplier.email}`" class="tw-text-primary hover:tw-underline">
                                        {{ supplier.email }}
                                    </a>
                                </p>
                            </div>
                            <div>
                                <Label class="tw-text-muted-foreground">{{ __("Phone") }}</Label>
                                <p class="tw-flex tw-items-center tw-gap-2">
                                    <Phone class="tw-w-4 tw-h-4" />
                                    <a :href="`tel:${supplier.phone}`" class="tw-text-primary hover:tw-underline">
                                        {{ supplier.phone }}
                                    </a>
                                </p>
                            </div>
                        </div>
                        
                        <div>
                            <Label class="tw-text-muted-foreground">{{ __("Address") }}</Label>
                            <p class="tw-flex tw-items-start tw-gap-2 tw-mt-1">
                                <MapPin class="tw-w-4 tw-h-4 tw-mt-0.5" />
                                <span>{{ supplier.address }}</span>
                            </p>
                        </div>

                        <div class="tw-grid tw-grid-cols-2 tw-gap-4 tw-text-sm tw-pt-4 tw-border-t">
                            <div>
                                <Label class="tw-text-muted-foreground">{{ __("Created At") }}</Label>
                                <p>{{ new Date(supplier.created_at).toLocaleString() }}</p>
                            </div>
                            <div>
                                <Label class="tw-text-muted-foreground">{{ __("Last Updated") }}</Label>
                                <p>{{ new Date(supplier.updated_at).toLocaleString() }}</p>
                            </div>
                        </div>
                    </CardContent>
                </Card>

                <!-- Inventory Orders -->
                <Card>
                    <CardHeader>
                        <div class="tw-flex tw-items-center tw-justify-between">
                            <CardTitle>{{ __("Recent Inventory Orders") }}</CardTitle>
                            <Button
                                size="sm"
                                @click="createInventoryOrder"
                            >
                                <Plus class="tw-w-4 tw-h-4 tw-mr-2" />
                                {{ __("New Order") }}
                            </Button>
                        </div>
                    </CardHeader>
                    <CardContent>
                        <div v-if="supplier.inventory_orders && supplier.inventory_orders.length > 0" class="tw-space-y-2">
                            <div
                                v-for="order in supplier.inventory_orders"
                                :key="order.id"
                                class="tw-flex tw-items-center tw-justify-between tw-p-3 tw-rounded-lg tw-border hover:tw-bg-muted/50 tw-cursor-pointer"
                                @click="viewInventoryOrder(order)"
                            >
                                <div class="tw-flex tw-items-center tw-gap-3">
                                    <div class="tw-w-10 tw-h-10 tw-rounded-full tw-bg-primary/10 tw-flex tw-items-center tw-justify-center">
                                        <Package class="tw-w-5 tw-h-5 tw-text-primary" />
                                    </div>
                                    <div>
                                        <p class="tw-font-medium">{{ order.order_number }}</p>
                                        <p class="tw-text-sm tw-text-muted-foreground">
                                            {{ new Date(order.order_date).toLocaleDateString() }}
                                        </p>
                                    </div>
                                </div>
                                <div class="tw-flex tw-items-center tw-gap-2">
                                    <Badge :variant="getStatusVariant(order.status)">
                                        {{ order.status }}
                                    </Badge>
                                    <ChevronRight class="tw-w-4 tw-h-4 tw-text-muted-foreground" />
                                </div>
                            </div>
                        </div>
                        <div v-else class="tw-text-center tw-py-8">
                            <Package class="tw-mx-auto tw-h-12 tw-w-12 tw-text-muted-foreground" />
                            <p class="tw-mt-2 tw-text-sm tw-text-muted-foreground">
                                {{ __("No inventory orders yet") }}
                            </p>
                        </div>
                    </CardContent>
                </Card>
            </div>

            <!-- Sidebar -->
            <div class="tw-space-y-6">
                <!-- Quick Actions -->
                <Card>
                    <CardHeader>
                        <CardTitle>{{ __("Quick Actions") }}</CardTitle>
                    </CardHeader>
                    <CardContent class="tw-space-y-2">
                        <Button
                            variant="outline"
                            class="tw-w-full tw-justify-start"
                            @click="editSupplier"
                        >
                            <Edit class="tw-w-4 tw-h-4 tw-mr-2" />
                            {{ __("Edit Supplier") }}
                        </Button>
                        <Button
                            variant="outline"
                            class="tw-w-full tw-justify-start"
                            @click="createInventoryOrder"
                        >
                            <Plus class="tw-w-4 tw-h-4 tw-mr-2" />
                            {{ __("New Order") }}
                        </Button>
                        <Button
                            variant="outline"
                            class="tw-w-full tw-justify-start"
                            as="a"
                            :href="`mailto:${supplier.email}`"
                        >
                            <Mail class="tw-w-4 tw-h-4 tw-mr-2" />
                            {{ __("Send Email") }}
                        </Button>
                        <Button
                            variant="outline"
                            class="tw-w-full tw-justify-start tw-text-destructive hover:tw-text-destructive"
                            @click="deleteSupplier"
                        >
                            <Trash2 class="tw-w-4 tw-h-4 tw-mr-2" />
                            {{ __("Delete Supplier") }}
                        </Button>
                    </CardContent>
                </Card>

                <!-- Statistics -->
                <Card>
                    <CardHeader>
                        <CardTitle>{{ __("Statistics") }}</CardTitle>
                    </CardHeader>
                    <CardContent class="tw-space-y-3">
                        <div class="tw-flex tw-items-center tw-justify-between">
                            <span class="tw-text-sm tw-text-muted-foreground">{{ __("Total Orders") }}</span>
                            <span class="tw-font-semibold">{{ supplier.inventory_orders?.length || 0 }}</span>
                        </div>
                    </CardContent>
                </Card>
            </div>
        </div>
    </div>
</template>

<script setup>
import { router } from "@inertiajs/vue3";
import { Head } from "@inertiajs/vue3";
import { Button } from "@/Components/ui/button";
import { Label } from "@/Components/ui/label";
import { Badge } from "@/Components/ui/badge";
import {
    Card,
    CardContent,
    CardHeader,
    CardTitle,
} from "@/Components/ui/card";
import {
    Edit,
    ArrowLeft,
    Plus,
    Trash2,
    Package,
    ChevronRight,
    Mail,
    Phone,
    MapPin,
} from "lucide-vue-next";
import { useToast } from "@/Components/ui/toast/use-toast";

const { toast } = useToast();

const props = defineProps({
    supplier: {
        type: Object,
        required: true,
    },
});

const getStatusVariant = (status) => {
    const variants = {
        pending: 'secondary',
        sent: 'default',
        received: 'success',
        cancelled: 'destructive'
    };
    return variants[status] || 'secondary';
};

const goBack = () => {
    router.visit(route("dashboard.suppliers.index"));
};

const editSupplier = () => {
    router.visit(route("dashboard.suppliers.edit", props.supplier.id));
};

const createInventoryOrder = () => {
    router.visit(route("dashboard.inventory-orders.create"), {
        data: { supplier_id: props.supplier.id }
    });
};

const viewInventoryOrder = (order) => {
    router.visit(route("dashboard.inventory-orders.show", order.id));
};

const deleteSupplier = () => {
    if (!confirm(__("Are you sure you want to delete this supplier? This action cannot be undone."))) {
        return;
    }

    router.delete(route("dashboard.suppliers.destroy", props.supplier.id), {
        onSuccess: () => {
            toast({
                title: __("Success"),
                description: __("Supplier deleted successfully"),
            });
        },
        onError: () => {
            toast({
                title: __("Error"),
                description: __("Failed to delete supplier"),
                variant: "destructive",
            });
        },
    });
};
</script>

// resources/js/Pages/InventoryOrders/Show.tsx
import { Head, Link, router } from '@inertiajs/react';
import AppLayout from '@/Layouts/AppLayout';
import { InventoryOrder } from '@/types';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Separator } from '@/components/ui/separator';
import { ArrowLeft, Send, Package, X } from 'lucide-react';
import { formatPrice, formatDateTime } from '@/lib/utils';

interface Props {
    inventoryOrder: InventoryOrder;
}

const statusColors = {
    pending: 'bg-yellow-100 text-yellow-800 border-yellow-200',
    sent: 'bg-blue-100 text-blue-800 border-blue-200',
    received: 'bg-green-100 text-green-800 border-green-200',
    cancelled: 'bg-red-100 text-red-800 border-red-200',
};

export default function Show({ inventoryOrder }: Props) {
    const handleMarkAsSent = () => {
        if (confirm('Mark this order as sent to supplier?')) {
            router.post(`/manager/inventory-orders/${inventoryOrder.id}/sent`, {});
        }
    };

    const handleMarkAsReceived = () => {
        if (confirm('Mark this order as received? This will update inventory levels.')) {
            router.post(`/manager/inventory-orders/${inventoryOrder.id}/received`, {});
        }
    };

    const handleCancel = () => {
        if (confirm('Are you sure you want to cancel this order?')) {
            router.post(`/manager/inventory-orders/${inventoryOrder.id}/cancel`, {});
        }
    };

    return (
        <AppLayout>
            <Head title={`Order #${inventoryOrder.order_number}`} />

            <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
                <Link href="/manager/inventory-orders">
                    <Button variant="outline" className="mb-6">
                        <ArrowLeft className="w-4 h-4 mr-2" />
                        Back to Orders
                    </Button>
                </Link>

                <Card>
                    <CardHeader>
                        <div className="flex justify-between items-start">
                            <div>
                                <CardTitle className="text-2xl">
                                    Order #{inventoryOrder.order_number}
                                </CardTitle>
                                <CardDescription>
                                    Created {formatDateTime(inventoryOrder.created_at)}
                                </CardDescription>
                            </div>
                            <Badge className={statusColors[inventoryOrder.status]}>
                                {inventoryOrder.status.charAt(0).toUpperCase() + inventoryOrder.status.slice(1)}
                            </Badge>
                        </div>
                    </CardHeader>
                    <CardContent className="space-y-6">
                        {/* Supplier Info */}
                        <div>
                            <h3 className="text-lg font-semibold mb-2">Supplier Information</h3>
                            <div className="bg-gray-50 rounded-lg p-4 space-y-1">
                                <p className="font-medium">{inventoryOrder.supplier?.name}</p>
                                <p className="text-sm text-gray-600">{inventoryOrder.supplier?.email}</p>
                                <p className="text-sm text-gray-600">{inventoryOrder.supplier?.phone}</p>
                                <p className="text-sm text-gray-600">{inventoryOrder.supplier?.address}</p>
                                {inventoryOrder.supplier?.contact_person && (
                                    <p className="text-sm text-gray-600">
                                        Contact: {inventoryOrder.supplier.contact_person}
                                    </p>
                                )}
                            </div>
                        </div>

                        <Separator />

                        {/* Order Items */}
                        <div>
                            <h3 className="text-lg font-semibold mb-4">Order Items</h3>
                            <div className="space-y-3">
                                {inventoryOrder.items?.map((item) => (
                                    <div key={item.id} className="flex justify-between items-center border-b pb-3">
                                        <div className="flex-1">
                                            <p className="font-medium">{item.product?.name}</p>
                                            <p className="text-sm text-gray-600">
                                                {formatPrice(item.unit_cost)} × {item.quantity}
                                            </p>
                                        </div>
                                        <div className="text-right">
                                            <p className="font-bold">{formatPrice(item.subtotal)}</p>
                                        </div>
                                    </div>
                                ))}
                            </div>

                            <div className="mt-4 pt-4 border-t">
                                <div className="flex justify-between text-xl font-bold">
                                    <span>Total:</span>
                                    <span className="text-indigo-600">
                                        {formatPrice(inventoryOrder.total_amount)}
                                    </span>
                                </div>
                            </div>
                        </div>

                        <Separator />

                        {/* Timeline */}
                        <div>
                            <h3 className="text-lg font-semibold mb-4">Order Timeline</h3>
                            <div className="space-y-3">
                                <div className="flex items-start gap-3">
                                    <div className="w-2 h-2 rounded-full bg-green-500 mt-2"></div>
                                    <div>
                                        <p className="font-medium">Order Created</p>
                                        <p className="text-sm text-gray-600">
                                            {formatDateTime(inventoryOrder.created_at)}
                                        </p>
                                        <p className="text-sm text-gray-600">
                                            By: {inventoryOrder.manager?.name}
                                        </p>
                                    </div>
                                </div>

                                {inventoryOrder.sent_at && (
                                    <div className="flex items-start gap-3">
                                        <div className="w-2 h-2 rounded-full bg-blue-500 mt-2"></div>
                                        <div>
                                            <p className="font-medium">Order Sent to Supplier</p>
                                            <p className="text-sm text-gray-600">
                                                {formatDateTime(inventoryOrder.sent_at)}
                                            </p>
                                        </div>
                                    </div>
                                )}

                                {inventoryOrder.received_at && (
                                    <div className="flex items-start gap-3">
                                        <div className="w-2 h-2 rounded-full bg-green-500 mt-2"></div>
                                        <div>
                                            <p className="font-medium">Order Received</p>
                                            <p className="text-sm text-gray-600">
                                                {formatDateTime(inventoryOrder.received_at)}
                                            </p>
                                        </div>
                                    </div>
                                )}
                            </div>
                        </div>

                        {/* Actions */}
                        <div className="flex gap-2">
                            {inventoryOrder.status === 'pending' && (
                                <>
                                    <Button onClick={handleMarkAsSent} className="flex-1">
                                        <Send className="w-4 h-4 mr-2" />
                                        Mark as Sent
                                    </Button>
                                    <Button variant="destructive" onClick={handleCancel}>
                                        <X className="w-4 h-4 mr-2" />
                                        Cancel
                                    </Button>
                                </>
                            )}
                            {inventoryOrder.status === 'sent' && (
                                <>
                                    <Button onClick={handleMarkAsReceived} className="flex-1">
                                        <Package className="w-4 h-4 mr-2" />
                                        Mark as Received
                                    </Button>
                                    <Button variant="destructive" onClick={handleCancel}>
                                        <X className="w-4 h-4 mr-2" />
                                        Cancel
                                    </Button>
                                </>
                            )}
                        </div>
                    </CardContent>
                </Card>
            </div>
        </AppLayout>
    );
}
