// resources/js/Pages/Dashboard/Customer.vue
<template>
    <AppLayout>

        <Head title="Dashboard" />

        <!-- Welcome Section -->
        <div class="mb-8">
            <h1 class="text-h3 font-weight-bold text-grey-darken-3 mb-2">
                Welcome back!
            </h1>
            <p class="text-grey-darken-1">
                Here's an overview of your orders
            </p>
        </div>

        <!-- Statistics Cards -->
        <v-row class="mb-8">
            <v-col v-for="(stat, key) in statsCards" :key="key" cols="12" sm="6" md="3">
                <v-card elevation="2" class="pa-4">
                    <div class="d-flex justify-space-between align-center mb-2">
                        <div class="text-subtitle-2 text-grey-darken-1">
                            {{ stat.title }}
                        </div>
                        <v-icon :color="stat.color" size="24">
                            {{ stat.icon }}
                        </v-icon>
                    </div>
                    <div :class="`text-h4 font-weight-bold ${stat.color}`">
                        {{ stat.value }}
                    </div>
                </v-card>
            </v-col>
        </v-row>

        <!-- Quick Actions -->
        <div class="mb-8">
            <v-btn color="primary" size="large" class="mr-4 mb-2" :to="{ name: 'orders.create' }">
                <v-icon left>mdi-plus</v-icon>
                Place New Order
            </v-btn>
            <v-btn variant="outlined" size="large" class="mb-2" :to="{ name: 'products' }">
                Browse Menu
            </v-btn>
        </div>

        <!-- Recent Orders -->
        <v-card elevation="2">
            <v-card-title class="text-h5">
                Recent Orders
            </v-card-title>
            <v-card-text>
                <template v-if="recentOrders.length > 0">
                    <v-list>
                        <v-list-item v-for="order in recentOrders" :key="order.id" class="mb-2"
                            :class="order.status === 'pending' ? 'bg-yellow-lighten-5' : ''">
                            <template v-slot:prepend>
                                <v-icon color="primary">mdi-receipt</v-icon>
                            </template>

                            <v-list-item-title class="font-weight-bold">
                                Order #{{ order.order_number }}
                            </v-list-item-title>

                            <v-list-item-subtitle>
                                {{ formatDate(order.created_at) }}
                            </v-list-item-subtitle>

                            <template v-slot:append>
                                <div class="text-right">
                                    <div class="text-h6 font-weight-bold text-primary">
                                        ${{ formatPrice(order.total) }}
                                    </div>
                                    <div class="mt-2">
                                        <v-chip :color="getStatusColor(order.status)" size="small" class="mb-2">
                                            {{ capitalizeStatus(order.status) }}
                                        </v-chip>
                                    </div>
                                    <div class="d-flex gap-2">
                                        <v-btn size="small" variant="outlined"
                                            :to="{ name: 'orders.show', params: { order: order.id } }">
                                            <v-icon left size="small">mdi-eye</v-icon>
                                            View
                                        </v-btn>
                                        <v-btn v-if="order.bill && order.bill.payment_status !== 'paid'" size="small"
                                            color="primary"
                                            :to="{ name: 'bills.show', params: { bill: order.bill.id } }">
                                            Pay Now
                                        </v-btn>
                                    </div>
                                </div>
                            </template>
                        </v-list-item>
                    </v-list>

                    <div class="text-center mt-6">
                        <v-btn variant="outlined" :to="{ name: 'orders' }">
                            View All Orders
                            <v-icon right>mdi-arrow-right</v-icon>
                        </v-btn>
                    </div>
                </template>

                <template v-else>
                    <v-empty-state headline="No orders yet" title="Start your first order"
                        text="Browse our menu and place your first order to get started!"
                        :image="require('@/assets/images/empty-orders.svg')">
                        <v-btn color="primary" :to="{ name: 'orders.create' }">
                            Place Your First Order
                        </v-btn>
                    </v-empty-state>
                </template>
            </v-card-text>
        </v-card>
    </AppLayout>
</template>

<script setup>
    import { computed } from 'vue';
    import { Head } from '@inertiajs/vue3';
    import AppLayout from '@/Layouts/AppLayout.vue';

    const props = defineProps({
        recentOrders: {
            type: Array,
            default: () => []
        },
        stats: {
            type: Object,
            required: true
        }
    });

    const statsCards = computed(() => [
        {
            title: 'Total Orders',
            value: props.stats.total_orders,
            icon: 'mdi-shopping',
            color: 'text-grey-darken-3'
        },
        {
            title: 'Pending',
            value: props.stats.pending_orders,
            icon: 'mdi-clock-outline',
            color: 'text-yellow-darken-2'
        },
        {
            title: 'Completed',
            value: props.stats.completed_orders,
            icon: 'mdi-check-circle',
            color: 'text-green-darken-2'
        },
        {
            title: 'Total Spent',
            value: `$${formatPrice(props.stats.total_spent)}`,
            icon: 'mdi-currency-usd',
            color: 'text-primary'
        }
    ]);

    const formatDate = (dateString) => {
        return new Date(dateString).toLocaleDateString('en-US', {
            month: 'short',
            day: 'numeric',
            year: 'numeric',
            hour: '2-digit',
            minute: '2-digit'
        });
    };

    const formatPrice = (price) => {
        const numPrice = typeof price === 'number' ? price : parseFloat(price);
        return numPrice.toFixed(2);
    };

    const getStatusColor = (status) => {
        const colors = {
            delivered: 'success',
            cancelled: 'error',
            preparing: 'info',
            pending: 'warning',
            confirmed: 'primary',
            ready: 'purple'
        };
        return colors[status] || 'grey';
    };

    const capitalizeStatus = (status) => {
        return status.charAt(0).toUpperCase() + status.slice(1);
    };
</script>

// resources/js/Pages/Dashboard/Customer.tsx
import { Head, Link } from '@inertiajs/react';
import AppLayout from '@/Layouts/AppLayout';
import { Order } from '@/types';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Plus, ShoppingBag, Clock, CheckCircle, DollarSign, Eye } from 'lucide-react';

interface Props {
    recentOrders: Order[];
    stats: {
        total_orders: number;
        pending_orders: number;
        completed_orders: number;
        total_spent: number;
    };
}

const statusColors: Record<string, string> = {
    delivered: 'bg-green-100 text-green-800',
    cancelled: 'bg-red-100 text-red-800',
    preparing: 'bg-blue-100 text-blue-800',
    pending: 'bg-yellow-100 text-yellow-800',
    confirmed: 'bg-indigo-100 text-indigo-800',
    ready: 'bg-purple-100 text-purple-800',
};

export default function Customer({ recentOrders, stats }: Props) {
    return (
        <AppLayout>
            <Head title="Dashboard" />

            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                {/* Welcome Section */}
                <div className="mb-8">
                    <h1 className="text-3xl font-bold text-gray-900">Welcome back!</h1>
                    <p className="text-gray-600">Here's an overview of your orders</p>
                </div>

                {/* Statistics Cards */}
                <div className="grid grid-cols-1 md:grid-cols-4 gap-6 mb-8">
                    <Card>
                        <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                            <CardTitle className="text-sm font-medium text-gray-500">
                                Total Orders
                            </CardTitle>
                            <ShoppingBag className="h-4 w-4 text-gray-400" />
                        </CardHeader>
                        <CardContent>
                            <div className="text-3xl font-bold text-gray-900">{stats.total_orders}</div>
                        </CardContent>
                    </Card>

                    <Card>
                        <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                            <CardTitle className="text-sm font-medium text-gray-500">
                                Pending
                            </CardTitle>
                            <Clock className="h-4 w-4 text-yellow-600" />
                        </CardHeader>
                        <CardContent>
                            <div className="text-3xl font-bold text-yellow-600">{stats.pending_orders}</div>
                        </CardContent>
                    </Card>

                    <Card>
                        <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                            <CardTitle className="text-sm font-medium text-gray-500">
                                Completed
                            </CardTitle>
                            <CheckCircle className="h-4 w-4 text-green-600" />
                        </CardHeader>
                        <CardContent>
                            <div className="text-3xl font-bold text-green-600">{stats.completed_orders}</div>
                        </CardContent>
                    </Card>

                    <Card>
                        <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                            <CardTitle className="text-sm font-medium text-gray-500">
                                Total Spent
                            </CardTitle>
                            <DollarSign className="h-4 w-4 text-indigo-600" />
                        </CardHeader>
                        <CardContent>
                            <div className="text-3xl font-bold text-indigo-600">
                                ${typeof stats.total_spent === 'number' ? stats.total_spent.toFixed(2) : stats.total_spent}
                            </div>
                        </CardContent>
                    </Card>
                </div>

                {/* Quick Actions */}
                <div className="mb-8 flex flex-wrap gap-4">
                    <Link href="/orders/create">
                        <Button size="lg">
                            <Plus className="w-5 h-5 mr-2" />
                            Place New Order
                        </Button>
                    </Link>
                    <Link href="/products">
                        <Button variant="outline" size="lg">
                            Browse Menu
                        </Button>
                    </Link>
                </div>

                {/* Recent Orders */}
                <Card>
                    <CardHeader>
                        <CardTitle className="text-xl">Recent Orders</CardTitle>
                    </CardHeader>
                    <CardContent>
                        {recentOrders.length > 0 ? (
                            <div className="divide-y divide-gray-200">
                                {recentOrders.map((order) => (
                                    <div key={order.id} className="py-4 hover:bg-gray-50 rounded-lg px-4 transition-colors">
                                        <div className="flex justify-between items-start">
                                            <div className="flex-1">
                                                <div className="font-medium text-gray-900">
                                                    Order #{order.order_number}
                                                </div>
                                                <div className="text-sm text-gray-500">
                                                    {new Date(order.created_at).toLocaleDateString('en-US', {
                                                        month: 'short',
                                                        day: 'numeric',
                                                        year: 'numeric',
                                                        hour: '2-digit',
                                                        minute: '2-digit'
                                                    })}
                                                </div>
                                                <div className="mt-2">
                                                    <Badge className={statusColors[order.status]}>
                                                        {order.status.charAt(0).toUpperCase() + order.status.slice(1)}
                                                    </Badge>
                                                </div>
                                            </div>
                                            <div className="text-right">
                                                <div className="text-lg font-semibold text-gray-900">
                                                    ${typeof order.total === 'number' ? order.total.toFixed(2) : order.total}
                                                </div>
                                                <div className="mt-2 flex gap-2">
                                                    <Link href={`/orders/${order.id}`}>
                                                        <Button size="sm" variant="outline">
                                                            <Eye className="w-4 h-4 mr-1" />
                                                            View
                                                        </Button>
                                                    </Link>
                                                    {order.bill && order.bill.payment_status !== 'paid' && (
                                                        <Link href={`/bills/${order.bill.id}`}>
                                                            <Button size="sm" variant="default">
                                                                Pay Now
                                                            </Button>
                                                        </Link>
                                                    )}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                ))}
                            </div>
                        ) : (
                            <div className="text-center py-12 text-gray-500">
                                No orders yet.{' '}
                                <Link href="/orders/create" className="text-indigo-600 hover:text-indigo-900 font-medium">
                                    Place your first order!
                                </Link>
                            </div>
                        )}

                        {recentOrders.length > 0 && (
                            <div className="mt-6 text-center">
                                <Link href="/orders">
                                    <Button variant="outline">
                                        View All Orders →
                                    </Button>
                                </Link>
                            </div>
                        )}
                    </CardContent>
                </Card>
            </div>
        </AppLayout>
    );
}
