// temp_backup/Orders/Show.vue
<template>
    <Head :title="`Order #${order.order_number}`" />

    <div class="tw-space-y-6">
        <!-- Header -->
        <div class="tw-flex tw-items-center tw-justify-between">
            <div>
                <h2 class="tw-text-2xl tw-font-bold tw-tracking-tight">
                    {{ __("Order") }} #{{ order.order_number }}
                </h2>
                <p class="tw-text-muted-foreground">
                    {{ __("Order details and status") }}
                </p>
            </div>
            <div class="tw-flex tw-gap-2">
                <Button
                    v-if="order.status === 'pending'"
                    variant="default"
                    @click="confirmOrder"
                >
                    <CheckCircle class="tw-w-4 tw-h-4 tw-mr-2" />
                    {{ __("Confirm Order") }}
                </Button>
                <Button
                    variant="outline"
                    @click="editOrder"
                >
                    <Edit class="tw-w-4 tw-h-4 tw-mr-2" />
                    {{ __("Update Status") }}
                </Button>
                <Button
                    variant="outline"
                    @click="goBack"
                >
                    <ArrowLeft class="tw-w-4 tw-h-4 tw-mr-2" />
                    {{ __("Back") }}
                </Button>
            </div>
        </div>

        <!-- Order Information -->
        <div class="tw-grid tw-grid-cols-1 lg:tw-grid-cols-3 tw-gap-6">
            <!-- Main Content -->
            <div class="tw-lg:col-span-2 tw-space-y-6">
                <!-- Order Status & Details -->
                <Card>
                    <CardHeader>
                        <div class="tw-flex tw-items-center tw-justify-between">
                            <CardTitle>{{ __("Order Information") }}</CardTitle>
                            <Badge :variant="getStatusVariant(order.status)" class="tw-text-base">
                                {{ getStatusText(order.status) }}
                            </Badge>
                        </div>
                    </CardHeader>
                    <CardContent class="tw-space-y-4">
                        <div class="tw-grid tw-grid-cols-2 tw-gap-4">
                            <div>
                                <Label class="tw-text-muted-foreground">{{ __("Order Number") }}</Label>
                                <p class="tw-text-lg tw-font-semibold">#{{ order.order_number }}</p>
                            </div>
                            <div>
                                <Label class="tw-text-muted-foreground">{{ __("Order Date") }}</Label>
                                <p class="tw-text-lg">{{ new Date(order.created_at).toLocaleString() }}</p>
                            </div>
                        </div>

                        <div class="tw-grid tw-grid-cols-2 tw-gap-4">
                            <div>
                                <Label class="tw-text-muted-foreground">{{ __("Customer") }}</Label>
                                <p class="tw-font-semibold">{{ order.customer?.name }}</p>
                                <p class="tw-text-sm tw-text-muted-foreground">{{ order.customer?.email }}</p>
                            </div>
                            <div>
                                <Label class="tw-text-muted-foreground">{{ __("Payment Status") }}</Label>
                                <p>
                                    <Badge :variant="order.bill?.payment_status === 'paid' ? 'success' : 'secondary'">
                                        {{ order.bill?.payment_status || __("Unpaid") }}
                                    </Badge>
                                </p>
                            </div>
                        </div>

                        <div>
                            <Label class="tw-text-muted-foreground">{{ __("Delivery Address") }}</Label>
                            <p class="tw-flex tw-items-start tw-gap-2 tw-mt-1">
                                <MapPin class="tw-w-4 tw-h-4 tw-mt-0.5" />
                                <span>{{ order.delivery_address }}</span>
                            </p>
                        </div>

                        <div v-if="order.notes">
                            <Label class="tw-text-muted-foreground">{{ __("Notes") }}</Label>
                            <p class="tw-mt-1">{{ order.notes }}</p>
                        </div>
                    </CardContent>
                </Card>

                <!-- Order Items -->
                <Card>
                    <CardHeader>
                        <CardTitle>{{ __("Order Items") }}</CardTitle>
                    </CardHeader>
                    <CardContent>
                        <div class="tw-space-y-2">
                            <div
                                v-for="item in order.items"
                                :key="item.id"
                                class="tw-flex tw-items-center tw-justify-between tw-p-3 tw-rounded-lg tw-border"
                            >
                                <div class="tw-flex tw-items-center tw-gap-3 tw-flex-1">
                                    <div class="tw-w-12 tw-h-12 tw-rounded-lg tw-bg-muted tw-flex tw-items-center tw-justify-center tw-overflow-hidden">
                                        <img
                                            v-if="item.product?.image"
                                            :src="`/storage/${item.product.image}`"
                                            :alt="item.product.name"
                                            class="tw-w-full tw-h-full tw-object-cover"
                                        />
                                        <Package v-else class="tw-w-6 tw-h-6 tw-text-muted-foreground" />
                                    </div>
                                    <div class="tw-flex-1">
                                        <p class="tw-font-medium">{{ item.product?.name }}</p>
                                        <p class="tw-text-sm tw-text-muted-foreground">
                                            {{ item.product?.category?.name }}
                                        </p>
                                        <p v-if="item.special_instructions" class="tw-text-xs tw-text-muted-foreground tw-mt-1">
                                            <span class="tw-font-semibold">{{ __("Note:") }}</span> {{ item.special_instructions }}
                                        </p>
                                    </div>
                                </div>
                                <div class="tw-text-right">
                                    <p class="tw-text-sm tw-text-muted-foreground">
                                        {{ item.quantity }} x ${{ item.unit_price }}
                                    </p>
                                    <p class="tw-font-semibold">${{ item.subtotal }}</p>
                                </div>
                            </div>
                        </div>

                        <!-- Order Summary -->
                        <div class="tw-mt-6 tw-pt-6 tw-border-t tw-space-y-2">
                            <div class="tw-flex tw-justify-between tw-text-sm">
                                <span class="tw-text-muted-foreground">{{ __("Subtotal") }}</span>
                                <span>${{ order.subtotal }}</span>
                            </div>
                            <div class="tw-flex tw-justify-between tw-text-sm">
                                <span class="tw-text-muted-foreground">{{ __("Tax") }}</span>
                                <span>${{ order.tax }}</span>
                            </div>
                            <div class="tw-flex tw-justify-between tw-text-lg tw-font-bold tw-pt-2 tw-border-t">
                                <span>{{ __("Total") }}</span>
                                <span>${{ order.total }}</span>
                            </div>
                        </div>
                    </CardContent>
                </Card>
            </div>

            <!-- Sidebar -->
            <div class="tw-space-y-6">
                <!-- Quick Actions -->
                <Card>
                    <CardHeader>
                        <CardTitle>{{ __("Quick Actions") }}</CardTitle>
                    </CardHeader>
                    <CardContent class="tw-space-y-2">
                        <Button
                            v-if="order.status === 'pending'"
                            variant="default"
                            class="tw-w-full tw-justify-start"
                            @click="confirmOrder"
                        >
                            <CheckCircle class="tw-w-4 tw-h-4 tw-mr-2" />
                            {{ __("Confirm Order") }}
                        </Button>
                        <Button
                            variant="outline"
                            class="tw-w-full tw-justify-start"
                            @click="editOrder"
                        >
                            <Edit class="tw-w-4 tw-h-4 tw-mr-2" />
                            {{ __("Update Status") }}
                        </Button>
                        <Button
                            variant="outline"
                            class="tw-w-full tw-justify-start"
                            @click="viewCustomer"
                        >
                            <User class="tw-w-4 tw-h-4 tw-mr-2" />
                            {{ __("View Customer") }}
                        </Button>
                        <Button
                            v-if="order.status === 'pending'"
                            variant="outline"
                            class="tw-w-full tw-justify-start tw-text-destructive hover:tw-text-destructive"
                            @click="cancelOrder"
                        >
                            <XCircle class="tw-w-4 tw-h-4 tw-mr-2" />
                            {{ __("Cancel Order") }}
                        </Button>
                    </CardContent>
                </Card>

                <!-- Order Timeline -->
                <Card>
                    <CardHeader>
                        <CardTitle>{{ __("Order Timeline") }}</CardTitle>
                    </CardHeader>
                    <CardContent class="tw-space-y-3 tw-text-sm">
                        <div class="tw-flex tw-items-center tw-gap-2">
                            <div class="tw-w-2 tw-h-2 tw-rounded-full" :class="order.status === 'pending' ? 'tw-bg-warning' : 'tw-bg-success'"></div>
                            <span>{{ __("Order Placed") }}</span>
                            <span class="tw-ml-auto tw-text-muted-foreground">
                                {{ new Date(order.created_at).toLocaleTimeString() }}
                            </span>
                        </div>
                        <div v-if="order.confirmed_at" class="tw-flex tw-items-center tw-gap-2">
                            <div class="tw-w-2 tw-h-2 tw-rounded-full tw-bg-success"></div>
                            <span>{{ __("Confirmed") }}</span>
                            <span class="tw-ml-auto tw-text-muted-foreground">
                                {{ new Date(order.confirmed_at).toLocaleTimeString() }}
                            </span>
                        </div>
                        <div v-if="order.delivered_at" class="tw-flex tw-items-center tw-gap-2">
                            <div class="tw-w-2 tw-h-2 tw-rounded-full tw-bg-success"></div>
                            <span>{{ __("Delivered") }}</span>
                            <span class="tw-ml-auto tw-text-muted-foreground">
                                {{ new Date(order.delivered_at).toLocaleTimeString() }}
                            </span>
                        </div>
                    </CardContent>
                </Card>
            </div>
        </div>
    </div>
</template>

<script setup>
import { router } from "@inertiajs/vue3";
import { Head } from "@inertiajs/vue3";
import { Button } from "@/Components/ui/button";
import { Label } from "@/Components/ui/label";
import { Badge } from "@/Components/ui/badge";
import {
    Card,
    CardContent,
    CardHeader,
    CardTitle,
} from "@/Components/ui/card";
import {
    Edit,
    ArrowLeft,
    Package,
    MapPin,
    User,
    CheckCircle,
    XCircle,
} from "lucide-vue-next";
import { useToast } from "@/Components/ui/toast/use-toast";

const { toast } = useToast();

const props = defineProps({
    order: {
        type: Object,
        required: true,
    },
});

const getStatusVariant = (status) => {
    const variants = {
        pending: 'warning',
        confirmed: 'default',
        preparing: 'default',
        ready: 'default',
        delivered: 'success',
        cancelled: 'destructive'
    };
    return variants[status] || 'secondary';
};

const getStatusText = (status) => {
    return status.charAt(0).toUpperCase() + status.slice(1);
};

const goBack = () => {
    router.visit(route("dashboard.orders.index"));
};

const editOrder = () => {
    router.visit(route("dashboard.orders.edit", props.order.id));
};

const viewCustomer = () => {
    router.visit(route("dashboard.users.show", props.order.customer.id));
};

const confirmOrder = () => {
    if (!confirm(__("Confirm this order?"))) return;

    router.post(route("dashboard.orders.confirm", props.order.id), {}, {
        onSuccess: () => {
            toast({
                title: __("Success"),
                description: __("Order confirmed successfully"),
            });
        },
        onError: () => {
            toast({
                title: __("Error"),
                description: __("Failed to confirm order"),
                variant: "destructive",
            });
        },
    });
};

const cancelOrder = () => {
    if (!confirm(__("Cancel this order? This action cannot be undone."))) return;

    router.post(route("dashboard.orders.cancel", props.order.id), {}, {
        onSuccess: () => {
            toast({
                title: __("Success"),
                description: __("Order cancelled successfully"),
            });
        },
        onError: () => {
            toast({
                title: __("Error"),
                description: __("Failed to cancel order"),
                variant: "destructive",
            });
        },
    });
};
</script>

// resources/js/Pages/Bills/Show.tsx
import { FormEventHandler } from 'react';
import { Head, Link, useForm, router } from '@inertiajs/react';
import AppLayout from '@/Layouts/AppLayout';
import { Bill } from '@/types';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Separator } from '@/components/ui/separator';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { ArrowLeft, CreditCard, Download, DollarSign, RotateCcw } from 'lucide-react';
import { formatPrice, formatDateTime } from '@/lib/utils';

interface Props {
    bill: Bill;
    auth?: {
        user?: any;
    };
}

const paymentStatusColors = {
    unpaid: 'bg-red-100 text-red-800 border-red-200',
    paid: 'bg-green-100 text-green-800 border-green-200',
    refunded: 'bg-gray-100 text-gray-800 border-gray-200',
};

export default function Show({ bill, auth }: Props) {
    const { data, setData, post, processing } = useForm({
        payment_method: 'card' as 'cash' | 'card' | 'online',
    });

    const handlePayment: FormEventHandler = (e) => {
        e.preventDefault();
        post(`/bills/${bill.id}/payment`);
    };

    const handleRefund = () => {
        if (confirm('Are you sure you want to refund this bill?')) {
            router.post(`/manager/bills/${bill.id}/refund`, {});
        }
    };

    const handleDownload = () => {
        window.location.href = `/bills/${bill.id}/download`;
    };

    const isManager = auth?.user?.role === 'manager';

    return (
        <AppLayout>
            <Head title={`Bill #${bill.bill_number}`} />

            <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
                <Link href="/orders">
                    <Button variant="outline" className="mb-6">
                        <ArrowLeft className="w-4 h-4 mr-2" />
                        Back to Orders
                    </Button>
                </Link>

                <Card>
                    <CardHeader>
                        <div className="flex justify-between items-start">
                            <div>
                                <CardTitle className="text-2xl">Bill #{bill.bill_number}</CardTitle>
                                <CardDescription>
                                    Order #{bill.order?.order_number}
                                </CardDescription>
                            </div>
                            <Badge className={paymentStatusColors[bill.payment_status]}>
                                {bill.payment_status.charAt(0).toUpperCase() + bill.payment_status.slice(1)}
                            </Badge>
                        </div>
                    </CardHeader>
                    <CardContent className="space-y-6">
                        {/* Bill Information */}
                        <div className="grid grid-cols-2 gap-4">
                            <div>
                                <p className="text-sm text-gray-600">Issue Date</p>
                                <p className="font-medium">{formatDateTime(bill.created_at)}</p>
                            </div>
                            {bill.paid_at && (
                                <div>
                                    <p className="text-sm text-gray-600">Paid Date</p>
                                    <p className="font-medium">{formatDateTime(bill.paid_at)}</p>
                                </div>
                            )}
                            {bill.payment_method && (
                                <div>
                                    <p className="text-sm text-gray-600">Payment Method</p>
                                    <p className="font-medium capitalize">{bill.payment_method}</p>
                                </div>
                            )}
                        </div>

                        <Separator />

                        {/* Customer Information */}
                        {bill.order?.customer && (
                            <div>
                                <h3 className="text-lg font-semibold mb-2">Customer Information</h3>
                                <div className="bg-gray-50 rounded-lg p-4">
                                    <p className="font-medium">{bill.order.customer.name}</p>
                                    <p className="text-sm text-gray-600">{bill.order.customer.email}</p>
                                    {bill.order.customer.phone && (
                                        <p className="text-sm text-gray-600">{bill.order.customer.phone}</p>
                                    )}
                                    {bill.order.delivery_address && (
                                        <div className="mt-2">
                                            <p className="text-sm font-medium">Delivery Address:</p>
                                            <p className="text-sm text-gray-600">{bill.order.delivery_address}</p>
                                        </div>
                                    )}
                                </div>
                            </div>
                        )}

                        <Separator />

                        {/* Order Items */}
                        {bill.order?.items && (
                            <div>
                                <h3 className="text-lg font-semibold mb-4">Order Items</h3>
                                <div className="space-y-3">
                                    {bill.order.items.map((item) => (
                                        <div key={item.id} className="flex justify-between items-center border-b pb-3">
                                            <div className="flex-1">
                                                <p className="font-medium">{item.product?.name}</p>
                                                <p className="text-sm text-gray-600">
                                                    {formatPrice(item.unit_price)} × {item.quantity}
                                                </p>
                                                {item.special_instructions && (
                                                    <p className="text-xs text-orange-600 mt-1">
                                                        Note: {item.special_instructions}
                                                    </p>
                                                )}
                                            </div>
                                            <div className="text-right">
                                                <p className="font-bold">{formatPrice(item.subtotal)}</p>
                                            </div>
                                        </div>
                                    ))}
                                </div>

                                <div className="mt-6 space-y-2">
                                    <div className="flex justify-between text-sm">
                                        <span>Subtotal:</span>
                                        <span>{formatPrice(bill.order.subtotal)}</span>
                                    </div>
                                    <div className="flex justify-between text-sm">
                                        <span>Tax (10%):</span>
                                        <span>{formatPrice(bill.order.tax)}</span>
                                    </div>
                                    <Separator />
                                    <div className="flex justify-between text-2xl font-bold">
                                        <span>Total Amount:</span>
                                        <span className="text-indigo-600">{formatPrice(bill.amount)}</span>
                                    </div>
                                </div>
                            </div>
                        )}

                        <Separator />

                        {/* Payment Section */}
                        {bill.payment_status === 'unpaid' && !isManager && (
                            <form onSubmit={handlePayment}>
                                <Card className="bg-indigo-50 border-indigo-200">
                                    <CardHeader>
                                        <CardTitle className="text-lg">Make Payment</CardTitle>
                                        <CardDescription>Choose a payment method</CardDescription>
                                    </CardHeader>
                                    <CardContent className="space-y-4">
                                        <Select
                                            value={data.payment_method}
                                            onValueChange={(value: any) => setData('payment_method', value)}
                                        >
                                            <SelectTrigger>
                                                <SelectValue />
                                            </SelectTrigger>
                                            <SelectContent>
                                                <SelectItem value="cash">Cash</SelectItem>
                                                <SelectItem value="card">Credit/Debit Card</SelectItem>
                                                <SelectItem value="online">Online Payment</SelectItem>
                                            </SelectContent>
                                        </Select>

                                        <Button type="submit" className="w-full" disabled={processing}>
                                            <CreditCard className="w-4 h-4 mr-2" />
                                            Pay {formatPrice(bill.amount)}
                                        </Button>
                                    </CardContent>
                                </Card>
                            </form>
                        )}

                        {/* Manager Actions */}
                        <div className="flex gap-2">
                            <Button variant="outline" onClick={handleDownload} className="flex-1">
                                <Download className="w-4 h-4 mr-2" />
                                Download PDF
                            </Button>

                            {isManager && bill.payment_status === 'paid' && (
                                <Button variant="destructive" onClick={handleRefund}>
                                    <RotateCcw className="w-4 h-4 mr-2" />
                                    Refund
                                </Button>
                            )}
                        </div>

                        {bill.payment_status === 'paid' && (
                            <div className="bg-green-50 border border-green-200 rounded-lg p-4">
                                <div className="flex items-center gap-2 text-green-800">
                                    <DollarSign className="w-5 h-5" />
                                    <div>
                                        <p className="font-semibold">Payment Received</p>
                                        <p className="text-sm">
                                            Paid on {formatDateTime(bill.paid_at!)} via {bill.payment_method}
                                        </p>
                                    </div>
                                </div>
                            </div>
                        )}

                        {bill.payment_status === 'refunded' && (
                            <div className="bg-gray-50 border border-gray-200 rounded-lg p-4">
                                <div className="flex items-center gap-2 text-gray-800">
                                    <RotateCcw className="w-5 h-5" />
                                    <div>
                                        <p className="font-semibold">Payment Refunded</p>
                                        <p className="text-sm">This bill has been refunded</p>
                                    </div>
                                </div>
                            </div>
                        )}
                    </CardContent>
                </Card>
            </div>
        </AppLayout>
    );
}
