// resources/js/Pages/Dashboard/Inventory/Create.vue
<template>
    <Head :title="__('Add Inventory Item')" />

    <vee-form
        :validation-schema="schema"
        @submit="submit"
        v-slot="{ meta, setErrors }"
    >
        <div class="tw-space-y-6">
            <!-- Header -->
            <div class="tw-flex tw-items-center tw-justify-between">
                <div>
                    <h2 class="tw-text-2xl tw-font-bold tw-tracking-tight">
                        {{ __("Add Inventory Item") }}
                    </h2>
                    <p class="tw-text-muted-foreground">
                        {{ __("Create new inventory record for a product") }}
                    </p>
                </div>
                <Button
                    variant="outline"
                    @click="goBack"
                >
                    <ArrowLeft class="tw-w-4 tw-h-4 tw-mr-2" />
                    {{ __("Back") }}
                </Button>
            </div>

            <!-- Form -->
            <div class="tw-grid tw-grid-cols-1 lg:tw-grid-cols-3 tw-gap-6">
                <!-- Main Form -->
                <div class="tw-lg:col-span-2 tw-space-y-6">
                    <!-- Product Selection -->
                    <Card>
                        <CardHeader>
                            <CardTitle>{{ __("Select Product") }}</CardTitle>
                            <CardDescription>
                                {{ __("Choose a product to add inventory tracking") }}
                            </CardDescription>
                        </CardHeader>
                        <CardContent class="tw-space-y-4">
                            <vee-field
                                name="product_id"
                                v-slot="{ field, errors }"
                            >
                                <div class="tw-space-y-2">
                                    <Label for="product_id">
                                        {{ __("Product") }}
                                        <span class="tw-text-destructive">*</span>
                                    </Label>
                                    <Select
                                        v-model="form.product_id"
                                        @update:model-value="(val) => form.product_id = val"
                                    >
                                        <SelectTrigger id="product_id">
                                            <SelectValue :placeholder="__('Select a product')" />
                                        </SelectTrigger>
                                        <SelectContent>
                                            <SelectItem 
                                                v-for="product in products" 
                                                :key="product.id" 
                                                :value="product.id"
                                            >
                                                {{ product.name }} - {{ product.category?.name }}
                                            </SelectItem>
                                        </SelectContent>
                                    </Select>
                                    <p v-if="errors.length" class="tw-text-sm tw-text-destructive">
                                        {{ errors[0] }}
                                    </p>
                                </div>
                            </vee-field>

                            <!-- Selected Product Preview -->
                            <div v-if="selectedProduct" class="tw-p-4 tw-rounded-lg tw-border tw-bg-muted/50">
                                <div class="tw-flex tw-items-center tw-gap-4">
                                    <div class="tw-w-16 tw-h-16 tw-rounded-lg tw-bg-muted tw-flex tw-items-center tw-justify-center tw-overflow-hidden">
                                        <img
                                            v-if="selectedProduct.image"
                                            :src="`/storage/${selectedProduct.image}`"
                                            :alt="selectedProduct.name"
                                            class="tw-w-full tw-h-full tw-object-cover"
                                        />
                                        <Package v-else class="tw-w-8 tw-h-8 tw-text-muted-foreground" />
                                    </div>
                                    <div class="tw-flex-1">
                                        <p class="tw-font-semibold">{{ selectedProduct.name }}</p>
                                        <p class="tw-text-sm tw-text-muted-foreground">
                                            {{ selectedProduct.category?.name }} • ${{ selectedProduct.price }}
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </CardContent>
                    </Card>

                    <!-- Stock Information -->
                    <Card>
                        <CardHeader>
                            <CardTitle>{{ __("Stock Information") }}</CardTitle>
                            <CardDescription>
                                {{ __("Set initial stock levels") }}
                            </CardDescription>
                        </CardHeader>
                        <CardContent class="tw-space-y-4">
                            <vee-field
                                name="quantity"
                                v-slot="{ field, errors }"
                            >
                                <div class="tw-space-y-2">
                                    <Label for="quantity">
                                        {{ __("Initial Quantity") }}
                                        <span class="tw-text-destructive">*</span>
                                    </Label>
                                    <Input
                                        id="quantity"
                                        type="number"
                                        min="0"
                                        v-bind="field"
                                        :model-value="form.quantity"
                                        @update:model-value="(val) => form.quantity = parseInt(val)"
                                        :class="{ 'tw-border-destructive': errors.length }"
                                        :placeholder="__('Enter initial stock quantity')"
                                    />
                                    <p v-if="errors.length" class="tw-text-sm tw-text-destructive">
                                        {{ errors[0] }}
                                    </p>
                                </div>
                            </vee-field>

                            <vee-field
                                name="minimum_stock"
                                v-slot="{ field, errors }"
                            >
                                <div class="tw-space-y-2">
                                    <Label for="minimum_stock">
                                        {{ __("Minimum Stock Threshold") }}
                                        <span class="tw-text-destructive">*</span>
                                    </Label>
                                    <Input
                                        id="minimum_stock"
                                        type="number"
                                        min="0"
                                        v-bind="field"
                                        :model-value="form.minimum_stock"
                                        @update:model-value="(val) => form.minimum_stock = parseInt(val)"
                                        :class="{ 'tw-border-destructive': errors.length }"
                                        :placeholder="__('Enter minimum stock level')"
                                    />
                                    <p v-if="errors.length" class="tw-text-sm tw-text-destructive">
                                        {{ errors[0] }}
                                    </p>
                                    <p class="tw-text-sm tw-text-muted-foreground">
                                        {{ __("Alert will trigger when stock reaches this level") }}
                                    </p>
                                </div>
                            </vee-field>

                            <!-- Stock Status Preview -->
                            <div v-if="form.quantity !== null && form.minimum_stock !== null" class="tw-p-4 tw-rounded-lg tw-bg-muted/50 tw-mt-6">
                                <Label class="tw-text-muted-foreground tw-text-sm">{{ __("Stock Status Preview") }}</Label>
                                <div class="tw-flex tw-items-center tw-gap-4 tw-mt-2">
                                    <div>
                                        <p class="tw-text-2xl tw-font-bold">{{ form.quantity || 0 }}</p>
                                        <p class="tw-text-xs tw-text-muted-foreground">{{ __("Initial") }}</p>
                                    </div>
                                    <div class="tw-text-muted-foreground">/</div>
                                    <div>
                                        <p class="tw-text-2xl tw-font-bold">{{ form.minimum_stock || 0 }}</p>
                                        <p class="tw-text-xs tw-text-muted-foreground">{{ __("Minimum") }}</p>
                                    </div>
                                    <div class="tw-ml-auto">
                                        <Badge :variant="getStatusVariant()">
                                            {{ getStatusText() }}
                                        </Badge>
                                    </div>
                                </div>
                            </div>
                        </CardContent>
                    </Card>
                </div>

                <!-- Sidebar -->
                <div class="tw-space-y-6">
                    <!-- Actions -->
                    <Card>
                        <CardHeader>
                            <CardTitle>{{ __("Actions") }}</CardTitle>
                        </CardHeader>
                        <CardContent class="tw-space-y-2">
                            <Button
                                type="submit"
                                class="tw-w-full"
                                :disabled="!meta.valid || form.processing"
                            >
                                <Loader2
                                    v-if="form.processing"
                                    class="tw-h-4 tw-w-4 tw-mr-2 tw-animate-spin"
                                />
                                <Plus v-else class="tw-h-4 tw-w-4 tw-mr-2" />
                                {{ __("Create Inventory") }}
                            </Button>
                            <Button
                                type="button"
                                variant="outline"
                                class="tw-w-full"
                                @click="goBack"
                            >
                                {{ __("Cancel") }}
                            </Button>
                        </CardContent>
                    </Card>

                    <!-- Tips -->
                    <Card>
                        <CardHeader>
                            <CardTitle>{{ __("Tips") }}</CardTitle>
                        </CardHeader>
                        <CardContent class="tw-text-sm tw-text-muted-foreground tw-space-y-2">
                            <p>• {{ __("Select a product without inventory") }}</p>
                            <p>• {{ __("Set minimum stock for alerts") }}</p>
                            <p>• {{ __("You can adjust quantities later") }}</p>
                        </CardContent>
                    </Card>
                </div>
            </div>
        </div>
    </vee-form>
</template>

<script setup>
import { computed } from "vue";
import { useForm } from "@inertiajs/vue3";
import { router, Head } from "@inertiajs/vue3";
import { Button } from "@/Components/ui/button";
import { Input } from "@/Components/ui/input";
import { Label } from "@/Components/ui/label";
import { Badge } from "@/Components/ui/badge";
import {
    Card,
    CardContent,
    CardDescription,
    CardHeader,
    CardTitle,
} from "@/Components/ui/card";
import {
    Select,
    SelectContent,
    SelectItem,
    SelectTrigger,
    SelectValue,
} from "@/Components/ui/select";
import { Loader2, Plus, ArrowLeft, Package } from "lucide-vue-next";
import { useToast } from "@/Components/ui/toast/use-toast";
import * as yup from "yup";

const { toast } = useToast();

const props = defineProps({
    products: {
        type: Array,
        default: () => [],
    },
});

const schema = yup.object({
    product_id: yup.string().required(__("Product is required")),
    quantity: yup.number().required(__("Quantity is required")).min(0, __("Quantity must be positive")),
    minimum_stock: yup.number().required(__("Minimum stock is required")).min(0, __("Minimum stock must be positive")),
});

const form = useForm({
    product_id: "",
    quantity: 0,
    minimum_stock: 0,
});

const selectedProduct = computed(() => {
    return props.products.find(p => p.id === form.product_id);
});

const getStatusVariant = () => {
    if ((form.quantity || 0) === 0) return 'destructive';
    if ((form.quantity || 0) <= (form.minimum_stock || 0)) return 'warning';
    return 'success';
};

const getStatusText = () => {
    if ((form.quantity || 0) === 0) return __("Out of Stock");
    if ((form.quantity || 0) <= (form.minimum_stock || 0)) return __("Low Stock");
    return __("In Stock");
};

const submit = (setErrors) => {
    form.post(route("dashboard.inventory.store"), {
        onSuccess: () => {
            toast({
                title: __("Success"),
                description: __("Inventory created successfully"),
            });
        },
        onError: (errors) => {
            setErrors(errors);
            toast({
                title: __("Error"),
                description: __("Failed to create inventory"),
                variant: "destructive",
            });
        },
    });
};

const goBack = () => {
    router.visit(route("dashboard.inventory.index"));
};
</script>

// resources/js/Pages/Products/Create.tsx
import { FormEventHandler, useState } from 'react';
import { Head, Link, useForm } from '@inertiajs/react';
import AppLayout from '@/Layouts/AppLayout';
import { Category } from '@/types';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Checkbox } from '@/components/ui/checkbox';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { ArrowLeft, Save, Upload } from 'lucide-react';

interface Props {
    categories: Category[];
}

export default function Create({ categories }: Props) {
    const { data, setData, post, processing, errors } = useForm({
        category_id: '',
        name: '',
        description: '',
        price: '',
        image: null as File | null,
        is_available: true,
        initial_stock: '0',
        minimum_stock: '5',
    });

    const [imagePreview, setImagePreview] = useState<string | null>(null);

    const handleImageChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const file = e.target.files?.[0];
        if (file) {
            setData('image', file);
            const reader = new FileReader();
            reader.onloadend = () => {
                setImagePreview(reader.result as string);
            };
            reader.readAsDataURL(file);
        }
    };

    const submit: FormEventHandler = (e) => {
        e.preventDefault();
        post('/manager/products', {
            forceFormData: true,
        });
    };

    return (
        <AppLayout>
            <Head title="Create Product" />

            <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
                <Link href="/products">
                    <Button variant="outline" className="mb-6">
                        <ArrowLeft className="w-4 h-4 mr-2" />
                        Back to Products
                    </Button>
                </Link>

                <Card>
                    <CardHeader>
                        <CardTitle className="text-2xl">Create New Product</CardTitle>
                        <CardDescription>Add a new item to your menu</CardDescription>
                    </CardHeader>
                    <CardContent>
                        <form onSubmit={submit} className="space-y-6">
                            {/* Category */}
                            <div className="space-y-2">
                                <label className="text-sm font-medium">Category *</label>
                                <Select
                                    value={data.category_id}
                                    onValueChange={(value) => setData('category_id', value)}
                                >
                                    <SelectTrigger>
                                        <SelectValue placeholder="Select a category" />
                                    </SelectTrigger>
                                    <SelectContent>
                                        {categories.map((category) => (
                                            <SelectItem key={category.id} value={category.id.toString()}>
                                                {category.name}
                                            </SelectItem>
                                        ))}
                                    </SelectContent>
                                </Select>
                                {errors.category_id && (
                                    <p className="text-sm text-red-600">{errors.category_id}</p>
                                )}
                            </div>

                            {/* Name */}
                            <div className="space-y-2">
                                <label className="text-sm font-medium">Product Name *</label>
                                <Input
                                    type="text"
                                    value={data.name}
                                    onChange={(e) => setData('name', e.target.value)}
                                    placeholder="e.g., Margherita Pizza"
                                />
                                {errors.name && (
                                    <p className="text-sm text-red-600">{errors.name}</p>
                                )}
                            </div>

                            {/* Description */}
                            <div className="space-y-2">
                                <label className="text-sm font-medium">Description</label>
                                <textarea
                                    value={data.description}
                                    onChange={(e) => setData('description', e.target.value)}
                                    placeholder="Describe your product..."
                                    rows={4}
                                    className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
                                />
                                {errors.description && (
                                    <p className="text-sm text-red-600">{errors.description}</p>
                                )}
                            </div>

                            {/* Price */}
                            <div className="space-y-2">
                                <label className="text-sm font-medium">Price ($) *</label>
                                <Input
                                    type="number"
                                    step="0.01"
                                    min="0"
                                    value={data.price}
                                    onChange={(e) => setData('price', e.target.value)}
                                    placeholder="0.00"
                                />
                                {errors.price && (
                                    <p className="text-sm text-red-600">{errors.price}</p>
                                )}
                            </div>

                            {/* Image */}
                            <div className="space-y-2">
                                <label className="text-sm font-medium">Product Image</label>
                                <div className="space-y-4">
                                    {imagePreview && (
                                        <div className="w-full h-48 rounded-lg overflow-hidden bg-gray-100">
                                            <img
                                                src={imagePreview}
                                                alt="Preview"
                                                className="w-full h-full object-cover"
                                            />
                                        </div>
                                    )}
                                    <div className="flex items-center gap-2">
                                        <Input
                                            type="file"
                                            accept="image/*"
                                            onChange={handleImageChange}
                                            className="flex-1"
                                        />
                                        <Upload className="w-5 h-5 text-gray-400" />
                                    </div>
                                </div>
                                {errors.image && (
                                    <p className="text-sm text-red-600">{errors.image}</p>
                                )}
                            </div>

                            {/* Stock */}
                            <div className="grid grid-cols-2 gap-4">
                                <div className="space-y-2">
                                    <label className="text-sm font-medium">Initial Stock *</label>
                                    <Input
                                        type="number"
                                        min="0"
                                        value={data.initial_stock}
                                        onChange={(e) => setData('initial_stock', e.target.value)}
                                    />
                                    {errors.initial_stock && (
                                        <p className="text-sm text-red-600">{errors.initial_stock}</p>
                                    )}
                                </div>
                                <div className="space-y-2">
                                    <label className="text-sm font-medium">Minimum Stock *</label>
                                    <Input
                                        type="number"
                                        min="0"
                                        value={data.minimum_stock}
                                        onChange={(e) => setData('minimum_stock', e.target.value)}
                                    />
                                    {errors.minimum_stock && (
                                        <p className="text-sm text-red-600">{errors.minimum_stock}</p>
                                    )}
                                </div>
                            </div>

                            {/* Available */}
                            <div className="flex items-center space-x-2">
                                <Checkbox
                                    id="is_available"
                                    checked={data.is_available}
                                    onCheckedChange={(checked) => setData('is_available', checked as boolean)}
                                />
                                <label htmlFor="is_available" className="text-sm font-medium cursor-pointer">
                                    Available for purchase
                                </label>
                            </div>

                            {/* Submit */}
                            <div className="flex gap-2 pt-4">
                                <Button type="submit" disabled={processing} className="flex-1">
                                    <Save className="w-4 h-4 mr-2" />
                                    Create Product
                                </Button>
                                <Link href="/products">
                                    <Button type="button" variant="outline">
                                        Cancel
                                    </Button>
                                </Link>
                            </div>
                        </form>
                    </CardContent>
                </Card>
            </div>
        </AppLayout>
    );
}
