// resources/js/Pages/Dashboard/Products/Create.vue
<template>
    <Head :title="__('Create Product')" />

    <vee-form
        :validation-schema="schema"
        @submit="submit"
        v-slot="{ meta, setErrors }"
    >
        <div class="tw-space-y-6">
            <!-- Header -->
            <div class="tw-flex tw-items-center tw-justify-between">
                <div>
                    <h2 class="tw-text-2xl tw-font-bold tw-tracking-tight">
                        {{ __("Create Product") }}
                    </h2>
                    <p class="tw-text-muted-foreground">
                        {{ __("Add a new product to your menu") }}
                    </p>
                </div>
                <Button
                    variant="outline"
                    @click="goBack"
                >
                    <ArrowLeft class="tw-w-4 tw-h-4 tw-mr-2" />
                    {{ __("Back") }}
                </Button>
            </div>

            <!-- Form -->
            <div class="tw-grid tw-grid-cols-1 lg:tw-grid-cols-3 tw-gap-6">
                <!-- Main Form -->
                <div class="tw-lg:col-span-2 tw-space-y-6">
                    <!-- Basic Information -->
                    <Card>
                        <CardHeader>
                            <CardTitle>{{ __("Basic Information") }}</CardTitle>
                            <CardDescription>
                                {{ __("Enter the basic details of the product") }}
                            </CardDescription>
                        </CardHeader>
                        <CardContent class="tw-space-y-4">
                            <vee-field
                                name="name"
                                v-slot="{ field, errors }"
                            >
                                <div class="tw-space-y-2">
                                    <Label for="name">
                                        {{ __("Product Name") }}
                                        <span class="tw-text-destructive">*</span>
                                    </Label>
                                    <Input
                                        id="name"
                                        v-bind="field"
                                        :model-value="form.name"
                                        @update:model-value="(val) => form.name = val"
                                        :class="{ 'tw-border-destructive': errors.length }"
                                        :placeholder="__('Enter product name')"
                                    />
                                    <p v-if="errors.length" class="tw-text-sm tw-text-destructive">
                                        {{ errors[0] }}
                                    </p>
                                </div>
                            </vee-field>

                            <vee-field
                                name="description"
                                v-slot="{ field, errors }"
                            >
                                <div class="tw-space-y-2">
                                    <Label for="description">{{ __("Description") }}</Label>
                                    <Textarea
                                        id="description"
                                        v-bind="field"
                                        :model-value="form.description"
                                        @update:model-value="(val) => form.description = val"
                                        rows="3"
                                        :class="{ 'tw-border-destructive': errors.length }"
                                        :placeholder="__('Enter product description')"
                                    />
                                    <p v-if="errors.length" class="tw-text-sm tw-text-destructive">
                                        {{ errors[0] }}
                                    </p>
                                </div>
                            </vee-field>

                            <div class="tw-grid tw-grid-cols-1 md:tw-grid-cols-2 tw-gap-4">
                                <vee-field
                                    name="price"
                                    v-slot="{ field, errors }"
                                >
                                    <div class="tw-space-y-2">
                                        <Label for="price">
                                            {{ __("Price") }}
                                            <span class="tw-text-destructive">*</span>
                                        </Label>
                                        <Input
                                            id="price"
                                            type="number"
                                            step="0.01"
                                            min="0"
                                            v-bind="field"
                                            :model-value="form.price"
                                            @update:model-value="(val) => form.price = val"
                                            :class="{ 'tw-border-destructive': errors.length }"
                                            :placeholder="__('0.00')"
                                        />
                                        <p v-if="errors.length" class="tw-text-sm tw-text-destructive">
                                            {{ errors[0] }}
                                        </p>
                                    </div>
                                </vee-field>

                                <vee-field
                                    name="category_id"
                                    v-slot="{ field, errors }"
                                >
                                    <div class="tw-space-y-2">
                                        <Label for="category_id">
                                            {{ __("Category") }}
                                            <span class="tw-text-destructive">*</span>
                                        </Label>
                                        <Select
                                            v-bind="field"
                                            :model-value="form.category_id"
                                            @update:model-value="(val) => form.category_id = val"
                                        >
                                            <SelectTrigger
                                                id="category_id"
                                                :class="{ 'tw-border-destructive': errors.length }"
                                            >
                                                <SelectValue :placeholder="__('Select category')" />
                                            </SelectTrigger>
                                            <SelectContent>
                                                <SelectItem
                                                    v-for="category in categories"
                                                    :key="category.id"
                                                    :value="category.id.toString()"
                                                >
                                                    {{ category.name }}
                                                </SelectItem>
                                            </SelectContent>
                                        </Select>
                                        <p v-if="errors.length" class="tw-text-sm tw-text-destructive">
                                            {{ errors[0] }}
                                        </p>
                                    </div>
                                </vee-field>
                            </div>

                            <div class="tw-flex tw-items-center tw-space-x-2">
                                <Switch
                                    id="is_available"
                                    :model-value="form.is_available"
                                    @update:model-value="(val) => form.is_available = val"
                                />
                                <Label for="is_available">{{ __("Available for sale") }}</Label>
                            </div>
                        </CardContent>
                    </Card>

                    <!-- Image Upload -->
                    <Card>
                        <CardHeader>
                            <CardTitle>{{ __("Product Image") }}</CardTitle>
                            <CardDescription>
                                {{ __("Upload an image for the product") }}
                            </CardDescription>
                        </CardHeader>
                        <CardContent>
                            <div class="tw-space-y-4">
                                <div class="tw-flex tw-items-center tw-gap-4">
                                    <div v-if="imagePreview" class="tw-w-20 tw-h-20 tw-rounded-lg tw-overflow-hidden">
                                        <img
                                            :src="imagePreview"
                                            :alt="form.name"
                                            class="tw-w-full tw-h-full tw-object-cover"
                                        />
                                    </div>
                                    <div class="tw-flex-1">
                                        <Input
                                            type="file"
                                            accept="image/*"
                                            @change="handleImageUpload"
                                            class="tw-file:tw-mr-4 tw-file:tw-py-2 tw-file:tw-px-4 tw-file:tw-rounded-full tw-file:tw-border-0 tw-file:tw-text-sm tw-file:tw-font-semibold tw-file:tw-bg-primary tw-file:tw-text-primary-foreground tw-hover:tw-file:tw-bg-primary/90"
                                        />
                                        <p class="tw-text-sm tw-text-muted-foreground tw-mt-1">
                                            {{ __("Recommended size: 400x400px, max 2MB") }}
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </CardContent>
                    </Card>
                </div>

                <!-- Sidebar -->
                <div class="tw-space-y-6">
                    <!-- Actions -->
                    <Card>
                        <CardHeader>
                            <CardTitle>{{ __("Actions") }}</CardTitle>
                        </CardHeader>
                        <CardContent class="tw-space-y-2">
                            <Button
                                type="submit"
                                class="tw-w-full"
                                :disabled="!meta.valid || form.processing"
                            >
                                <Loader2
                                    v-if="form.processing"
                                    class="tw-h-4 tw-w-4 tw-mr-2 tw-animate-spin"
                                />
                                <Plus v-else class="tw-h-4 tw-w-4 tw-mr-2" />
                                {{ __("Create Product") }}
                            </Button>
                            <Button
                                type="button"
                                variant="outline"
                                class="tw-w-full"
                                @click="goBack"
                            >
                                {{ __("Cancel") }}
                            </Button>
                        </CardContent>
                    </Card>

                    <!-- Product Info -->
                    <Card>
                        <CardHeader>
                            <CardTitle>{{ __("Product Information") }}</CardTitle>
                        </CardHeader>
                        <CardContent class="tw-space-y-2 tw-text-sm">
                            <div class="tw-flex tw-justify-between">
                                <span class="tw-text-muted-foreground">{{ __("Status") }}:</span>
                                <Badge :variant="form.is_available ? 'default' : 'secondary'">
                                    {{ form.is_available ? __("Available") : __("Unavailable") }}
                                </Badge>
                            </div>
                            <div v-if="form.price" class="tw-flex tw-justify-between">
                                <span class="tw-text-muted-foreground">{{ __("Price") }}:</span>
                                <span class="tw-font-medium">${{ form.price }}</span>
                            </div>
                        </CardContent>
                    </Card>
                </div>
            </div>
        </div>
    </vee-form>
</template>

<script setup>
import { useForm } from "@inertiajs/vue3";
import { Head } from "@inertiajs/vue3";
import { Button } from "@/Components/ui/button";
import { Input } from "@/Components/ui/input";
import { Label } from "@/Components/ui/label";
import { Textarea } from "@/Components/ui/textarea";
import { Switch } from "@/Components/ui/switch";
import {
    Select,
    SelectContent,
    SelectItem,
    SelectTrigger,
    SelectValue,
} from "@/Components/ui/select";
import {
    Card,
    CardContent,
    CardDescription,
    CardHeader,
    CardTitle,
} from "@/Components/ui/card";
import { Badge } from "@/Components/ui/badge";
import { Loader2, Plus, ArrowLeft } from "lucide-vue-next";
import { useToast } from "@/Components/ui/toast/use-toast";
import * as yup from "yup";

const { toast } = useToast();

const props = defineProps({
    categories: {
        type: Array,
        default: () => [],
    },
});

const schema = yup.object({
    name: yup.string().required(__("Product name is required")),
    description: yup.string(),
    price: yup.number().min(0.01).required(__("Price is required")),
    category_id: yup.number().required(__("Category is required")),
    is_available: yup.boolean(),
});

const form = useForm({
    name: "",
    description: "",
    price: "",
    category_id: null,
    is_available: true,
    image: null,
});

const imagePreview = ref(null);

const handleImageUpload = (event) => {
    const file = event.target.files[0];
    if (file) {
        form.image = file;
        
        // Create preview
        const reader = new FileReader();
        reader.onload = (e) => {
            imagePreview.value = e.target.result;
        };
        reader.readAsDataURL(file);
    }
};

const submit = (setErrors) => {
    form.post(route("dashboard.products.store"), {
        forceFormData: true,
        onSuccess: () => {
            toast({
                title: __("Success"),
                description: __("Product created successfully"),
            });
        },
        onError: (errors) => {
            setErrors(errors);
            toast({
                title: __("Error"),
                description: __("Failed to create product"),
                variant: "destructive",
            });
        },
    });
};

const goBack = () => {
    router.visit(route("dashboard.products.index"));
};
</script>

// resources/js/Pages/Products/Create.tsx
import { FormEventHandler, useState } from 'react';
import { Head, Link, useForm } from '@inertiajs/react';
import AppLayout from '@/Layouts/AppLayout';
import { Category } from '@/types';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Checkbox } from '@/components/ui/checkbox';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { ArrowLeft, Save, Upload } from 'lucide-react';

interface Props {
    categories: Category[];
}

export default function Create({ categories }: Props) {
    const { data, setData, post, processing, errors } = useForm({
        category_id: '',
        name: '',
        description: '',
        price: '',
        image: null as File | null,
        is_available: true,
        initial_stock: '0',
        minimum_stock: '5',
    });

    const [imagePreview, setImagePreview] = useState<string | null>(null);

    const handleImageChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const file = e.target.files?.[0];
        if (file) {
            setData('image', file);
            const reader = new FileReader();
            reader.onloadend = () => {
                setImagePreview(reader.result as string);
            };
            reader.readAsDataURL(file);
        }
    };

    const submit: FormEventHandler = (e) => {
        e.preventDefault();
        post('/manager/products', {
            forceFormData: true,
        });
    };

    return (
        <AppLayout>
            <Head title="Create Product" />

            <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
                <Link href="/products">
                    <Button variant="outline" className="mb-6">
                        <ArrowLeft className="w-4 h-4 mr-2" />
                        Back to Products
                    </Button>
                </Link>

                <Card>
                    <CardHeader>
                        <CardTitle className="text-2xl">Create New Product</CardTitle>
                        <CardDescription>Add a new item to your menu</CardDescription>
                    </CardHeader>
                    <CardContent>
                        <form onSubmit={submit} className="space-y-6">
                            {/* Category */}
                            <div className="space-y-2">
                                <label className="text-sm font-medium">Category *</label>
                                <Select
                                    value={data.category_id}
                                    onValueChange={(value) => setData('category_id', value)}
                                >
                                    <SelectTrigger>
                                        <SelectValue placeholder="Select a category" />
                                    </SelectTrigger>
                                    <SelectContent>
                                        {categories.map((category) => (
                                            <SelectItem key={category.id} value={category.id.toString()}>
                                                {category.name}
                                            </SelectItem>
                                        ))}
                                    </SelectContent>
                                </Select>
                                {errors.category_id && (
                                    <p className="text-sm text-red-600">{errors.category_id}</p>
                                )}
                            </div>

                            {/* Name */}
                            <div className="space-y-2">
                                <label className="text-sm font-medium">Product Name *</label>
                                <Input
                                    type="text"
                                    value={data.name}
                                    onChange={(e) => setData('name', e.target.value)}
                                    placeholder="e.g., Margherita Pizza"
                                />
                                {errors.name && (
                                    <p className="text-sm text-red-600">{errors.name}</p>
                                )}
                            </div>

                            {/* Description */}
                            <div className="space-y-2">
                                <label className="text-sm font-medium">Description</label>
                                <textarea
                                    value={data.description}
                                    onChange={(e) => setData('description', e.target.value)}
                                    placeholder="Describe your product..."
                                    rows={4}
                                    className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
                                />
                                {errors.description && (
                                    <p className="text-sm text-red-600">{errors.description}</p>
                                )}
                            </div>

                            {/* Price */}
                            <div className="space-y-2">
                                <label className="text-sm font-medium">Price ($) *</label>
                                <Input
                                    type="number"
                                    step="0.01"
                                    min="0"
                                    value={data.price}
                                    onChange={(e) => setData('price', e.target.value)}
                                    placeholder="0.00"
                                />
                                {errors.price && (
                                    <p className="text-sm text-red-600">{errors.price}</p>
                                )}
                            </div>

                            {/* Image */}
                            <div className="space-y-2">
                                <label className="text-sm font-medium">Product Image</label>
                                <div className="space-y-4">
                                    {imagePreview && (
                                        <div className="w-full h-48 rounded-lg overflow-hidden bg-gray-100">
                                            <img
                                                src={imagePreview}
                                                alt="Preview"
                                                className="w-full h-full object-cover"
                                            />
                                        </div>
                                    )}
                                    <div className="flex items-center gap-2">
                                        <Input
                                            type="file"
                                            accept="image/*"
                                            onChange={handleImageChange}
                                            className="flex-1"
                                        />
                                        <Upload className="w-5 h-5 text-gray-400" />
                                    </div>
                                </div>
                                {errors.image && (
                                    <p className="text-sm text-red-600">{errors.image}</p>
                                )}
                            </div>

                            {/* Stock */}
                            <div className="grid grid-cols-2 gap-4">
                                <div className="space-y-2">
                                    <label className="text-sm font-medium">Initial Stock *</label>
                                    <Input
                                        type="number"
                                        min="0"
                                        value={data.initial_stock}
                                        onChange={(e) => setData('initial_stock', e.target.value)}
                                    />
                                    {errors.initial_stock && (
                                        <p className="text-sm text-red-600">{errors.initial_stock}</p>
                                    )}
                                </div>
                                <div className="space-y-2">
                                    <label className="text-sm font-medium">Minimum Stock *</label>
                                    <Input
                                        type="number"
                                        min="0"
                                        value={data.minimum_stock}
                                        onChange={(e) => setData('minimum_stock', e.target.value)}
                                    />
                                    {errors.minimum_stock && (
                                        <p className="text-sm text-red-600">{errors.minimum_stock}</p>
                                    )}
                                </div>
                            </div>

                            {/* Available */}
                            <div className="flex items-center space-x-2">
                                <Checkbox
                                    id="is_available"
                                    checked={data.is_available}
                                    onCheckedChange={(checked) => setData('is_available', checked as boolean)}
                                />
                                <label htmlFor="is_available" className="text-sm font-medium cursor-pointer">
                                    Available for purchase
                                </label>
                            </div>

                            {/* Submit */}
                            <div className="flex gap-2 pt-4">
                                <Button type="submit" disabled={processing} className="flex-1">
                                    <Save className="w-4 h-4 mr-2" />
                                    Create Product
                                </Button>
                                <Link href="/products">
                                    <Button type="button" variant="outline">
                                        Cancel
                                    </Button>
                                </Link>
                            </div>
                        </form>
                    </CardContent>
                </Card>
            </div>
        </AppLayout>
    );
}
