// temp_backup/Products/Show.vue
<template>
    <Head :title="__('Product Details')" />

    <div class="tw-space-y-6">
        <!-- Header -->
        <div class="tw-flex tw-items-center tw-justify-between">
            <div>
                <h2 class="tw-text-2xl tw-font-bold tw-tracking-tight">
                    {{ product.name }}
                </h2>
                <p class="tw-text-muted-foreground">
                    {{ __("Product details and information") }}
                </p>
            </div>
            <div class="tw-flex tw-items-center tw-gap-2">
                <Button
                    @click="editProduct"
                >
                    <Edit class="tw-w-4 tw-h-4 tw-mr-2" />
                    {{ __("Edit Product") }}
                </Button>
                <Button
                    variant="outline"
                    @click="goBack"
                >
                    <ArrowLeft class="tw-w-4 tw-h-4 tw-mr-2" />
                    {{ __("Back") }}
                </Button>
            </div>
        </div>

        <div class="tw-grid tw-grid-cols-1 lg:tw-grid-cols-3 tw-gap-6">
            <!-- Main Content -->
            <div class="tw-lg:col-span-2 tw-space-y-6">
                <!-- Product Image -->
                <Card>
                    <CardContent class="tw-p-6">
                        <div v-if="product.image_url" class="tw-w-full tw-h-64 tw-rounded-lg tw-overflow-hidden">
                            <img
                                :src="product.image_url"
                                :alt="product.name"
                                class="tw-w-full tw-h-full tw-object-cover"
                            />
                        </div>
                        <div v-else class="tw-w-full tw-h-64 tw-rounded-lg tw-border-2 tw-border-dashed tw-border-muted-foreground/25 tw-flex tw-items-center tw-justify-center">
                            <div class="tw-text-center">
                                <Package class="tw-mx-auto tw-h-12 tw-w-12 tw-text-muted-foreground" />
                                <p class="tw-text-sm tw-text-muted-foreground tw-mt-2">
                                    {{ __("No image available") }}
                                </p>
                            </div>
                        </div>
                    </CardContent>
                </Card>

                <!-- Product Information -->
                <Card>
                    <CardHeader>
                        <CardTitle>{{ __("Product Information") }}</CardTitle>
                    </CardHeader>
                    <CardContent class="tw-space-y-4">
                        <div>
                            <Label class="tw-text-sm tw-font-medium tw-text-muted-foreground">
                                {{ __("Description") }}
                            </Label>
                            <p class="tw-mt-1 tw-text-sm">
                                {{ product.description || __("No description provided") }}
                            </p>
                        </div>

                        <div class="tw-grid tw-grid-cols-1 md:tw-grid-cols-2 tw-gap-4">
                            <div>
                                <Label class="tw-text-sm tw-font-medium tw-text-muted-foreground">
                                    {{ __("Category") }}
                                </Label>
                                <p class="tw-mt-1 tw-text-sm">{{ product.category?.name }}</p>
                            </div>
                            <div>
                                <Label class="tw-text-sm tw-font-medium tw-text-muted-foreground">
                                    {{ __("Price") }}
                                </Label>
                                <p class="tw-mt-1 tw-text-sm tw-font-medium">${{ product.price }}</p>
                            </div>
                        </div>
                    </CardContent>
                </Card>

                <!-- Inventory Information -->
                <Card>
                    <CardHeader>
                        <CardTitle>{{ __("Inventory Information") }}</CardTitle>
                    </CardHeader>
                    <CardContent class="tw-space-y-4">
                        <div class="tw-grid tw-grid-cols-1 md:tw-grid-cols-3 tw-gap-4">
                            <div>
                                <Label class="tw-text-sm tw-font-medium tw-text-muted-foreground">
                                    {{ __("Current Stock") }}
                                </Label>
                                <p class="tw-mt-1 tw-text-2xl tw-font-bold">
                                    {{ product.inventory?.quantity || 0 }}
                                </p>
                            </div>
                            <div>
                                <Label class="tw-text-sm tw-font-medium tw-text-muted-foreground">
                                    {{ __("Minimum Stock") }}
                                </Label>
                                <p class="tw-mt-1 tw-text-2xl tw-font-bold">
                                    {{ product.inventory?.minimum_stock || 0 }}
                                </p>
                            </div>
                            <div>
                                <Label class="tw-text-sm tw-font-medium tw-text-muted-foreground">
                                    {{ __("Stock Status") }}
                                </Label>
                                <div class="tw-mt-1">
                                    <Badge
                                        v-if="isLowStock"
                                        variant="destructive"
                                    >
                                        {{ __("Low Stock") }}
                                    </Badge>
                                    <Badge
                                        v-else-if="isOutOfStock"
                                        variant="destructive"
                                    >
                                        {{ __("Out of Stock") }}
                                    </Badge>
                                    <Badge
                                        v-else
                                        variant="default"
                                    >
                                        {{ __("In Stock") }}
                                    </Badge>
                                </div>
                            </div>
                        </div>

                        <div v-if="product.inventory?.last_restocked_at">
                            <Label class="tw-text-sm tw-font-medium tw-text-muted-foreground">
                                {{ __("Last Restocked") }}
                            </Label>
                            <p class="tw-mt-1 tw-text-sm">
                                {{ new Date(product.inventory.last_restocked_at).toLocaleDateString() }}
                            </p>
                        </div>
                    </CardContent>
                </Card>

                <!-- Recent Orders -->
                <Card>
                    <CardHeader>
                        <CardTitle>{{ __("Recent Orders") }}</CardTitle>
                        <CardDescription>
                            {{ __("Last 10 orders containing this product") }}
                        </CardDescription>
                    </CardHeader>
                    <CardContent>
                        <div v-if="product.order_items && product.order_items.length > 0" class="tw-space-y-2">
                            <div
                                v-for="orderItem in product.order_items"
                                :key="orderItem.id"
                                class="tw-flex tw-items-center tw-justify-between tw-py-2 tw-px-3 tw-rounded-md tw-bg-muted/50"
                            >
                                <div>
                                    <p class="tw-text-sm tw-font-medium">
                                        {{ __("Order") }} #{{ orderItem.order?.order_number }}
                                    </p>
                                    <p class="tw-text-xs tw-text-muted-foreground">
                                        {{ new Date(orderItem.order?.created_at).toLocaleDateString() }}
                                    </p>
                                </div>
                                <div class="tw-text-right">
                                    <p class="tw-text-sm tw-font-medium">
                                        {{ orderItem.quantity }} {{ __("items") }}
                                    </p>
                                    <p class="tw-text-xs tw-text-muted-foreground">
                                        ${{ orderItem.subtotal }}
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div v-else class="tw-text-center tw-py-6">
                            <ShoppingCart class="tw-mx-auto tw-h-8 tw-w-8 tw-text-muted-foreground" />
                            <p class="tw-text-sm tw-text-muted-foreground tw-mt-2">
                                {{ __("No orders found") }}
                            </p>
                        </div>
                    </CardContent>
                </Card>
            </div>

            <!-- Sidebar -->
            <div class="tw-space-y-6">
                <!-- Product Status -->
                <Card>
                    <CardHeader>
                        <CardTitle>{{ __("Product Status") }}</CardTitle>
                    </CardHeader>
                    <CardContent class="tw-space-y-4">
                        <div class="tw-flex tw-items-center tw-justify-between">
                            <span class="tw-text-sm tw-font-medium">{{ __("Availability") }}</span>
                            <Badge :variant="product.is_available ? 'default' : 'secondary'">
                                {{ product.is_available ? __("Available") : __("Unavailable") }}
                            </Badge>
                        </div>
                        
                        <div class="tw-flex tw-items-center tw-justify-between">
                            <span class="tw-text-sm tw-font-medium">{{ __("Stock Level") }}</span>
                            <Badge
                                :variant="getStockBadgeVariant()"
                            >
                                {{ getStockStatus() }}
                            </Badge>
                        </div>
                    </CardContent>
                </Card>

                <!-- Quick Actions -->
                <Card>
                    <CardHeader>
                        <CardTitle>{{ __("Quick Actions") }}</CardTitle>
                    </CardHeader>
                    <CardContent class="tw-space-y-2">
                        <Button
                            variant="outline"
                            class="tw-w-full tw-justify-start"
                            @click="toggleAvailability"
                        >
                            <ToggleLeft class="tw-w-4 tw-h-4 tw-mr-2" />
                            {{ product.is_available ? __("Disable Product") : __("Enable Product") }}
                        </Button>
                        
                        <Button
                            variant="outline"
                            class="tw-w-full tw-justify-start"
                            @click="manageInventory"
                        >
                            <Package class="tw-w-4 tw-h-4 tw-mr-2" />
                            {{ __("Manage Inventory") }}
                        </Button>
                    </CardContent>
                </Card>

                <!-- Product Statistics -->
                <Card>
                    <CardHeader>
                        <CardTitle>{{ __("Statistics") }}</CardTitle>
                    </CardHeader>
                    <CardContent class="tw-space-y-4 tw-text-sm">
                        <div class="tw-flex tw-justify-between">
                            <span class="tw-text-muted-foreground">{{ __("Created") }}:</span>
                            <span>{{ new Date(product.created_at).toLocaleDateString() }}</span>
                        </div>
                        <div class="tw-flex tw-justify-between">
                            <span class="tw-text-muted-foreground">{{ __("Last Updated") }}:</span>
                            <span>{{ new Date(product.updated_at).toLocaleDateString() }}</span>
                        </div>
                        <div class="tw-flex tw-justify-between">
                            <span class="tw-text-muted-foreground">{{ __("Total Orders") }}:</span>
                            <span>{{ product.order_items?.length || 0 }}</span>
                        </div>
                        <div class="tw-flex tw-justify-between">
                            <span class="tw-text-muted-foreground">{{ __("Total Sold") }}:</span>
                            <span>{{ totalQuantitySold }}</span>
                        </div>
                    </CardContent>
                </Card>
            </div>
        </div>
    </div>
</template>

<script setup>
import { computed } from "vue";
import { router } from "@inertiajs/vue3";
import { Head } from "@inertiajs/vue3";
import { Button } from "@/Components/ui/button";
import { Label } from "@/Components/ui/label";
import {
    Card,
    CardContent,
    CardDescription,
    CardHeader,
    CardTitle,
} from "@/Components/ui/card";
import { Badge } from "@/Components/ui/badge";
import {
    Edit,
    ArrowLeft,
    Package,
    ShoppingCart,
    ToggleLeft,
} from "lucide-vue-next";
import { useToast } from "@/Components/ui/toast/use-toast";

const { toast } = useToast();

const props = defineProps({
    product: {
        type: Object,
        required: true,
    },
});

// Computed properties
const isLowStock = computed(() => {
    return props.product.inventory?.quantity <= props.product.inventory?.minimum_stock && props.product.inventory?.quantity > 0;
});

const isOutOfStock = computed(() => {
    return props.product.inventory?.quantity === 0;
});

const totalQuantitySold = computed(() => {
    return props.product.order_items?.reduce((total, item) => total + item.quantity, 0) || 0;
});

// Methods
const getStockStatus = () => {
    if (isOutOfStock.value) return __("Out of Stock");
    if (isLowStock.value) return __("Low Stock");
    return __("In Stock");
};

const getStockBadgeVariant = () => {
    if (isOutOfStock.value) return "destructive";
    if (isLowStock.value) return "destructive";
    return "default";
};

const editProduct = () => {
    router.visit(route("dashboard.products.edit", props.product.id));
};

const toggleAvailability = async () => {
    try {
        await router.put(
            route("dashboard.products.update", props.product.id),
            {
                is_available: !props.product.is_available,
            },
            {
                preserveState: true,
                onSuccess: () => {
                    toast({
                        title: __("Success"),
                        description: props.product.is_available
                            ? __("Product disabled successfully")
                            : __("Product enabled successfully"),
                    });
                },
                onError: () => {
                    toast({
                        title: __("Error"),
                        description: __("Failed to update product status"),
                        variant: "destructive",
                    });
                },
            }
        );
    } catch (error) {
        console.error("Error toggling availability:", error);
    }
};

const manageInventory = () => {
    router.visit(route("dashboard.inventory.index", { search: props.product.name }));
};

const goBack = () => {
    router.visit(route("dashboard.products.index"));
};
</script>

// resources/js/Pages/Products/Show.tsx
import { useState } from 'react';
import { Head, Link, router } from '@inertiajs/react';
import AppLayout from '@/Layouts/AppLayout';
import { Product, User } from '@/types';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { Separator } from '@/components/ui/separator';
import { ShoppingCart, ArrowLeft, Package, Edit, Trash2, Minus, Plus } from 'lucide-react';
import { formatPrice } from '@/lib/utils';

interface Props {
    product: Product;
    auth?: {
        user?: User;
    };
}

export default function Show({ product, auth }: Props) {
    const [quantity, setQuantity] = useState(1);

    const handleAddToCart = () => {
        router.post('/cart/add', {
            product_id: product.id,
            quantity: quantity,
        });
    };

    const decrementQuantity = () => {
        if (quantity > 1) setQuantity(quantity - 1);
    };

    const incrementQuantity = () => {
        const maxStock = product.inventory?.quantity || 0;
        if (quantity < maxStock) setQuantity(quantity + 1);
    };

    const handleDelete = () => {
        if (confirm('Are you sure you want to delete this product?')) {
            router.delete(`/manager/products/${product.id}`);
        }
    };

    const isAvailable = product.is_available && product.inventory && product.inventory.quantity > 0;

    return (
        <AppLayout>
            <Head title={product.name} />

            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
                {/* Back Button */}
                <Link href="/products">
                    <Button variant="outline" className="mb-6">
                        <ArrowLeft className="w-4 h-4 mr-2" />
                        Back to Menu
                    </Button>
                </Link>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                    {/* Product Image */}
                    <div className="aspect-square bg-gray-200 rounded-lg overflow-hidden">
                        {product.image ? (
                            <img
                                src={`/storage/${product.image}`}
                                alt={product.name}
                                className="w-full h-full object-cover"
                            />
                        ) : (
                            <div className="w-full h-full flex items-center justify-center">
                                <Package className="w-32 h-32 text-gray-400" />
                            </div>
                        )}
                    </div>

                    {/* Product Details */}
                    <div className="space-y-6">
                        <div>
                            <div className="flex items-start justify-between mb-2">
                                <div>
                                    <h1 className="text-3xl font-bold text-gray-900">{product.name}</h1>
                                    {product.category && (
                                        <p className="text-sm text-gray-500 mt-1">{product.category.name}</p>
                                    )}
                                </div>
                                <Badge variant={isAvailable ? "default" : "destructive"}>
                                    {isAvailable ? 'Available' : 'Out of Stock'}
                                </Badge>
                            </div>

                            <p className="text-3xl font-bold text-indigo-600 mt-4">
                                {formatPrice(product.price)}
                            </p>
                        </div>

                        <Separator />

                        {/* Description */}
                        {product.description && (
                            <div>
                                <h3 className="text-lg font-semibold mb-2">Description</h3>
                                <p className="text-gray-700">{product.description}</p>
                            </div>
                        )}

                        {/* Stock Information */}
                        {product.inventory && (
                            <div>
                                <h3 className="text-lg font-semibold mb-2">Availability</h3>
                                <div className="flex items-center gap-2">
                                    <Package className="w-5 h-5 text-gray-500" />
                                    <span className="text-gray-700">
                                        {product.inventory.quantity} items in stock
                                    </span>
                                </div>
                            </div>
                        )}

                        <Separator />

                        {/* Add to Cart */}
                        {isAvailable && !auth?.user?.role?.match(/manager|kitchen|supplier/) && (
                            <Card>
                                <CardContent className="pt-6">
                                    <div className="space-y-4">
                                        <div>
                                            <label className="text-sm font-medium mb-2 block">Quantity</label>
                                            <div className="flex items-center gap-2">
                                                <Button
                                                    variant="outline"
                                                    size="icon"
                                                    onClick={decrementQuantity}
                                                    disabled={quantity <= 1}
                                                >
                                                    <Minus className="w-4 h-4" />
                                                </Button>
                                                <Input
                                                    type="number"
                                                    value={quantity}
                                                    onChange={(e) => {
                                                        const val = parseInt(e.target.value) || 1;
                                                        const max = product.inventory?.quantity || 1;
                                                        setQuantity(Math.min(Math.max(1, val), max));
                                                    }}
                                                    className="w-20 text-center"
                                                    min={1}
                                                    max={product.inventory?.quantity || 1}
                                                />
                                                <Button
                                                    variant="outline"
                                                    size="icon"
                                                    onClick={incrementQuantity}
                                                    disabled={quantity >= (product.inventory?.quantity || 0)}
                                                >
                                                    <Plus className="w-4 h-4" />
                                                </Button>
                                            </div>
                                        </div>
                                        <Button className="w-full" onClick={handleAddToCart}>
                                            <ShoppingCart className="w-4 h-4 mr-2" />
                                            Add to Cart
                                        </Button>
                                    </div>
                                </CardContent>
                            </Card>
                        )}

                        {/* Manager Actions */}
                        {auth?.user?.role === 'manager' && (
                            <div className="flex gap-2">
                                <Link href={`/manager/products/${product.id}/edit`} className="flex-1">
                                    <Button variant="outline" className="w-full">
                                        <Edit className="w-4 h-4 mr-2" />
                                        Edit Product
                                    </Button>
                                </Link>
                                <Button variant="destructive" onClick={handleDelete}>
                                    <Trash2 className="w-4 h-4 mr-2" />
                                    Delete
                                </Button>
                            </div>
                        )}
                    </div>
                </div>
            </div>
        </AppLayout>
    );
}
