// resources/js/Pages/Products/Edit.tsx
import { FormEventHandler, useState } from 'react';
import { Head, Link, useForm } from '@inertiajs/react';
import AppLayout from '@/Layouts/AppLayout';
import { Category, Product } from '@/types';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Checkbox } from '@/components/ui/checkbox';
import { ArrowLeft, Save, Upload } from 'lucide-react';

interface Props {
    product: Product;
    categories: Category[];
}

export default function Edit({ product, categories }: Props) {
    const { data, setData, post, processing, errors } = useForm({
        category_id: product.category_id.toString(),
        name: product.name,
        description: product.description || '',
        price: product.price.toString(),
        image: null as File | null,
        is_available: product.is_available,
        _method: 'PUT',
    });

    const [imagePreview, setImagePreview] = useState<string | null>(
        product.image ? `/storage/${product.image}` : null
    );

    const handleImageChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const file = e.target.files?.[0];
        if (file) {
            setData('image', file);
            const reader = new FileReader();
            reader.onloadend = () => {
                setImagePreview(reader.result as string);
            };
            reader.readAsDataURL(file);
        }
    };

    const submit: FormEventHandler = (e) => {
        e.preventDefault();
        post(`/manager/products/${product.id}`, {
            forceFormData: true,
        });
    };

    return (
        <AppLayout>
            <Head title={`Edit ${product.name}`} />

            <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
                <Link href="/products">
                    <Button variant="outline" className="mb-6">
                        <ArrowLeft className="w-4 h-4 mr-2" />
                        Back to Products
                    </Button>
                </Link>

                <Card>
                    <CardHeader>
                        <CardTitle className="text-2xl">Edit Product</CardTitle>
                        <CardDescription>Update product information</CardDescription>
                    </CardHeader>
                    <CardContent>
                        <form onSubmit={submit} className="space-y-6">
                            {/* Category */}
                            <div className="space-y-2">
                                <label className="text-sm font-medium">Category *</label>
                                <Select
                                    value={data.category_id}
                                    onValueChange={(value) => setData('category_id', value)}
                                >
                                    <SelectTrigger>
                                        <SelectValue />
                                    </SelectTrigger>
                                    <SelectContent>
                                        {categories.map((category) => (
                                            <SelectItem key={category.id} value={category.id.toString()}>
                                                {category.name}
                                            </SelectItem>
                                        ))}
                                    </SelectContent>
                                </Select>
                                {errors.category_id && (
                                    <p className="text-sm text-red-600">{errors.category_id}</p>
                                )}
                            </div>

                            {/* Name */}
                            <div className="space-y-2">
                                <label className="text-sm font-medium">Product Name *</label>
                                <Input
                                    type="text"
                                    value={data.name}
                                    onChange={(e) => setData('name', e.target.value)}
                                />
                                {errors.name && (
                                    <p className="text-sm text-red-600">{errors.name}</p>
                                )}
                            </div>

                            {/* Description */}
                            <div className="space-y-2">
                                <label className="text-sm font-medium">Description</label>
                                <textarea
                                    value={data.description}
                                    onChange={(e) => setData('description', e.target.value)}
                                    rows={4}
                                    className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
                                />
                                {errors.description && (
                                    <p className="text-sm text-red-600">{errors.description}</p>
                                )}
                            </div>

                            {/* Price */}
                            <div className="space-y-2">
                                <label className="text-sm font-medium">Price ($) *</label>
                                <Input
                                    type="number"
                                    step="0.01"
                                    min="0"
                                    value={data.price}
                                    onChange={(e) => setData('price', e.target.value)}
                                />
                                {errors.price && (
                                    <p className="text-sm text-red-600">{errors.price}</p>
                                )}
                            </div>

                            {/* Image */}
                            <div className="space-y-2">
                                <label className="text-sm font-medium">Product Image</label>
                                <div className="space-y-4">
                                    {imagePreview && (
                                        <div className="w-full h-48 rounded-lg overflow-hidden bg-gray-100">
                                            <img
                                                src={imagePreview}
                                                alt="Preview"
                                                className="w-full h-full object-cover"
                                            />
                                        </div>
                                    )}
                                    <div className="flex items-center gap-2">
                                        <Input
                                            type="file"
                                            accept="image/*"
                                            onChange={handleImageChange}
                                            className="flex-1"
                                        />
                                        <Upload className="w-5 h-5 text-gray-400" />
                                    </div>
                                    <p className="text-xs text-gray-500">
                                        Leave empty to keep the current image
                                    </p>
                                </div>
                                {errors.image && (
                                    <p className="text-sm text-red-600">{errors.image}</p>
                                )}
                            </div>

                            {/* Available */}
                            <div className="flex items-center space-x-2">
                                <Checkbox
                                    id="is_available"
                                    checked={data.is_available}
                                    onCheckedChange={(checked) => setData('is_available', checked as boolean)}
                                />
                                <label htmlFor="is_available" className="text-sm font-medium cursor-pointer">
                                    Available for purchase
                                </label>
                            </div>

                            {/* Submit */}
                            <div className="flex gap-2 pt-4">
                                <Button type="submit" disabled={processing} className="flex-1">
                                    <Save className="w-4 h-4 mr-2" />
                                    Update Product
                                </Button>
                                <Link href="/products">
                                    <Button type="button" variant="outline">
                                        Cancel
                                    </Button>
                                </Link>
                            </div>
                        </form>
                    </CardContent>
                </Card>
            </div>
        </AppLayout>
    );
}

// resources/js/Pages/Dashboard/Categories/Edit.vue
<template>
    <Head :title="__('Edit Category')" />

    <vee-form
        :validation-schema="schema"
        @submit="submit"
        v-slot="{ meta, setErrors }"
        :initial-values="form"
    >
        <div class="tw-space-y-6">
            <!-- Header -->
            <div class="tw-flex tw-items-center tw-justify-between">
                <div>
                    <h2 class="tw-text-2xl tw-font-bold tw-tracking-tight">
                        {{ __("Edit Category") }}
                    </h2>
                    <p class="tw-text-muted-foreground">
                        {{ __("Update category information") }}
                    </p>
                </div>
                <Button
                    variant="outline"
                    @click="goBack"
                >
                    <ArrowLeft class="tw-w-4 tw-h-4 tw-mr-2" />
                    {{ __("Back") }}
                </Button>
            </div>

            <!-- Form -->
            <div class="tw-grid tw-grid-cols-1 lg:tw-grid-cols-3 tw-gap-6">
                <!-- Main Form -->
                <div class="tw-lg:col-span-2 tw-space-y-6">
                    <!-- Basic Information -->
                    <Card>
                        <CardHeader>
                            <CardTitle>{{ __("Category Information") }}</CardTitle>
                            <CardDescription>
                                {{ __("Update the basic details of the category") }}
                            </CardDescription>
                        </CardHeader>
                        <CardContent class="tw-space-y-4">
                            <vee-field
                                name="name"
                                v-slot="{ field, errors }"
                            >
                                <div class="tw-space-y-2">
                                    <Label for="name">
                                        {{ __("Category Name") }}
                                        <span class="tw-text-destructive">*</span>
                                    </Label>
                                    <Input
                                        id="name"
                                        v-bind="field"
                                        :model-value="form.name"
                                        @update:model-value="(val) => form.name = val"
                                        :class="{ 'tw-border-destructive': errors.length }"
                                        :placeholder="__('Enter category name')"
                                    />
                                    <p v-if="errors.length" class="tw-text-sm tw-text-destructive">
                                        {{ errors[0] }}
                                    </p>
                                </div>
                            </vee-field>

                            <vee-field
                                name="description"
                                v-slot="{ field, errors }"
                            >
                                <div class="tw-space-y-2">
                                    <Label for="description">{{ __("Description") }}</Label>
                                    <Textarea
                                        id="description"
                                        v-bind="field"
                                        :model-value="form.description"
                                        @update:model-value="(val) => form.description = val"
                                        rows="4"
                                        :class="{ 'tw-border-destructive': errors.length }"
                                        :placeholder="__('Enter category description')"
                                    />
                                    <p v-if="errors.length" class="tw-text-sm tw-text-destructive">
                                        {{ errors[0] }}
                                    </p>
                                </div>
                            </vee-field>
                        </CardContent>
                    </Card>

                    <!-- Products in Category -->
                    <Card>
                        <CardHeader>
                            <CardTitle>{{ __("Products in Category") }}</CardTitle>
                            <CardDescription>
                                {{ __("Products currently assigned to this category") }}
                            </CardDescription>
                        </CardHeader>
                        <CardContent>
                            <div v-if="category.products && category.products.length > 0" class="tw-space-y-2">
                                <div
                                    v-for="product in category.products"
                                    :key="product.id"
                                    class="tw-flex tw-items-center tw-justify-between tw-py-2 tw-px-3 tw-rounded-md tw-bg-muted/50"
                                >
                                    <div class="tw-flex tw-items-center tw-gap-3">
                                        <img
                                            v-if="product.image"
                                            :src="product.image_url"
                                            :alt="product.name"
                                            class="tw-w-8 tw-h-8 tw-rounded-md tw-object-cover"
                                        />
                                        <div>
                                            <p class="tw-text-sm tw-font-medium">{{ product.name }}</p>
                                            <p class="tw-text-xs tw-text-muted-foreground">
                                                ${{ product.price }}
                                            </p>
                                        </div>
                                    </div>
                                    <Badge :variant="product.is_available ? 'default' : 'secondary'">
                                        {{ product.is_available ? __("Available") : __("Unavailable") }}
                                    </Badge>
                                </div>
                            </div>
                            <div v-else class="tw-text-center tw-py-6">
                                <Package class="tw-mx-auto tw-h-8 tw-w-8 tw-text-muted-foreground" />
                                <p class="tw-text-sm tw-text-muted-foreground tw-mt-2">
                                    {{ __("No products in this category") }}
                                </p>
                            </div>
                        </CardContent>
                    </Card>
                </div>

                <!-- Sidebar -->
                <div class="tw-space-y-6">
                    <!-- Actions -->
                    <Card>
                        <CardHeader>
                            <CardTitle>{{ __("Actions") }}</CardTitle>
                        </CardHeader>
                        <CardContent class="tw-space-y-2">
                            <Button
                                type="submit"
                                class="tw-w-full"
                                :disabled="!meta.valid || form.processing"
                            >
                                <Loader2
                                    v-if="form.processing"
                                    class="tw-h-4 tw-w-4 tw-mr-2 tw-animate-spin"
                                />
                                <Save v-else class="tw-h-4 tw-w-4 tw-mr-2" />
                                {{ __("Update Category") }}
                            </Button>
                            <Button
                                type="button"
                                variant="outline"
                                class="tw-w-full"
                                @click="goBack"
                            >
                                {{ __("Cancel") }}
                            </Button>
                        </CardContent>
                    </Card>

                    <!-- Category Info -->
                    <Card>
                        <CardHeader>
                            <CardTitle>{{ __("Category Information") }}</CardTitle>
                        </CardHeader>
                        <CardContent class="tw-space-y-2 tw-text-sm">
                            <div class="tw-flex tw-justify-between">
                                <span class="tw-text-muted-foreground">{{ __("Products Count") }}:</span>
                                <span>{{ category.products?.length || 0 }}</span>
                            </div>
                            <div class="tw-flex tw-justify-between">
                                <span class="tw-text-muted-foreground">{{ __("Created") }}:</span>
                                <span>{{ new Date(category.created_at).toLocaleDateString() }}</span>
                            </div>
                            <div class="tw-flex tw-justify-between">
                                <span class="tw-text-muted-foreground">{{ __("Last Updated") }}:</span>
                                <span>{{ new Date(category.updated_at).toLocaleDateString() }}</span>
                            </div>
                        </CardContent>
                    </Card>

                    <!-- Danger Zone -->
                    <Card v-if="!category.products || category.products.length === 0" class="tw-border-destructive">
                        <CardHeader>
                            <CardTitle class="tw-text-destructive">{{ __("Danger Zone") }}</CardTitle>
                        </CardHeader>
                        <CardContent>
                            <Button
                                variant="destructive"
                                class="tw-w-full"
                                @click="deleteCategory"
                                :disabled="form.processing || (category.products && category.products.length > 0)"
                            >
                                <Trash2 class="tw-w-4 tw-h-4 tw-mr-2" />
                                {{ __("Delete Category") }}
                            </Button>
                            <p class="tw-text-xs tw-text-muted-foreground tw-mt-2">
                                {{ __("This action cannot be undone") }}
                            </p>
                        </CardContent>
                    </Card>

                    <!-- Warning -->
                    <Card v-else class="tw-border-yellow-200 tw-bg-yellow-50">
                        <CardHeader>
                            <CardTitle class="tw-text-yellow-800">{{ __("Cannot Delete") }}</CardTitle>
                        </CardHeader>
                        <CardContent>
                            <p class="tw-text-sm tw-text-yellow-700">
                                {{ __("This category has associated products and cannot be deleted") }}
                            </p>
                        </CardContent>
                    </Card>
                </div>
            </div>
        </div>
    </vee-form>
</template>

<script setup>
import { useForm } from "@inertiajs/vue3";
import { Head } from "@inertiajs/vue3";
import { Button } from "@/Components/ui/button";
import { Input } from "@/Components/ui/input";
import { Label } from "@/Components/ui/label";
import { Textarea } from "@/Components/ui/textarea";
import {
    Card,
    CardContent,
    CardDescription,
    CardHeader,
    CardTitle,
} from "@/Components/ui/card";
import { Badge } from "@/Components/ui/badge";
import { Loader2, Save, ArrowLeft, Trash2, Package } from "lucide-vue-next";
import { useToast } from "@/Components/ui/toast/use-toast";
import * as yup from "yup";

const { toast } = useToast();

const props = defineProps({
    category: {
        type: Object,
        required: true,
    },
});

const schema = yup.object({
    name: yup.string().required(__("Category name is required")),
    description: yup.string(),
});

const form = useForm({
    name: props.category.name,
    description: props.category.description,
});

const submit = (setErrors) => {
    form.put(route("dashboard.categories.update", props.category.id), {
        onSuccess: () => {
            toast({
                title: __("Success"),
                description: __("Category updated successfully"),
            });
        },
        onError: (errors) => {
            setErrors(errors);
            toast({
                title: __("Error"),
                description: __("Failed to update category"),
                variant: "destructive",
            });
        },
    });
};

const deleteCategory = () => {
    if (props.category.products && props.category.products.length > 0) {
        toast({
            title: __("Cannot Delete"),
            description: __("Category has associated products and cannot be deleted"),
            variant: "destructive",
        });
        return;
    }

    if (!confirm(__("Are you sure you want to delete this category? This action cannot be undone."))) return;

    router.delete(route("dashboard.categories.destroy", props.category.id), {
        onSuccess: () => {
            toast({
                title: __("Success"),
                description: __("Category deleted successfully"),
            });
        },
        onError: () => {
            toast({
                title: __("Error"),
                description: __("Failed to delete category"),
                variant: "destructive",
            });
        },
    });
};

const goBack = () => {
    router.visit(route("dashboard.categories.index"));
};
</script>
