// resources/js/Pages/Inventory/Index.tsx
import { useState } from 'react';
import { Head, Link, router, useForm } from '@inertiajs/react';
import AppLayout from '@/Layouts/AppLayout';
import { Inventory, Product, PaginatedData } from '@/types';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { Checkbox } from '@/components/ui/checkbox';
import { AlertTriangle, Package, Plus, Search } from 'lucide-react';

interface InventoryWithProduct extends Inventory {
    product: Product & {
        category: { name: string };
    };
}

interface Props {
    inventory: PaginatedData<InventoryWithProduct>;
    lowStockCount: number;
    filters: {
        search?: string;
        low_stock?: string;
    };
}

export default function Index({ inventory, lowStockCount, filters }: Props) {
    const [search, setSearch] = useState(filters.search || '');
    const [lowStockOnly, setLowStockOnly] = useState(!!filters.low_stock);

    const handleFilter = () => {
        router.get('/manager/inventory', {
            search: search || undefined,
            low_stock: lowStockOnly ? '1' : undefined,
        }, {
            preserveState: true,
            preserveScroll: true,
        });
    };

    const restockForm = useForm<{ quantity: number }>({
        quantity: 10,
    });

    const handleRestock = (inventoryId: number) => {
        restockForm.post(`/manager/inventory/${inventoryId}/restock`, {
            preserveScroll: true,
            onSuccess: () => {
                restockForm.reset();
            },
        });
    };

    return (
        <AppLayout>
            <Head title="Inventory Management" />

            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                {/* Header */}
                <div className="mb-6 flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
                    <div>
                        <h1 className="text-3xl font-bold text-gray-900">Inventory Management</h1>
                        <p className="text-gray-600">Manage product stock levels</p>
                    </div>
                    <div className="flex gap-3">
                        <Link href="/manager/inventory/alerts">
                            <Button variant="outline">
                                <AlertTriangle className="w-4 h-4 mr-2" />
                                Low Stock Alerts ({lowStockCount})
                            </Button>
                        </Link>
                        <Link href="/manager/inventory-orders/create">
                            <Button>
                                <Plus className="w-4 h-4 mr-2" />
                                Create Restock Order
                            </Button>
                        </Link>
                    </div>
                </div>

                {/* Filters */}
                <Card className="mb-6">
                    <CardContent className="pt-6">
                        <div className="flex flex-col sm:flex-row gap-4">
                            <div className="flex-1 relative">
                                <Search className="absolute left-3 top-3 h-4 w-4 text-gray-400" />
                                <Input
                                    type="text"
                                    placeholder="Search products..."
                                    value={search}
                                    onChange={(e) => setSearch(e.target.value)}
                                    onKeyDown={(e) => e.key === 'Enter' && handleFilter()}
                                    className="pl-10"
                                />
                            </div>
                            <div className="flex items-center space-x-2">
                                <Checkbox
                                    id="low-stock"
                                    checked={lowStockOnly}
                                    onCheckedChange={(checked) => setLowStockOnly(checked as boolean)}
                                />
                                <label htmlFor="low-stock" className="text-sm text-gray-700 cursor-pointer">
                                    Low Stock Only
                                </label>
                            </div>
                            <Button onClick={handleFilter}>Filter</Button>
                        </div>
                    </CardContent>
                </Card>

                {/* Inventory Table */}
                <Card>
                    <CardContent className="p-0">
                        <div className="overflow-x-auto">
                            <table className="min-w-full divide-y divide-gray-200">
                                <thead className="bg-gray-50">
                                    <tr>
                                        <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                            Product
                                        </th>
                                        <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                            Category
                                        </th>
                                        <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                            Quantity
                                        </th>
                                        <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                            Min Stock
                                        </th>
                                        <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                            Status
                                        </th>
                                        <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                            Last Restocked
                                        </th>
                                        <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                            Actions
                                        </th>
                                    </tr>
                                </thead>
                                <tbody className="bg-white divide-y divide-gray-200">
                                    {inventory.data.map((item) => {
                                        const isLowStock = item.quantity <= item.minimum_stock;
                                        const isOutOfStock = item.quantity === 0;

                                        return (
                                            <tr
                                                key={item.id}
                                                className={isLowStock ? 'bg-yellow-50' : ''}
                                            >
                                                <td className="px-6 py-4 whitespace-nowrap">
                                                    <div className="flex items-center">
                                                        <Package className="h-5 w-5 text-gray-400 mr-3" />
                                                        <div className="font-medium text-gray-900">
                                                            {item.product.name}
                                                        </div>
                                                    </div>
                                                </td>
                                                <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-600">
                                                    {item.product.category.name}
                                                </td>
                                                <td className="px-6 py-4 whitespace-nowrap">
                                                    <span className={`text-lg font-semibold ${
                                                        isOutOfStock
                                                            ? 'text-red-600'
                                                            : isLowStock
                                                            ? 'text-yellow-600'
                                                            : 'text-green-600'
                                                    }`}>
                                                        {item.quantity}
                                                    </span>
                                                </td>
                                                <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-600">
                                                    {item.minimum_stock}
                                                </td>
                                                <td className="px-6 py-4 whitespace-nowrap">
                                                    {isOutOfStock ? (
                                                        <Badge variant="destructive">Out of Stock</Badge>
                                                    ) : isLowStock ? (
                                                        <Badge variant="secondary" className="bg-yellow-100 text-yellow-800">
                                                            Low Stock
                                                        </Badge>
                                                    ) : (
                                                        <Badge variant="default" className="bg-green-100 text-green-800">
                                                            In Stock
                                                        </Badge>
                                                    )}
                                                </td>
                                                <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-600">
                                                    {item.last_restocked_at
                                                        ? new Date(item.last_restocked_at).toLocaleDateString()
                                                        : 'Never'}
                                                </td>
                                                <td className="px-6 py-4 whitespace-nowrap">
                                                    <form
                                                        onSubmit={(e) => {
                                                            e.preventDefault();
                                                            handleRestock(item.id);
                                                        }}
                                                        className="flex items-center gap-2"
                                                    >
                                                        <Input
                                                            type="number"
                                                            min="1"
                                                            defaultValue="10"
                                                            className="w-20"
                                                            onChange={(e) => restockForm.setData('quantity', parseInt(e.target.value))}
                                                        />
                                                        <Button type="submit" size="sm">
                                                            Restock
                                                        </Button>
                                                    </form>
                                                </td>
                                            </tr>
                                        );
                                    })}
                                </tbody>
                            </table>
                        </div>

                        {inventory.data.length === 0 && (
                            <div className="text-center py-12 text-gray-500">
                                No inventory records found.
                            </div>
                        )}
                    </CardContent>
                </Card>

                {/* Pagination */}
                {inventory.meta.last_page > 1 && (
                    <div className="mt-6 flex justify-center gap-2">
                        {inventory.links.prev && (
                            <Link href={inventory.links.prev}>
                                <Button variant="outline">Previous</Button>
                            </Link>
                        )}
                        <span className="flex items-center px-4 text-sm text-gray-700">
                            Page {inventory.meta.current_page} of {inventory.meta.last_page}
                        </span>
                        {inventory.links.next && (
                            <Link href={inventory.links.next}>
                                <Button variant="outline">Next</Button>
                            </Link>
                        )}
                    </div>
                )}
            </div>
        </AppLayout>
    );
}

// resources/js/Pages/Inventory/Index.vue
<template>
    <AppLayout>

        <Head title="Inventory Management" />

        <!-- Header -->
        <div class="d-flex flex-column flex-sm-row justify-space-between align-start align-sm-center mb-6">
            <div>
                <h1 class="text-h3 font-weight-bold text-grey-darken-3 mb-2">
                    Inventory Management
                </h1>
                <p class="text-grey-darken-1">
                    Manage product stock levels
                </p>
            </div>
            <div class="d-flex gap-3 mt-4 mt-sm-0">
                <v-btn variant="outlined" :to="{ name: 'inventory.alerts' }">
                    <v-icon left>mdi-alert</v-icon>
                    Low Stock Alerts ({{ lowStockCount }})
                </v-btn>
                <v-btn color="primary" :to="{ name: 'inventory-orders.create' }">
                    <v-icon left>mdi-plus</v-icon>
                    Create Restock Order
                </v-btn>
            </div>
        </div>

        <!-- Filters -->
        <v-card class="mb-6" elevation="2">
            <v-card-text class="pt-6">
                <v-row>
                    <v-col cols="12" md="8">
                        <v-text-field v-model="search" prepend-inner-icon="mdi-magnify" label="Search products..."
                            variant="outlined" clearable @keyup.enter="handleFilter" />
                    </v-col>
                    <v-col cols="12" md="2" class="d-flex align-center">
                        <v-checkbox v-model="lowStockOnly" label="Low Stock Only" hide-details />
                    </v-col>
                    <v-col cols="12" md="2" class="d-flex align-center">
                        <v-btn color="primary" block @click="handleFilter">
                            Filter
                        </v-btn>
                    </v-col>
                </v-row>
            </v-card-text>
        </v-card>

        <!-- Inventory Table -->
        <v-card elevation="2">
            <v-data-table :headers="headers" :items="inventory.data" :loading="loading" class="elevation-0"
                no-data-text="No inventory records found">
                <!-- Product Column -->
                <template v-slot:item="{ item }">
                    <tr :class="{ 'bg-yellow-lighten-5': isLowStock(item) }">
                        <td>
                            <div class="d-flex align-center">
                                <v-icon color="grey" class="mr-3">mdi-package-variant</v-icon>
                                <div class="font-weight-medium">
                                    {{ item.product.name }}
                                </div>
                            </div>
                        </td>
                        <td>{{ item.product.category.name }}</td>
                        <td>
                            <span :class="getQuantityColor(item)" class="text-h6 font-weight-bold">
                                {{ item.quantity }}
                            </span>
                        </td>
                        <td>{{ item.minimum_stock }}</td>
                        <td>
                            <v-chip :color="getStatusColor(item)" size="small">
                                {{ getStatusText(item) }}
                            </v-chip>
                        </td>
                        <td>{{ formatDate(item.last_restocked_at) }}</td>
                        <td>
                            <div class="d-flex align-center gap-2">
                                <v-text-field v-model.number="restockQuantities[item.id]" type="number" min="1"
                                    variant="outlined" density="compact" hide-details style="width: 80px;" />
                                <v-btn size="small" color="primary" @click="handleRestock(item.id)"
                                    :loading="restockLoading[item.id]">
                                    Restock
                                </v-btn>
                            </div>
                        </td>
                    </tr>
                </template>
            </v-data-table>

            <!-- Pagination -->
            <div v-if="inventory.meta && inventory.meta.last_page > 1" class="d-flex justify-center pa-4">
                <v-pagination :model-value="inventory.meta.current_page" :length="inventory.meta.last_page"
                    @update:model-value="handlePageChange" color="primary" total-visible="7" />
            </div>
        </v-card>
    </AppLayout>
</template>

<script setup>
    import { ref, computed, reactive } from 'vue';
    import { Head, router } from '@inertiajs/vue3';
    import AppLayout from '@/Layouts/AppLayout.vue';

    const props = defineProps({
        inventory: {
            type: Object,
            required: true
        },
        lowStockCount: {
            type: Number,
            default: 0
        },
        filters: {
            type: Object,
            default: () => ({})
        }
    });

    const search = ref(props.filters.search || '');
    const lowStockOnly = ref(!!props.filters.low_stock);
    const loading = ref(false);
    const restockQuantities = reactive({});
    const restockLoading = reactive({});

    // Initialize restock quantities
    props.inventory.data.forEach(item => {
        restockQuantities[item.id] = 10;
        restockLoading[item.id] = false;
    });

    const headers = [
        { title: 'Product', key: 'product', sortable: false },
        { title: 'Category', key: 'category', sortable: false },
        { title: 'Quantity', key: 'quantity', sortable: true },
        { title: 'Min Stock', key: 'minimum_stock', sortable: true },
        { title: 'Status', key: 'status', sortable: false },
        { title: 'Last Restocked', key: 'last_restocked', sortable: true },
        { title: 'Actions', key: 'actions', sortable: false }
    ];

    const isLowStock = (item) => {
        return item.quantity <= item.minimum_stock;
    };

    const getQuantityColor = (item) => {
        if (item.quantity === 0) return 'text-red-darken-2';
        if (isLowStock(item)) return 'text-yellow-darken-2';
        return 'text-green-darken-2';
    };

    const getStatusColor = (item) => {
        if (item.quantity === 0) return 'error';
        if (isLowStock(item)) return 'warning';
        return 'success';
    };

    const getStatusText = (item) => {
        if (item.quantity === 0) return 'Out of Stock';
        if (isLowStock(item)) return 'Low Stock';
        return 'In Stock';
    };

    const formatDate = (dateString) => {
        if (!dateString) return 'Never';
        return new Date(dateString).toLocaleDateString();
    };

    const handleFilter = () => {
        router.get('/manager/inventory', {
            search: search.value || undefined,
            low_stock: lowStockOnly.value ? '1' : undefined,
        }, {
            preserveState: true,
            preserveScroll: true,
        });
    };

    const handlePageChange = (page) => {
        router.get('/manager/inventory', {
            page,
            search: search.value || undefined,
            low_stock: lowStockOnly.value ? '1' : undefined,
        }, {
            preserveState: true,
            preserveScroll: true,
        });
    };

    const handleRestock = async (inventoryId) => {
        const quantity = restockQuantities[inventoryId];
        if (!quantity || quantity <= 0) return;

        restockLoading[inventoryId] = true;

        try {
            await router.post(`/manager/inventory/${inventoryId}/restock`, {
                quantity
            }, {
                preserveScroll: true,
                onSuccess: () => {
                    restockQuantities[inventoryId] = 10;
                }
            });
        } finally {
            restockLoading[inventoryId] = false;
        }
    };
</script>
