// temp_backup/Inventory/Index.vue
<template>
    <Head :title="__('Inventory Management')" />

    <div class="tw-w-full">
        <div class="tw-space-y-4">
            <!-- Header -->
            <div class="tw-flex tw-items-center tw-justify-between">
                <div>
                    <h2 class="tw-text-2xl tw-font-bold tw-tracking-tight">
                        {{ __("Inventory Management") }}
                    </h2>
                    <p class="tw-text-muted-foreground">
                        {{ __("Track stock levels and manage inventory") }}
                    </p>
                </div>
                <div class="tw-flex tw-items-center tw-gap-2">
                    <Button
                        variant="outline"
                        size="sm"
                        @click="refresh"
                        :disabled="loading"
                    >
                        <RotateCcw class="tw-w-4 tw-h-4 tw-mr-2" />
                        {{ __("Refresh") }}
                    </Button>
                </div>
            </div>

            <!-- Stats Cards -->
            <div class="tw-grid tw-grid-cols-1 md:tw-grid-cols-4 tw-gap-4">
                <Card>
                    <CardContent class="tw-p-4">
                        <div class="tw-flex tw-items-center tw-justify-between">
                            <div>
                                <p class="tw-text-sm tw-text-muted-foreground">{{ __("Total Products") }}</p>
                                <p class="tw-text-2xl tw-font-bold">{{ inventory?.data?.length || 0 }}</p>
                            </div>
                            <Package class="tw-w-8 tw-h-8 tw-text-primary" />
                        </div>
                    </CardContent>
                </Card>
                <Card>
                    <CardContent class="tw-p-4">
                        <div class="tw-flex tw-items-center tw-justify-between">
                            <div>
                                <p class="tw-text-sm tw-text-muted-foreground">{{ __("Low Stock") }}</p>
                                <p class="tw-text-2xl tw-font-bold tw-text-warning">{{ lowStockCount || 0 }}</p>
                            </div>
                            <AlertTriangle class="tw-w-8 tw-h-8 tw-text-warning" />
                        </div>
                    </CardContent>
                </Card>
                <Card>
                    <CardContent class="tw-p-4">
                        <div class="tw-flex tw-items-center tw-justify-between">
                            <div>
                                <p class="tw-text-sm tw-text-muted-foreground">{{ __("In Stock") }}</p>
                                <p class="tw-text-2xl tw-font-bold tw-text-success">{{ inStockCount }}</p>
                            </div>
                            <CheckCircle class="tw-w-8 tw-h-8 tw-text-success" />
                        </div>
                    </CardContent>
                </Card>
                <Card>
                    <CardContent class="tw-p-4">
                        <div class="tw-flex tw-items-center tw-justify-between">
                            <div>
                                <p class="tw-text-sm tw-text-muted-foreground">{{ __("Out of Stock") }}</p>
                                <p class="tw-text-2xl tw-font-bold tw-text-destructive">{{ outOfStockCount }}</p>
                            </div>
                            <XCircle class="tw-w-8 tw-h-8 tw-text-destructive" />
                        </div>
                    </CardContent>
                </Card>
            </div>

            <!-- Filters -->
            <div class="tw-flex tw-items-center tw-gap-2">
                <div class="tw-flex-1">
                    <Input
                        v-model="filters.search"
                        :placeholder="__('Search products...')"
                        class="tw-max-w-sm"
                        @input="debouncedSearch"
                    />
                </div>
                <Button
                    variant="outline"
                    @click="toggleLowStock"
                    :class="{ 'tw-bg-warning/10': filters.low_stock }"
                >
                    <AlertTriangle class="tw-w-4 tw-h-4 tw-mr-2" />
                    {{ __("Low Stock Only") }}
                </Button>
            </div>

            <!-- Data Table -->
            <div class="tw-rounded-md tw-border">
                <table class="tw-w-full tw-caption-bottom tw-text-sm">
                    <thead class="tw-border-b">
                        <tr class="tw-border-b tw-transition-colors hover:tw-bg-muted/50">
                            <th class="tw-h-12 tw-px-4 tw-text-left tw-align-middle tw-font-medium tw-text-muted-foreground">
                                {{ __("Product") }}
                            </th>
                            <th class="tw-h-12 tw-px-4 tw-text-left tw-align-middle tw-font-medium tw-text-muted-foreground">
                                {{ __("Category") }}
                            </th>
                            <th class="tw-h-12 tw-px-4 tw-text-center tw-align-middle tw-font-medium tw-text-muted-foreground">
                                {{ __("Stock") }}
                            </th>
                            <th class="tw-h-12 tw-px-4 tw-text-center tw-align-middle tw-font-medium tw-text-muted-foreground">
                                {{ __("Min Stock") }}
                            </th>
                            <th class="tw-h-12 tw-px-4 tw-text-center tw-align-middle tw-font-medium tw-text-muted-foreground">
                                {{ __("Status") }}
                            </th>
                            <th class="tw-h-12 tw-px-4 tw-text-left tw-align-middle tw-font-medium tw-text-muted-foreground">
                                {{ __("Last Restocked") }}
                            </th>
                            <th class="tw-h-12 tw-px-4 tw-text-left tw-align-middle tw-font-medium tw-text-muted-foreground tw-w-[100px]">
                                {{ __("Actions") }}
                            </th>
                        </tr>
                    </thead>
                    <tbody class="[&_tr:last-child]:tw-border-0">
                        <tr
                            v-for="item in inventoryItems"
                            :key="item.id"
                            class="tw-border-b tw-transition-colors hover:tw-bg-muted/50"
                        >
                            <td class="tw-p-4 tw-align-middle">
                                <div class="tw-flex tw-items-center tw-gap-3">
                                    <div class="tw-w-10 tw-h-10 tw-rounded-lg tw-bg-muted tw-flex tw-items-center tw-justify-center tw-overflow-hidden">
                                        <img
                                            v-if="item.product?.image"
                                            :src="`/storage/${item.product.image}`"
                                            :alt="item.product.name"
                                            class="tw-w-full tw-h-full tw-object-cover"
                                        />
                                        <Package v-else class="tw-w-5 tw-h-5 tw-text-muted-foreground" />
                                    </div>
                                    <div class="tw-font-medium">{{ item.product?.name }}</div>
                                </div>
                            </td>
                            <td class="tw-p-4 tw-align-middle">
                                <Badge variant="secondary">
                                    {{ item.product?.category?.name || __("No category") }}
                                </Badge>
                            </td>
                            <td class="tw-p-4 tw-align-middle tw-text-center">
                                <span class="tw-font-semibold" :class="{
                                    'tw-text-destructive': item.quantity === 0,
                                    'tw-text-warning': item.quantity > 0 && item.quantity <= item.minimum_stock,
                                    'tw-text-success': item.quantity > item.minimum_stock
                                }">
                                    {{ item.quantity }}
                                </span>
                            </td>
                            <td class="tw-p-4 tw-align-middle tw-text-center">
                                <span class="tw-text-muted-foreground">{{ item.minimum_stock }}</span>
                            </td>
                            <td class="tw-p-4 tw-align-middle tw-text-center">
                                <Badge :variant="getStockStatusVariant(item)">
                                    {{ getStockStatusText(item) }}
                                </Badge>
                            </td>
                            <td class="tw-p-4 tw-align-middle">
                                <div class="tw-text-sm tw-text-muted-foreground">
                                    {{ item.last_restocked_at ? new Date(item.last_restocked_at).toLocaleDateString() : __("Never") }}
                                </div>
                            </td>
                            <td class="tw-p-4 tw-align-middle">
                                <DropdownMenu>
                                    <DropdownMenuTrigger asChild>
                                        <Button variant="ghost" size="sm">
                                            <MoreHorizontal class="tw-h-4 tw-w-4" />
                                        </Button>
                                    </DropdownMenuTrigger>
                                    <DropdownMenuContent align="end">
                                        <DropdownMenuLabel>{{ __("Actions") }}</DropdownMenuLabel>
                                        <DropdownMenuSeparator />
                                        <DropdownMenuItem @click="viewInventory(item)">
                                            <Eye class="tw-w-4 tw-h-4 tw-mr-2" />
                                            {{ __("View") }}
                                        </DropdownMenuItem>
                                        <DropdownMenuItem @click="editInventory(item)">
                                            <Edit class="tw-w-4 tw-h-4 tw-mr-2" />
                                            {{ __("Edit") }}
                                        </DropdownMenuItem>
                                        <DropdownMenuItem @click="openRestockDialog(item)">
                                            <Plus class="tw-w-4 tw-h-4 tw-mr-2" />
                                            {{ __("Restock") }}
                                        </DropdownMenuItem>
                                    </DropdownMenuContent>
                                </DropdownMenu>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>

            <!-- Pagination -->
            <div v-if="meta" class="tw-flex tw-items-center tw-justify-between">
                <p class="tw-text-sm tw-text-muted-foreground">
                    {{ __("Showing :from to :to of :total results", {
                        args: {
                            from: meta.from || 0,
                            to: meta.to || 0,
                            total: meta.total || 0,
                        },
                    }) }}
                </p>

                <div class="tw-flex tw-items-center tw-gap-2">
                    <Button
                        variant="outline"
                        size="sm"
                        @click="goToPage(currentPage - 1)"
                        :disabled="currentPage === 1"
                    >
                        <ChevronLeft class="tw-h-4 tw-w-4" />
                        {{ __("Previous") }}
                    </Button>

                    <span class="tw-text-sm">
                        {{ __("Page :current of :total", {
                            args: {
                                current: currentPage,
                                total: lastPage,
                            },
                        }) }}
                    </span>

                    <Button
                        variant="outline"
                        size="sm"
                        @click="goToPage(currentPage + 1)"
                        :disabled="currentPage === lastPage"
                    >
                        {{ __("Next") }}
                        <ChevronRight class="tw-h-4 tw-w-4" />
                    </Button>
                </div>
            </div>

            <!-- Empty State -->
            <div v-if="inventoryItems.length === 0" class="tw-text-center tw-py-12">
                <Package class="tw-mx-auto tw-h-12 tw-w-12 tw-text-muted-foreground" />
                <h3 class="tw-mt-2 tw-text-sm tw-font-semibold">
                    {{ __("No inventory items found") }}
                </h3>
                <p class="tw-mt-1 tw-text-sm tw-text-muted-foreground">
                    {{ filters.search ? __("Try adjusting your search") : __("No inventory available") }}
                </p>
            </div>
        </div>

        <!-- Restock Dialog -->
        <Dialog v-model:open="showRestockDialog">
            <DialogContent>
                <DialogHeader>
                    <DialogTitle>{{ __("Restock Inventory") }}</DialogTitle>
                    <DialogDescription>
                        {{ __("Add stock quantity for") }} {{ selectedItem?.product?.name }}
                    </DialogDescription>
                </DialogHeader>
                <div class="tw-space-y-4 tw-py-4">
                    <div class="tw-space-y-2">
                        <Label for="restock_quantity">{{ __("Quantity to Add") }}</Label>
                        <Input
                            id="restock_quantity"
                            v-model.number="restockQuantity"
                            type="number"
                            min="1"
                            :placeholder="__('Enter quantity')"
                        />
                        <p class="tw-text-sm tw-text-muted-foreground">
                            {{ __("Current:") }} {{ selectedItem?.quantity }} → 
                            {{ __("New total:") }} {{ (selectedItem?.quantity || 0) + (restockQuantity || 0) }}
                        </p>
                    </div>
                </div>
                <DialogFooter>
                    <Button variant="outline" @click="showRestockDialog = false">
                        {{ __("Cancel") }}
                    </Button>
                    <Button @click="restock" :disabled="!restockQuantity || restockQuantity < 1">
                        <Plus class="tw-w-4 tw-h-4 tw-mr-2" />
                        {{ __("Restock") }}
                    </Button>
                </DialogFooter>
            </DialogContent>
        </Dialog>
    </div>
</template>

<script setup>
import { computed, ref } from "vue";
import { router } from "@inertiajs/vue3";
import { Head } from "@inertiajs/vue3";
import { Button } from "@/Components/ui/button";
import { Input } from "@/Components/ui/input";
import { Label } from "@/Components/ui/label";
import { Badge } from "@/Components/ui/badge";
import { Card, CardContent } from "@/Components/ui/card";
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogTitle,
} from "@/Components/ui/dialog";
import {
    DropdownMenu,
    DropdownMenuContent,
    DropdownMenuItem,
    DropdownMenuLabel,
    DropdownMenuSeparator,
    DropdownMenuTrigger,
} from "@/Components/ui/dropdown-menu";
import {
    RotateCcw,
    MoreHorizontal,
    Eye,
    Edit,
    Plus,
    ChevronLeft,
    ChevronRight,
    Package,
    AlertTriangle,
    CheckCircle,
    XCircle,
} from "lucide-vue-next";
import { useToast } from "@/Components/ui/toast/use-toast";
import { debounce } from "lodash";

const { toast } = useToast();

const props = defineProps({
    inventory: {
        type: Object,
        required: true,
    },
    lowStockCount: {
        type: Number,
        default: 0,
    },
    filters: {
        type: Object,
        default: () => ({}),
    },
});

// Pagination data
const inventoryItems = computed(() => props.inventory.data || []);
const meta = computed(() => props.inventory.meta || {});
const currentPage = computed(() => meta.value.current_page || 1);
const lastPage = computed(() => meta.value.last_page || 1);

// Stats
const inStockCount = computed(() => 
    inventoryItems.value.filter(item => item.quantity > item.minimum_stock).length
);
const outOfStockCount = computed(() => 
    inventoryItems.value.filter(item => item.quantity === 0).length
);

// Local state
const loading = ref(false);
const showRestockDialog = ref(false);
const selectedItem = ref(null);
const restockQuantity = ref(null);
const filters = ref({
    search: props.filters.search || "",
    low_stock: props.filters.low_stock || false,
});

// Debounced search
const debouncedSearch = debounce(() => {
    applyFilters();
}, 300);

// Apply filters
const applyFilters = () => {
    const params = {};

    if (filters.value.search) {
        params.search = filters.value.search;
    }
    if (filters.value.low_stock) {
        params.low_stock = true;
    }

    router.get(route("dashboard.inventory.index"), params, {
        preserveState: true,
        preserveScroll: true,
        only: ["inventory", "lowStockCount"],
    });
};

const toggleLowStock = () => {
    filters.value.low_stock = !filters.value.low_stock;
    applyFilters();
};

// Pagination
const goToPage = (page) => {
    if (page < 1 || page > lastPage.value) return;

    router.get(
        route("dashboard.inventory.index"),
        {
            page,
            ...filters.value,
        },
        {
            preserveState: true,
            preserveScroll: true,
            only: ["inventory"],
        }
    );
};

// Stock status helpers
const getStockStatusVariant = (item) => {
    if (item.quantity === 0) return 'destructive';
    if (item.quantity <= item.minimum_stock) return 'warning';
    return 'success';
};

const getStockStatusText = (item) => {
    if (item.quantity === 0) return __("Out of Stock");
    if (item.quantity <= item.minimum_stock) return __("Low Stock");
    return __("In Stock");
};

// Actions
const refresh = () => {
    loading.value = true;
    router.reload({
        only: ["inventory", "lowStockCount"],
        onFinish: () => {
            loading.value = false;
        },
    });
};

const viewInventory = (item) => {
    router.visit(route("dashboard.inventory.show", item.id));
};

const editInventory = (item) => {
    router.visit(route("dashboard.inventory.edit", item.id));
};

const openRestockDialog = (item) => {
    selectedItem.value = item;
    restockQuantity.value = null;
    showRestockDialog.value = true;
};

const restock = () => {
    if (!restockQuantity.value || restockQuantity.value < 1) return;

    router.post(route("dashboard.inventory.restock", selectedItem.value.id), {
        quantity: restockQuantity.value
    }, {
        onSuccess: () => {
            toast({
                title: __("Success"),
                description: __("Inventory restocked successfully"),
            });
            showRestockDialog.value = false;
            selectedItem.value = null;
            restockQuantity.value = null;
        },
        onError: () => {
            toast({
                title: __("Error"),
                description: __("Failed to restock inventory"),
                variant: "destructive",
            });
        },
    });
};
</script>

// resources/js/Pages/Inventory/Index.tsx
import { useState } from 'react';
import { Head, Link, router, useForm } from '@inertiajs/react';
import AppLayout from '@/Layouts/AppLayout';
import { Inventory, Product, PaginatedData } from '@/types';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { Checkbox } from '@/components/ui/checkbox';
import { AlertTriangle, Package, Plus, Search } from 'lucide-react';

interface InventoryWithProduct extends Inventory {
    product: Product & {
        category: { name: string };
    };
}

interface Props {
    inventory: PaginatedData<InventoryWithProduct>;
    lowStockCount: number;
    filters: {
        search?: string;
        low_stock?: string;
    };
}

export default function Index({ inventory, lowStockCount, filters }: Props) {
    const [search, setSearch] = useState(filters.search || '');
    const [lowStockOnly, setLowStockOnly] = useState(!!filters.low_stock);

    const handleFilter = () => {
        router.get('/manager/inventory', {
            search: search || undefined,
            low_stock: lowStockOnly ? '1' : undefined,
        }, {
            preserveState: true,
            preserveScroll: true,
        });
    };

    const restockForm = useForm<{ quantity: number }>({
        quantity: 10,
    });

    const handleRestock = (inventoryId: number) => {
        restockForm.post(`/manager/inventory/${inventoryId}/restock`, {
            preserveScroll: true,
            onSuccess: () => {
                restockForm.reset();
            },
        });
    };

    return (
        <AppLayout>
            <Head title="Inventory Management" />

            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                {/* Header */}
                <div className="mb-6 flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
                    <div>
                        <h1 className="text-3xl font-bold text-gray-900">Inventory Management</h1>
                        <p className="text-gray-600">Manage product stock levels</p>
                    </div>
                    <div className="flex gap-3">
                        <Link href="/manager/inventory/alerts">
                            <Button variant="outline">
                                <AlertTriangle className="w-4 h-4 mr-2" />
                                Low Stock Alerts ({lowStockCount})
                            </Button>
                        </Link>
                        <Link href="/manager/inventory-orders/create">
                            <Button>
                                <Plus className="w-4 h-4 mr-2" />
                                Create Restock Order
                            </Button>
                        </Link>
                    </div>
                </div>

                {/* Filters */}
                <Card className="mb-6">
                    <CardContent className="pt-6">
                        <div className="flex flex-col sm:flex-row gap-4">
                            <div className="flex-1 relative">
                                <Search className="absolute left-3 top-3 h-4 w-4 text-gray-400" />
                                <Input
                                    type="text"
                                    placeholder="Search products..."
                                    value={search}
                                    onChange={(e) => setSearch(e.target.value)}
                                    onKeyDown={(e) => e.key === 'Enter' && handleFilter()}
                                    className="pl-10"
                                />
                            </div>
                            <div className="flex items-center space-x-2">
                                <Checkbox
                                    id="low-stock"
                                    checked={lowStockOnly}
                                    onCheckedChange={(checked) => setLowStockOnly(checked as boolean)}
                                />
                                <label htmlFor="low-stock" className="text-sm text-gray-700 cursor-pointer">
                                    Low Stock Only
                                </label>
                            </div>
                            <Button onClick={handleFilter}>Filter</Button>
                        </div>
                    </CardContent>
                </Card>

                {/* Inventory Table */}
                <Card>
                    <CardContent className="p-0">
                        <div className="overflow-x-auto">
                            <table className="min-w-full divide-y divide-gray-200">
                                <thead className="bg-gray-50">
                                    <tr>
                                        <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                            Product
                                        </th>
                                        <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                            Category
                                        </th>
                                        <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                            Quantity
                                        </th>
                                        <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                            Min Stock
                                        </th>
                                        <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                            Status
                                        </th>
                                        <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                            Last Restocked
                                        </th>
                                        <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                            Actions
                                        </th>
                                    </tr>
                                </thead>
                                <tbody className="bg-white divide-y divide-gray-200">
                                    {inventory.data.map((item) => {
                                        const isLowStock = item.quantity <= item.minimum_stock;
                                        const isOutOfStock = item.quantity === 0;

                                        return (
                                            <tr
                                                key={item.id}
                                                className={isLowStock ? 'bg-yellow-50' : ''}
                                            >
                                                <td className="px-6 py-4 whitespace-nowrap">
                                                    <div className="flex items-center">
                                                        <Package className="h-5 w-5 text-gray-400 mr-3" />
                                                        <div className="font-medium text-gray-900">
                                                            {item.product.name}
                                                        </div>
                                                    </div>
                                                </td>
                                                <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-600">
                                                    {item.product.category.name}
                                                </td>
                                                <td className="px-6 py-4 whitespace-nowrap">
                                                    <span className={`text-lg font-semibold ${
                                                        isOutOfStock
                                                            ? 'text-red-600'
                                                            : isLowStock
                                                            ? 'text-yellow-600'
                                                            : 'text-green-600'
                                                    }`}>
                                                        {item.quantity}
                                                    </span>
                                                </td>
                                                <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-600">
                                                    {item.minimum_stock}
                                                </td>
                                                <td className="px-6 py-4 whitespace-nowrap">
                                                    {isOutOfStock ? (
                                                        <Badge variant="destructive">Out of Stock</Badge>
                                                    ) : isLowStock ? (
                                                        <Badge variant="secondary" className="bg-yellow-100 text-yellow-800">
                                                            Low Stock
                                                        </Badge>
                                                    ) : (
                                                        <Badge variant="default" className="bg-green-100 text-green-800">
                                                            In Stock
                                                        </Badge>
                                                    )}
                                                </td>
                                                <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-600">
                                                    {item.last_restocked_at
                                                        ? new Date(item.last_restocked_at).toLocaleDateString()
                                                        : 'Never'}
                                                </td>
                                                <td className="px-6 py-4 whitespace-nowrap">
                                                    <form
                                                        onSubmit={(e) => {
                                                            e.preventDefault();
                                                            handleRestock(item.id);
                                                        }}
                                                        className="flex items-center gap-2"
                                                    >
                                                        <Input
                                                            type="number"
                                                            min="1"
                                                            defaultValue="10"
                                                            className="w-20"
                                                            onChange={(e) => restockForm.setData('quantity', parseInt(e.target.value))}
                                                        />
                                                        <Button type="submit" size="sm">
                                                            Restock
                                                        </Button>
                                                    </form>
                                                </td>
                                            </tr>
                                        );
                                    })}
                                </tbody>
                            </table>
                        </div>

                        {inventory.data.length === 0 && (
                            <div className="text-center py-12 text-gray-500">
                                No inventory records found.
                            </div>
                        )}
                    </CardContent>
                </Card>

                {/* Pagination */}
                {inventory.meta.last_page > 1 && (
                    <div className="mt-6 flex justify-center gap-2">
                        {inventory.links.prev && (
                            <Link href={inventory.links.prev}>
                                <Button variant="outline">Previous</Button>
                            </Link>
                        )}
                        <span className="flex items-center px-4 text-sm text-gray-700">
                            Page {inventory.meta.current_page} of {inventory.meta.last_page}
                        </span>
                        {inventory.links.next && (
                            <Link href={inventory.links.next}>
                                <Button variant="outline">Next</Button>
                            </Link>
                        )}
                    </div>
                )}
            </div>
        </AppLayout>
    );
}
