// resources/js/Pages/Dashboard/Orders/Create.vue
<template>
  <DashboardLayout>
    <Head title="Create Order" />

    <v-container>
      <!-- Header -->
      <div class="d-flex justify-space-between align-center mb-6">
        <div>
          <h1 class="text-h3 font-weight-bold text-grey-darken-3 mb-2">
            Create Order
          </h1>
          <p class="text-grey-darken-1">
            Create a new customer order
          </p>
        </div>
        <v-btn
          color="grey"
          variant="outlined"
          :to="{ name: 'dashboard.orders.index' }"
        >
          <v-icon left>mdi-arrow-left</v-icon>
          Back to Orders
        </v-btn>
      </div>

      <!-- Create Form -->
      <v-card elevation="2">
        <v-card-title class="text-h6 font-weight-bold text-grey-darken-3">
          <v-icon left color="primary">mdi-plus</v-icon>
          Order Information
        </v-card-title>
        <v-card-text>
          <v-form ref="form" v-model="valid">
            <v-row>
              <!-- Customer Selection -->
              <v-col cols="12" md="6">
                <v-select
                  v-model="form.customer_id"
                  :items="customers"
                  item-title="name"
                  item-value="id"
                  label="Customer"
                  variant="outlined"
                  :rules="[rules.required]"
                  required
                >
                  <template v-slot:item="{ props, item }">
                    <v-list-item v-bind="props">
                      <v-list-item-title>{{ item.raw.name }}</v-list-item-title>
                      <v-list-item-subtitle>{{ item.raw.email }}</v-list-item-subtitle>
                    </v-list-item>
                  </template>
                </v-select>
              </v-col>

              <!-- Order Number -->
              <v-col cols="12" md="6">
                <v-text-field
                  v-model="form.order_number"
                  label="Order Number"
                  variant="outlined"
                  :rules="[rules.required]"
                  required
                  hint="Auto-generated if left empty"
                  persistent-hint
                />
              </v-col>

              <!-- Order Status -->
              <v-col cols="12" md="6">
                <v-select
                  v-model="form.status"
                  :items="statusOptions"
                  item-title="text"
                  item-value="value"
                  label="Status"
                  variant="outlined"
                  :rules="[rules.required]"
                  required
                />
              </v-col>


              <!-- Delivery Address -->
              <v-col cols="12">
                <v-textarea
                  v-model="form.delivery_address"
                  label="Delivery Address"
                  variant="outlined"
                  rows="3"
                  :rules="[rules.required]"
                  required
                />
              </v-col>

              <!-- Special Instructions -->
              <v-col cols="12">
                <v-textarea
                  v-model="form.special_instructions"
                  label="Special Instructions"
                  variant="outlined"
                  rows="2"
                  hint="Any special notes for this order"
                  persistent-hint
                />
              </v-col>
            </v-row>

            <!-- Order Items Section -->
            <v-divider class="my-6" />
            
            <div class="d-flex justify-space-between align-center mb-4">
              <h3 class="text-h6 font-weight-bold">Order Items</h3>
              <v-btn color="primary" @click="addOrderItem">
                <v-icon left>mdi-plus</v-icon>
                Add Item
              </v-btn>
            </div>

            <v-card
              v-for="(item, index) in form.order_items"
              :key="index"
              elevation="1"
              class="mb-4"
            >
              <v-card-text>
                <v-row>
                  <v-col cols="12" md="5">
                    <v-select
                      v-model="item.product_id"
                      :items="products"
                      item-title="name"
                      item-value="id"
                      label="Product"
                      variant="outlined"
                      @update:model-value="updateItemPrice(index)"
                    />
                  </v-col>
                  <v-col cols="12" md="2">
                    <v-text-field
                      v-model="item.quantity"
                      label="Quantity"
                      type="number"
                      min="1"
                      variant="outlined"
                      @input="updateItemTotal(index)"
                    />
                  </v-col>
                  <v-col cols="12" md="2">
                    <v-text-field
                      :model-value="getProductPrice(item.product_id)"
                      label="Price"
                      prefix="$"
                      variant="outlined"
                      readonly
                    />
                  </v-col>
                  <v-col cols="12" md="2">
                    <v-text-field
                      v-model="item.total"
                      label="Total"
                      prefix="$"
                      variant="outlined"
                      readonly
                    />
                  </v-col>
                  <v-col cols="12" md="1">
                    <v-btn
                      color="error"
                      variant="text"
                      @click="removeOrderItem(index)"
                      :disabled="form.order_items.length === 1"
                    >
                      <v-icon>mdi-delete</v-icon>
                    </v-btn>
                  </v-col>
                </v-row>
              </v-card-text>
            </v-card>

            <!-- Order Total -->
            <v-card elevation="2" color="primary" variant="tonal">
              <v-card-text>
                <div class="d-flex justify-space-between align-center">
                  <span class="text-h6 font-weight-bold">Order Total:</span>
                  <span class="text-h5 font-weight-bold">${{ formatPrice(orderTotal) }}</span>
                </div>
              </v-card-text>
            </v-card>

            <!-- Form Actions -->
            <v-row class="mt-6">
              <v-col cols="12">
                <div class="d-flex gap-4">
                  <v-btn
                    color="primary"
                    size="large"
                    :disabled="!valid || form.order_items.length === 0"
                    @click="submitForm"
                    :loading="loading"
                  >
                    <v-icon left>mdi-check</v-icon>
                    Create Order
                  </v-btn>
                  <v-btn
                    color="grey"
                    variant="outlined"
                    size="large"
                    :to="{ name: 'dashboard.orders.index' }"
                  >
                    Cancel
                  </v-btn>
                </div>
              </v-col>
            </v-row>
          </v-form>
        </v-card-text>
      </v-card>
    </v-container>
  </DashboardLayout>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue';
import { Head, router } from '@inertiajs/vue3';
import DashboardLayout from '@/Layouts/DashboardLayout.vue';

const props = defineProps({
  customers: {
    type: Array,
    default: () => []
  },
  products: {
    type: Array,
    default: () => []
  }
});

const form = ref({
  customer_id: null,
  order_number: '',
  status: 'pending',
  delivery_address: '',
  special_instructions: '',
  order_items: [{
    product_id: null,
    quantity: 1,
    total: 0
  }]
});

const valid = ref(false);
const loading = ref(false);

const statusOptions = [
  { text: 'Pending', value: 'pending' },
  { text: 'Confirmed', value: 'confirmed' },
  { text: 'Preparing', value: 'preparing' },
  { text: 'Ready', value: 'ready' },
  { text: 'Delivered', value: 'delivered' },
  { text: 'Cancelled', value: 'cancelled' }
];

const rules = {
  required: (value) => !!value || 'This field is required'
};

const orderTotal = computed(() => {
  return form.value.order_items.reduce((sum, item) => {
    return sum + (parseFloat(item.total) || 0);
  }, 0);
});

const formatPrice = (price) => {
  const numPrice = typeof price === 'number' ? price : parseFloat(price);
  return numPrice.toFixed(2);
};

const getProductPrice = (productId) => {
  const product = props.products.find(p => p.id === productId);
  return product ? formatPrice(product.price) : '0.00';
};

const updateItemPrice = (index) => {
  const item = form.value.order_items[index];
  const price = getProductPrice(item.product_id);
  item.total = formatPrice(parseFloat(price) * item.quantity);
};

const updateItemTotal = (index) => {
  const item = form.value.order_items[index];
  const price = getProductPrice(item.product_id);
  item.total = formatPrice(parseFloat(price) * item.quantity);
};

const addOrderItem = () => {
  form.value.order_items.push({
    product_id: null,
    quantity: 1,
    total: 0
  });
};

const removeOrderItem = (index) => {
  if (form.value.order_items.length > 1) {
    form.value.order_items.splice(index, 1);
  }
};

onMounted(() => {
  // Set default order date to now
  const now = new Date();
});

const submitForm = () => {
  if (valid.value && form.value.order_items.length > 0) {
    loading.value = true;
    
    const orderData = {
      ...form.value,
      total: orderTotal.value
    };

    router.post(route('dashboard.orders.store'), orderData, {
      onSuccess: () => {
        // Order created successfully
      },
      onError: () => {
        loading.value = false;
      },
      onFinish: () => {
        loading.value = false;
      }
    });
  }
};
</script>

// resources/js/Pages/Orders/Create.tsx
import { FormEventHandler, useState } from 'react';
import { Head, Link, useForm, router } from '@inertiajs/react';
import AppLayout from '@/Layouts/AppLayout';
import { Product, Category } from '@/types';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { ArrowLeft, Plus, Minus, Trash2, ShoppingCart } from 'lucide-react';
import { formatPrice } from '@/lib/utils';

interface Props {
    products: Product[];
    categories: Category[];
}

interface CartItem {
    product: Product;
    quantity: number;
    special_instructions?: string;
}

export default function Create({ products, categories }: Props) {
    const [cart, setCart] = useState<CartItem[]>([]);
    const [selectedCategory, setSelectedCategory] = useState<string>('');
    const [deliveryAddress, setDeliveryAddress] = useState('');
    const [notes, setNotes] = useState('');

    const { post, processing } = useForm();

    const addToCart = (product: Product) => {
        const existingItem = cart.find(item => item.product.id === product.id);
        if (existingItem) {
            updateQuantity(product.id, existingItem.quantity + 1);
        } else {
            setCart([...cart, { product, quantity: 1 }]);
        }
    };

    const updateQuantity = (productId: number, quantity: number) => {
        if (quantity <= 0) {
            removeFromCart(productId);
            return;
        }
        setCart(cart.map(item =>
            item.product.id === productId ? { ...item, quantity } : item
        ));
    };

    const updateInstructions = (productId: number, instructions: string) => {
        setCart(cart.map(item =>
            item.product.id === productId ? { ...item, special_instructions: instructions } : item
        ));
    };

    const removeFromCart = (productId: number) => {
        setCart(cart.filter(item => item.product.id !== productId));
    };

    const calculateSubtotal = () => {
        return cart.reduce((sum, item) => {
            const price = typeof item.product.price === 'string'
                ? parseFloat(item.product.price)
                : item.product.price;
            return sum + (price * item.quantity);
        }, 0);
    };

    const calculateTax = () => {
        return calculateSubtotal() * 0.1; // 10% tax
    };

    const calculateTotal = () => {
        return calculateSubtotal() + calculateTax();
    };

    const submit: FormEventHandler = (e) => {
        e.preventDefault();

        const orderData = {
            items: cart.map(item => ({
                product_id: item.product.id,
                quantity: item.quantity,
                special_instructions: item.special_instructions,
            })),
            delivery_address: deliveryAddress,
            notes: notes,
        };

        post('/orders', {
            data: orderData,
        });
    };

    const filteredProducts = selectedCategory
        ? products.filter(p => p.category_id.toString() === selectedCategory)
        : products;

    return (
        <AppLayout>
            <Head title="Create Order" />

            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
                <Link href="/orders">
                    <Button variant="outline" className="mb-6">
                        <ArrowLeft className="w-4 h-4 mr-2" />
                        Back to Orders
                    </Button>
                </Link>

                <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                    {/* Products Selection */}
                    <div className="lg:col-span-2 space-y-6">
                        <Card>
                            <CardHeader>
                                <CardTitle>Select Products</CardTitle>
                                <CardDescription>Choose items for your order</CardDescription>
                            </CardHeader>
                            <CardContent>
                                {/* Category Filter */}
                                <div className="mb-4">
                                    <Select value={selectedCategory} onValueChange={setSelectedCategory}>
                                        <SelectTrigger>
                                            <SelectValue placeholder="All Categories" />
                                        </SelectTrigger>
                                        <SelectContent>
                                            <SelectItem value="">All Categories</SelectItem>
                                            {categories.map((category) => (
                                                <SelectItem key={category.id} value={category.id.toString()}>
                                                    {category.name}
                                                </SelectItem>
                                            ))}
                                        </SelectContent>
                                    </Select>
                                </div>

                                {/* Products Grid */}
                                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 max-h-[600px] overflow-y-auto">
                                    {filteredProducts.map((product) => {
                                        const isAvailable = product.is_available && product.inventory && product.inventory.quantity > 0;
                                        return (
                                            <Card key={product.id} className={!isAvailable ? 'opacity-50' : ''}>
                                                <CardHeader className="p-4">
                                                    <div className="flex justify-between items-start">
                                                        <div className="flex-1">
                                                            <CardTitle className="text-sm">{product.name}</CardTitle>
                                                            <p className="text-xs text-gray-500 mt-1">
                                                                {product.category?.name}
                                                            </p>
                                                        </div>
                                                        <Badge variant={isAvailable ? "default" : "destructive"} className="text-xs">
                                                            {isAvailable ? 'Available' : 'Out of Stock'}
                                                        </Badge>
                                                    </div>
                                                    <p className="text-sm font-bold text-indigo-600 mt-2">
                                                        {formatPrice(product.price)}
                                                    </p>
                                                </CardHeader>
                                                <CardContent className="p-4 pt-0">
                                                    <Button
                                                        size="sm"
                                                        className="w-full"
                                                        onClick={() => addToCart(product)}
                                                        disabled={!isAvailable}
                                                    >
                                                        <Plus className="w-3 h-3 mr-1" />
                                                        Add to Cart
                                                    </Button>
                                                </CardContent>
                                            </Card>
                                        );
                                    })}
                                </div>
                            </CardContent>
                        </Card>
                    </div>

                    {/* Cart & Checkout */}
                    <div className="space-y-6">
                        <Card>
                            <CardHeader>
                                <CardTitle>Your Cart</CardTitle>
                                <CardDescription>{cart.length} items</CardDescription>
                            </CardHeader>
                            <CardContent>
                                {cart.length === 0 ? (
                                    <div className="text-center py-8 text-gray-500">
                                        <ShoppingCart className="w-12 h-12 mx-auto mb-2 text-gray-400" />
                                        <p>Your cart is empty</p>
                                    </div>
                                ) : (
                                    <div className="space-y-4">
                                        {cart.map((item) => (
                                            <div key={item.product.id} className="border-b pb-4">
                                                <div className="flex justify-between items-start mb-2">
                                                    <div className="flex-1">
                                                        <p className="font-medium text-sm">{item.product.name}</p>
                                                        <p className="text-xs text-gray-500">
                                                            {formatPrice(item.product.price)} each
                                                        </p>
                                                    </div>
                                                    <Button
                                                        size="icon"
                                                        variant="ghost"
                                                        onClick={() => removeFromCart(item.product.id)}
                                                    >
                                                        <Trash2 className="w-4 h-4 text-red-500" />
                                                    </Button>
                                                </div>
                                                <div className="flex items-center gap-2 mb-2">
                                                    <Button
                                                        size="icon"
                                                        variant="outline"
                                                        onClick={() => updateQuantity(item.product.id, item.quantity - 1)}
                                                    >
                                                        <Minus className="w-3 h-3" />
                                                    </Button>
                                                    <span className="w-8 text-center">{item.quantity}</span>
                                                    <Button
                                                        size="icon"
                                                        variant="outline"
                                                        onClick={() => updateQuantity(item.product.id, item.quantity + 1)}
                                                    >
                                                        <Plus className="w-3 h-3" />
                                                    </Button>
                                                </div>
                                                <Input
                                                    placeholder="Special instructions..."
                                                    value={item.special_instructions || ''}
                                                    onChange={(e) => updateInstructions(item.product.id, e.target.value)}
                                                    className="text-sm"
                                                />
                                            </div>
                                        ))}
                                    </div>
                                )}
                            </CardContent>
                        </Card>

                        {cart.length > 0 && (
                            <form onSubmit={submit}>
                                <Card>
                                    <CardHeader>
                                        <CardTitle>Order Details</CardTitle>
                                    </CardHeader>
                                    <CardContent className="space-y-4">
                                        <div>
                                            <label className="text-sm font-medium mb-2 block">
                                                Delivery Address
                                            </label>
                                            <textarea
                                                value={deliveryAddress}
                                                onChange={(e) => setDeliveryAddress(e.target.value)}
                                                rows={2}
                                                className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
                                                placeholder="Enter delivery address..."
                                            />
                                        </div>
                                        <div>
                                            <label className="text-sm font-medium mb-2 block">
                                                Order Notes
                                            </label>
                                            <textarea
                                                value={notes}
                                                onChange={(e) => setNotes(e.target.value)}
                                                rows={2}
                                                className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
                                                placeholder="Any special requests..."
                                            />
                                        </div>

                                        <div className="border-t pt-4 space-y-2">
                                            <div className="flex justify-between text-sm">
                                                <span>Subtotal:</span>
                                                <span>{formatPrice(calculateSubtotal())}</span>
                                            </div>
                                            <div className="flex justify-between text-sm">
                                                <span>Tax (10%):</span>
                                                <span>{formatPrice(calculateTax())}</span>
                                            </div>
                                            <div className="flex justify-between text-lg font-bold">
                                                <span>Total:</span>
                                                <span className="text-indigo-600">
                                                    {formatPrice(calculateTotal())}
                                                </span>
                                            </div>
                                        </div>

                                        <Button type="submit" className="w-full" disabled={processing}>
                                            <ShoppingCart className="w-4 h-4 mr-2" />
                                            Place Order
                                        </Button>
                                    </CardContent>
                                </Card>
                            </form>
                        )}
                    </div>
                </div>
            </div>
        </AppLayout>
    );
}
