// resources/js/Pages/Dashboard/Products/Create.vue
<template>
    <Head :title="__('Create Product')" />

    <vee-form
        :validation-schema="schema"
        @submit="submit"
        v-slot="{ meta, setErrors }"
    >
        <div class="tw-space-y-6">
            <!-- Header -->
            <div class="tw-flex tw-items-center tw-justify-between">
                <div>
                    <h2 class="tw-text-2xl tw-font-bold tw-tracking-tight">
                        {{ __("Create Product") }}
                    </h2>
                    <p class="tw-text-muted-foreground">
                        {{ __("Add a new product to your menu") }}
                    </p>
                </div>
                <Button
                    variant="outline"
                    @click="goBack"
                >
                    <ArrowLeft class="tw-w-4 tw-h-4 tw-mr-2" />
                    {{ __("Back") }}
                </Button>
            </div>

            <!-- Form -->
            <div class="tw-grid tw-grid-cols-1 lg:tw-grid-cols-3 tw-gap-6">
                <!-- Main Form -->
                <div class="tw-lg:col-span-2 tw-space-y-6">
                    <!-- Basic Information -->
                    <Card>
                        <CardHeader>
                            <CardTitle>{{ __("Basic Information") }}</CardTitle>
                            <CardDescription>
                                {{ __("Enter the basic details of the product") }}
                            </CardDescription>
                        </CardHeader>
                        <CardContent class="tw-space-y-4">
                            <vee-field
                                name="name"
                                v-slot="{ field, errors }"
                            >
                                <div class="tw-space-y-2">
                                    <Label for="name">
                                        {{ __("Product Name") }}
                                        <span class="tw-text-destructive">*</span>
                                    </Label>
                                    <Input
                                        id="name"
                                        v-bind="field"
                                        :model-value="form.name"
                                        @update:model-value="(val) => form.name = val"
                                        :class="{ 'tw-border-destructive': errors.length }"
                                        :placeholder="__('Enter product name')"
                                    />
                                    <p v-if="errors.length" class="tw-text-sm tw-text-destructive">
                                        {{ errors[0] }}
                                    </p>
                                </div>
                            </vee-field>

                            <vee-field
                                name="description"
                                v-slot="{ field, errors }"
                            >
                                <div class="tw-space-y-2">
                                    <Label for="description">{{ __("Description") }}</Label>
                                    <Textarea
                                        id="description"
                                        v-bind="field"
                                        :model-value="form.description"
                                        @update:model-value="(val) => form.description = val"
                                        rows="3"
                                        :class="{ 'tw-border-destructive': errors.length }"
                                        :placeholder="__('Enter product description')"
                                    />
                                    <p v-if="errors.length" class="tw-text-sm tw-text-destructive">
                                        {{ errors[0] }}
                                    </p>
                                </div>
                            </vee-field>

                            <div class="tw-grid tw-grid-cols-1 md:tw-grid-cols-2 tw-gap-4">
                                <vee-field
                                    name="price"
                                    v-slot="{ field, errors }"
                                >
                                    <div class="tw-space-y-2">
                                        <Label for="price">
                                            {{ __("Price") }}
                                            <span class="tw-text-destructive">*</span>
                                        </Label>
                                        <Input
                                            id="price"
                                            type="number"
                                            step="0.01"
                                            min="0"
                                            v-bind="field"
                                            :model-value="form.price"
                                            @update:model-value="(val) => form.price = val"
                                            :class="{ 'tw-border-destructive': errors.length }"
                                            :placeholder="__('0.00')"
                                        />
                                        <p v-if="errors.length" class="tw-text-sm tw-text-destructive">
                                            {{ errors[0] }}
                                        </p>
                                    </div>
                                </vee-field>

                                <vee-field
                                    name="category_id"
                                    v-slot="{ field, errors }"
                                >
                                    <div class="tw-space-y-2">
                                        <Label for="category_id">
                                            {{ __("Category") }}
                                            <span class="tw-text-destructive">*</span>
                                        </Label>
                                        <Select
                                            v-bind="field"
                                            :model-value="form.category_id"
                                            @update:model-value="(val) => form.category_id = val"
                                        >
                                            <SelectTrigger
                                                id="category_id"
                                                :class="{ 'tw-border-destructive': errors.length }"
                                            >
                                                <SelectValue :placeholder="__('Select category')" />
                                            </SelectTrigger>
                                            <SelectContent>
                                                <SelectItem
                                                    v-for="category in categories"
                                                    :key="category.id"
                                                    :value="category.id.toString()"
                                                >
                                                    {{ category.name }}
                                                </SelectItem>
                                            </SelectContent>
                                        </Select>
                                        <p v-if="errors.length" class="tw-text-sm tw-text-destructive">
                                            {{ errors[0] }}
                                        </p>
                                    </div>
                                </vee-field>
                            </div>

                            <div class="tw-flex tw-items-center tw-space-x-2">
                                <Switch
                                    id="is_available"
                                    :model-value="form.is_available"
                                    @update:model-value="(val) => form.is_available = val"
                                />
                                <Label for="is_available">{{ __("Available for sale") }}</Label>
                            </div>
                        </CardContent>
                    </Card>

                    <!-- Image Upload -->
                    <Card>
                        <CardHeader>
                            <CardTitle>{{ __("Product Image") }}</CardTitle>
                            <CardDescription>
                                {{ __("Upload an image for the product") }}
                            </CardDescription>
                        </CardHeader>
                        <CardContent>
                            <div class="tw-space-y-4">
                                <div class="tw-flex tw-items-center tw-gap-4">
                                    <div v-if="imagePreview" class="tw-w-20 tw-h-20 tw-rounded-lg tw-overflow-hidden">
                                        <img
                                            :src="imagePreview"
                                            :alt="form.name"
                                            class="tw-w-full tw-h-full tw-object-cover"
                                        />
                                    </div>
                                    <div class="tw-flex-1">
                                        <Input
                                            type="file"
                                            accept="image/*"
                                            @change="handleImageUpload"
                                            class="tw-file:tw-mr-4 tw-file:tw-py-2 tw-file:tw-px-4 tw-file:tw-rounded-full tw-file:tw-border-0 tw-file:tw-text-sm tw-file:tw-font-semibold tw-file:tw-bg-primary tw-file:tw-text-primary-foreground tw-hover:tw-file:tw-bg-primary/90"
                                        />
                                        <p class="tw-text-sm tw-text-muted-foreground tw-mt-1">
                                            {{ __("Recommended size: 400x400px, max 2MB") }}
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </CardContent>
                    </Card>
                </div>

                <!-- Sidebar -->
                <div class="tw-space-y-6">
                    <!-- Actions -->
                    <Card>
                        <CardHeader>
                            <CardTitle>{{ __("Actions") }}</CardTitle>
                        </CardHeader>
                        <CardContent class="tw-space-y-2">
                            <Button
                                type="submit"
                                class="tw-w-full"
                                :disabled="!meta.valid || form.processing"
                            >
                                <Loader2
                                    v-if="form.processing"
                                    class="tw-h-4 tw-w-4 tw-mr-2 tw-animate-spin"
                                />
                                <Plus v-else class="tw-h-4 tw-w-4 tw-mr-2" />
                                {{ __("Create Product") }}
                            </Button>
                            <Button
                                type="button"
                                variant="outline"
                                class="tw-w-full"
                                @click="goBack"
                            >
                                {{ __("Cancel") }}
                            </Button>
                        </CardContent>
                    </Card>

                    <!-- Product Info -->
                    <Card>
                        <CardHeader>
                            <CardTitle>{{ __("Product Information") }}</CardTitle>
                        </CardHeader>
                        <CardContent class="tw-space-y-2 tw-text-sm">
                            <div class="tw-flex tw-justify-between">
                                <span class="tw-text-muted-foreground">{{ __("Status") }}:</span>
                                <Badge :variant="form.is_available ? 'default' : 'secondary'">
                                    {{ form.is_available ? __("Available") : __("Unavailable") }}
                                </Badge>
                            </div>
                            <div v-if="form.price" class="tw-flex tw-justify-between">
                                <span class="tw-text-muted-foreground">{{ __("Price") }}:</span>
                                <span class="tw-font-medium">${{ form.price }}</span>
                            </div>
                        </CardContent>
                    </Card>
                </div>
            </div>
        </div>
    </vee-form>
</template>

<script setup>
import { useForm } from "@inertiajs/vue3";
import { Head } from "@inertiajs/vue3";
import { Button } from "@/Components/ui/button";
import { Input } from "@/Components/ui/input";
import { Label } from "@/Components/ui/label";
import { Textarea } from "@/Components/ui/textarea";
import { Switch } from "@/Components/ui/switch";
import {
    Select,
    SelectContent,
    SelectItem,
    SelectTrigger,
    SelectValue,
} from "@/Components/ui/select";
import {
    Card,
    CardContent,
    CardDescription,
    CardHeader,
    CardTitle,
} from "@/Components/ui/card";
import { Badge } from "@/Components/ui/badge";
import { Loader2, Plus, ArrowLeft } from "lucide-vue-next";
import { useToast } from "@/Components/ui/toast/use-toast";
import * as yup from "yup";

const { toast } = useToast();

const props = defineProps({
    categories: {
        type: Array,
        default: () => [],
    },
});

const schema = yup.object({
    name: yup.string().required(__("Product name is required")),
    description: yup.string(),
    price: yup.number().min(0.01).required(__("Price is required")),
    category_id: yup.number().required(__("Category is required")),
    is_available: yup.boolean(),
});

const form = useForm({
    name: "",
    description: "",
    price: "",
    category_id: null,
    is_available: true,
    image: null,
});

const imagePreview = ref(null);

const handleImageUpload = (event) => {
    const file = event.target.files[0];
    if (file) {
        form.image = file;
        
        // Create preview
        const reader = new FileReader();
        reader.onload = (e) => {
            imagePreview.value = e.target.result;
        };
        reader.readAsDataURL(file);
    }
};

const submit = (setErrors) => {
    form.post(route("dashboard.products.store"), {
        forceFormData: true,
        onSuccess: () => {
            toast({
                title: __("Success"),
                description: __("Product created successfully"),
            });
        },
        onError: (errors) => {
            setErrors(errors);
            toast({
                title: __("Error"),
                description: __("Failed to create product"),
                variant: "destructive",
            });
        },
    });
};

const goBack = () => {
    router.visit(route("dashboard.products.index"));
};
</script>

// resources/js/Pages/Orders/Create.tsx
import { FormEventHandler, useState } from 'react';
import { Head, Link, useForm, router } from '@inertiajs/react';
import AppLayout from '@/Layouts/AppLayout';
import { Product, Category } from '@/types';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { ArrowLeft, Plus, Minus, Trash2, ShoppingCart } from 'lucide-react';
import { formatPrice } from '@/lib/utils';

interface Props {
    products: Product[];
    categories: Category[];
}

interface CartItem {
    product: Product;
    quantity: number;
    special_instructions?: string;
}

export default function Create({ products, categories }: Props) {
    const [cart, setCart] = useState<CartItem[]>([]);
    const [selectedCategory, setSelectedCategory] = useState<string>('');
    const [deliveryAddress, setDeliveryAddress] = useState('');
    const [notes, setNotes] = useState('');

    const { post, processing } = useForm();

    const addToCart = (product: Product) => {
        const existingItem = cart.find(item => item.product.id === product.id);
        if (existingItem) {
            updateQuantity(product.id, existingItem.quantity + 1);
        } else {
            setCart([...cart, { product, quantity: 1 }]);
        }
    };

    const updateQuantity = (productId: number, quantity: number) => {
        if (quantity <= 0) {
            removeFromCart(productId);
            return;
        }
        setCart(cart.map(item =>
            item.product.id === productId ? { ...item, quantity } : item
        ));
    };

    const updateInstructions = (productId: number, instructions: string) => {
        setCart(cart.map(item =>
            item.product.id === productId ? { ...item, special_instructions: instructions } : item
        ));
    };

    const removeFromCart = (productId: number) => {
        setCart(cart.filter(item => item.product.id !== productId));
    };

    const calculateSubtotal = () => {
        return cart.reduce((sum, item) => {
            const price = typeof item.product.price === 'string'
                ? parseFloat(item.product.price)
                : item.product.price;
            return sum + (price * item.quantity);
        }, 0);
    };

    const calculateTax = () => {
        return calculateSubtotal() * 0.1; // 10% tax
    };

    const calculateTotal = () => {
        return calculateSubtotal() + calculateTax();
    };

    const submit: FormEventHandler = (e) => {
        e.preventDefault();

        const orderData = {
            items: cart.map(item => ({
                product_id: item.product.id,
                quantity: item.quantity,
                special_instructions: item.special_instructions,
            })),
            delivery_address: deliveryAddress,
            notes: notes,
        };

        post('/orders', {
            data: orderData,
        });
    };

    const filteredProducts = selectedCategory
        ? products.filter(p => p.category_id.toString() === selectedCategory)
        : products;

    return (
        <AppLayout>
            <Head title="Create Order" />

            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
                <Link href="/orders">
                    <Button variant="outline" className="mb-6">
                        <ArrowLeft className="w-4 h-4 mr-2" />
                        Back to Orders
                    </Button>
                </Link>

                <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                    {/* Products Selection */}
                    <div className="lg:col-span-2 space-y-6">
                        <Card>
                            <CardHeader>
                                <CardTitle>Select Products</CardTitle>
                                <CardDescription>Choose items for your order</CardDescription>
                            </CardHeader>
                            <CardContent>
                                {/* Category Filter */}
                                <div className="mb-4">
                                    <Select value={selectedCategory} onValueChange={setSelectedCategory}>
                                        <SelectTrigger>
                                            <SelectValue placeholder="All Categories" />
                                        </SelectTrigger>
                                        <SelectContent>
                                            <SelectItem value="">All Categories</SelectItem>
                                            {categories.map((category) => (
                                                <SelectItem key={category.id} value={category.id.toString()}>
                                                    {category.name}
                                                </SelectItem>
                                            ))}
                                        </SelectContent>
                                    </Select>
                                </div>

                                {/* Products Grid */}
                                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 max-h-[600px] overflow-y-auto">
                                    {filteredProducts.map((product) => {
                                        const isAvailable = product.is_available && product.inventory && product.inventory.quantity > 0;
                                        return (
                                            <Card key={product.id} className={!isAvailable ? 'opacity-50' : ''}>
                                                <CardHeader className="p-4">
                                                    <div className="flex justify-between items-start">
                                                        <div className="flex-1">
                                                            <CardTitle className="text-sm">{product.name}</CardTitle>
                                                            <p className="text-xs text-gray-500 mt-1">
                                                                {product.category?.name}
                                                            </p>
                                                        </div>
                                                        <Badge variant={isAvailable ? "default" : "destructive"} className="text-xs">
                                                            {isAvailable ? 'Available' : 'Out of Stock'}
                                                        </Badge>
                                                    </div>
                                                    <p className="text-sm font-bold text-indigo-600 mt-2">
                                                        {formatPrice(product.price)}
                                                    </p>
                                                </CardHeader>
                                                <CardContent className="p-4 pt-0">
                                                    <Button
                                                        size="sm"
                                                        className="w-full"
                                                        onClick={() => addToCart(product)}
                                                        disabled={!isAvailable}
                                                    >
                                                        <Plus className="w-3 h-3 mr-1" />
                                                        Add to Cart
                                                    </Button>
                                                </CardContent>
                                            </Card>
                                        );
                                    })}
                                </div>
                            </CardContent>
                        </Card>
                    </div>

                    {/* Cart & Checkout */}
                    <div className="space-y-6">
                        <Card>
                            <CardHeader>
                                <CardTitle>Your Cart</CardTitle>
                                <CardDescription>{cart.length} items</CardDescription>
                            </CardHeader>
                            <CardContent>
                                {cart.length === 0 ? (
                                    <div className="text-center py-8 text-gray-500">
                                        <ShoppingCart className="w-12 h-12 mx-auto mb-2 text-gray-400" />
                                        <p>Your cart is empty</p>
                                    </div>
                                ) : (
                                    <div className="space-y-4">
                                        {cart.map((item) => (
                                            <div key={item.product.id} className="border-b pb-4">
                                                <div className="flex justify-between items-start mb-2">
                                                    <div className="flex-1">
                                                        <p className="font-medium text-sm">{item.product.name}</p>
                                                        <p className="text-xs text-gray-500">
                                                            {formatPrice(item.product.price)} each
                                                        </p>
                                                    </div>
                                                    <Button
                                                        size="icon"
                                                        variant="ghost"
                                                        onClick={() => removeFromCart(item.product.id)}
                                                    >
                                                        <Trash2 className="w-4 h-4 text-red-500" />
                                                    </Button>
                                                </div>
                                                <div className="flex items-center gap-2 mb-2">
                                                    <Button
                                                        size="icon"
                                                        variant="outline"
                                                        onClick={() => updateQuantity(item.product.id, item.quantity - 1)}
                                                    >
                                                        <Minus className="w-3 h-3" />
                                                    </Button>
                                                    <span className="w-8 text-center">{item.quantity}</span>
                                                    <Button
                                                        size="icon"
                                                        variant="outline"
                                                        onClick={() => updateQuantity(item.product.id, item.quantity + 1)}
                                                    >
                                                        <Plus className="w-3 h-3" />
                                                    </Button>
                                                </div>
                                                <Input
                                                    placeholder="Special instructions..."
                                                    value={item.special_instructions || ''}
                                                    onChange={(e) => updateInstructions(item.product.id, e.target.value)}
                                                    className="text-sm"
                                                />
                                            </div>
                                        ))}
                                    </div>
                                )}
                            </CardContent>
                        </Card>

                        {cart.length > 0 && (
                            <form onSubmit={submit}>
                                <Card>
                                    <CardHeader>
                                        <CardTitle>Order Details</CardTitle>
                                    </CardHeader>
                                    <CardContent className="space-y-4">
                                        <div>
                                            <label className="text-sm font-medium mb-2 block">
                                                Delivery Address
                                            </label>
                                            <textarea
                                                value={deliveryAddress}
                                                onChange={(e) => setDeliveryAddress(e.target.value)}
                                                rows={2}
                                                className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
                                                placeholder="Enter delivery address..."
                                            />
                                        </div>
                                        <div>
                                            <label className="text-sm font-medium mb-2 block">
                                                Order Notes
                                            </label>
                                            <textarea
                                                value={notes}
                                                onChange={(e) => setNotes(e.target.value)}
                                                rows={2}
                                                className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
                                                placeholder="Any special requests..."
                                            />
                                        </div>

                                        <div className="border-t pt-4 space-y-2">
                                            <div className="flex justify-between text-sm">
                                                <span>Subtotal:</span>
                                                <span>{formatPrice(calculateSubtotal())}</span>
                                            </div>
                                            <div className="flex justify-between text-sm">
                                                <span>Tax (10%):</span>
                                                <span>{formatPrice(calculateTax())}</span>
                                            </div>
                                            <div className="flex justify-between text-lg font-bold">
                                                <span>Total:</span>
                                                <span className="text-indigo-600">
                                                    {formatPrice(calculateTotal())}
                                                </span>
                                            </div>
                                        </div>

                                        <Button type="submit" className="w-full" disabled={processing}>
                                            <ShoppingCart className="w-4 h-4 mr-2" />
                                            Place Order
                                        </Button>
                                    </CardContent>
                                </Card>
                            </form>
                        )}
                    </div>
                </div>
            </div>
        </AppLayout>
    );
}
