// resources/js/Layouts/AppLayout.tsx
import { PropsWithChildren, useState } from 'react';
import { Link, usePage } from '@inertiajs/react';
import { User } from '@/types';
import { Button } from '@/components/ui/button';
import {
    DropdownMenu,
    DropdownMenuContent,
    DropdownMenuItem,
    DropdownMenuLabel,
    DropdownMenuSeparator,
    DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { Menu, X, ShoppingCart, Package, BarChart3, ChefHat, Home } from 'lucide-react';

interface Props extends PropsWithChildren {
    user?: User;
}

export default function AppLayout({ children }: Props) {
    const { auth, flash } = usePage<any>().props;
    const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
    const user = auth?.user;

    return (
        <div className="min-h-screen bg-gray-50">
            {/* Navigation */}
            <nav className="bg-white border-b border-gray-200">
                <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                    <div className="flex justify-between h-16">
                        <div className="flex">
                            <div className="flex-shrink-0 flex items-center">
                                <Link href="/dashboard" className="text-xl font-bold text-gray-900">
                                    Food Ordering System
                                </Link>
                            </div>

                            <div className="hidden sm:ml-8 sm:flex sm:space-x-8">
                                <Link
                                    href="/products"
                                    className="inline-flex items-center px-1 pt-1 border-b-2 border-transparent text-sm font-medium text-gray-500 hover:text-gray-700 hover:border-gray-300"
                                >
                                    <ShoppingCart className="w-4 h-4 mr-2" />
                                    Menu
                                </Link>

                                {user && (
                                    <>
                                        <Link
                                            href="/orders"
                                            className="inline-flex items-center px-1 pt-1 border-b-2 border-transparent text-sm font-medium text-gray-500 hover:text-gray-700 hover:border-gray-300"
                                        >
                                            My Orders
                                        </Link>

                                        {user.role === 'manager' && (
                                            <>
                                                <Link
                                                    href="/manager/inventory"
                                                    className="inline-flex items-center px-1 pt-1 border-b-2 border-transparent text-sm font-medium text-gray-500 hover:text-gray-700 hover:border-gray-300"
                                                >
                                                    <Package className="w-4 h-4 mr-2" />
                                                    Inventory
                                                </Link>
                                                <Link
                                                    href="/manager/reports/sales"
                                                    className="inline-flex items-center px-1 pt-1 border-b-2 border-transparent text-sm font-medium text-gray-500 hover:text-gray-700 hover:border-gray-300"
                                                >
                                                    <BarChart3 className="w-4 h-4 mr-2" />
                                                    Reports
                                                </Link>
                                            </>
                                        )}

                                        {user.role === 'kitchen' && (
                                            <Link
                                                href="/kitchen/orders"
                                                className="inline-flex items-center px-1 pt-1 border-b-2 border-transparent text-sm font-medium text-gray-500 hover:text-gray-700 hover:border-gray-300"
                                            >
                                                <ChefHat className="w-4 h-4 mr-2" />
                                                Kitchen Orders
                                            </Link>
                                        )}
                                    </>
                                )}
                            </div>
                        </div>

                        <div className="hidden sm:ml-6 sm:flex sm:items-center">
                            {user ? (
                                <DropdownMenu>
                                    <DropdownMenuTrigger asChild>
                                        <Button variant="ghost" className="flex items-center">
                                            <span>{user.name}</span>
                                            <span className="ml-2 text-xs bg-indigo-100 text-indigo-800 px-2 py-1 rounded-full">
                                                {user.role.charAt(0).toUpperCase() + user.role.slice(1)}
                                            </span>
                                        </Button>
                                    </DropdownMenuTrigger>
                                    <DropdownMenuContent align="end">
                                        <DropdownMenuLabel>My Account</DropdownMenuLabel>
                                        <DropdownMenuSeparator />
                                        <DropdownMenuItem asChild>
                                            <Link href="/dashboard">
                                                <Home className="w-4 h-4 mr-2" />
                                                Dashboard
                                            </Link>
                                        </DropdownMenuItem>
                                        <DropdownMenuItem asChild>
                                            <Link href="/profile">Profile</Link>
                                        </DropdownMenuItem>
                                        <DropdownMenuSeparator />
                                        <DropdownMenuItem asChild>
                                            <Link href="/logout" method="post" as="button" className="w-full">
                                                Logout
                                            </Link>
                                        </DropdownMenuItem>
                                    </DropdownMenuContent>
                                </DropdownMenu>
                            ) : (
                                <div className="flex items-center space-x-4">
                                    <Link href="/login">
                                        <Button variant="ghost">Login</Button>
                                    </Link>
                                    <Link href="/register">
                                        <Button>Register</Button>
                                    </Link>
                                </div>
                            )}
                        </div>

                        {/* Mobile menu button */}
                        <div className="flex items-center sm:hidden">
                            <Button
                                variant="ghost"
                                onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
                            >
                                {mobileMenuOpen ? <X className="h-6 w-6" /> : <Menu className="h-6 w-6" />}
                            </Button>
                        </div>
                    </div>
                </div>

                {/* Mobile menu */}
                {mobileMenuOpen && (
                    <div className="sm:hidden">
                        <div className="pt-2 pb-3 space-y-1">
                            <Link
                                href="/products"
                                className="block pl-3 pr-4 py-2 border-l-4 border-transparent text-base font-medium text-gray-600 hover:text-gray-800 hover:bg-gray-50 hover:border-gray-300"
                            >
                                Menu
                            </Link>
                            {user && (
                                <Link
                                    href="/orders"
                                    className="block pl-3 pr-4 py-2 border-l-4 border-transparent text-base font-medium text-gray-600 hover:text-gray-800 hover:bg-gray-50 hover:border-gray-300"
                                >
                                    My Orders
                                </Link>
                            )}
                        </div>
                    </div>
                )}
            </nav>

            {/* Flash Messages */}
            {flash?.success && (
                <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 mt-4">
                    <Alert className="bg-green-50 border-green-200">
                        <AlertDescription className="text-green-800">
                            {flash.success}
                        </AlertDescription>
                    </Alert>
                </div>
            )}

            {flash?.error && (
                <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 mt-4">
                    <Alert variant="destructive">
                        <AlertDescription>{flash.error}</AlertDescription>
                    </Alert>
                </div>
            )}

            {/* Page Content */}
            <main className="py-6">
                {children}
            </main>

            {/* Footer */}
            <footer className="bg-white mt-12 py-6 border-t border-gray-200">
                <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center text-gray-600">
                    <p>&copy; {new Date().getFullYear()} Food Ordering System. All rights reserved.</p>
                </div>
            </footer>
        </div>
    );
}

// resources/js/Layouts/AppLayout.vue
<template>
  <v-app>
    <!-- Navigation -->
    <v-app-bar
      app
      color="primary"
      dark
      elevation="1"
    >
      <v-app-bar-nav-icon
        @click="drawer = !drawer"
        class="d-lg-none"
      />

      <v-toolbar-title class="text-h6 font-weight-bold">
        <Link href="/dashboard" class="text-decoration-none text-white">
          Food Ordering System
        </Link>
      </v-toolbar-title>

      <v-spacer />

      <!-- Desktop Navigation -->
      <div class="d-none d-lg-flex align-center">
        <v-btn
          text
          dark
          :to="{ name: 'products.index' }"
          class="mx-2"
        >
          <v-icon left>mdi-food</v-icon>
          Menu
        </v-btn>

        <template v-if="user">
          <v-btn
            text
            dark
            :to="{ name: 'orders.index' }"
            class="mx-2"
          >
            <v-icon left>mdi-clipboard-list</v-icon>
            My Orders
          </v-btn>

          <!-- Admin Menu -->
          <template v-if="user.role === 'admin'">
            <v-btn
              text
              dark
              :to="{ name: 'admin.products.index' }"
              class="mx-2"
            >
              <v-icon left>mdi-food</v-icon>
              Products
            </v-btn>
            <v-btn
              text
              dark
              :to="{ name: 'categories.index' }"
              class="mx-2"
            >
              <v-icon left>mdi-tag</v-icon>
              Categories
            </v-btn>
            <v-btn
              text
              dark
              :to="{ name: 'inventory.index' }"
              class="mx-2"
            >
              <v-icon left>mdi-package-variant</v-icon>
              Inventory
            </v-btn>
            <v-btn
              text
              dark
              :to="{ name: 'roles.index' }"
              class="mx-2"
            >
              <v-icon left>mdi-shield-account</v-icon>
              Roles
            </v-btn>
            <v-btn
              text
              dark
              :to="{ name: 'user-roles.index' }"
              class="mx-2"
            >
              <v-icon left>mdi-account-cog</v-icon>
              User Roles
            </v-btn>
            <v-btn
              text
              dark
              :to="{ name: 'admin.reports.sales' }"
              class="mx-2"
            >
              <v-icon left>mdi-chart-line</v-icon>
              Reports
            </v-btn>
          </template>
        </template>
      </div>

      <!-- User Menu -->
      <div class="d-none d-sm-flex align-center ml-4">
        <template v-if="user">
          <v-menu offset-y>
            <template v-slot:activator="{ props }">
              <v-btn
                v-bind="props"
                variant="text"
                dark
                class="text-capitalize"
              >
                {{ user.name }}
                <v-chip
                  small
                  color="white"
                  text-color="primary"
                  class="ml-2"
                >
                  {{ capitalizeRole(user.role) }}
                </v-chip>
                <v-icon right>mdi-chevron-down</v-icon>
              </v-btn>
            </template>
            <v-list>
              <v-list-item>
                <v-list-item-title>My Account</v-list-item-title>
              </v-list-item>
              <v-divider />
              <v-list-item :to="{ name: 'dashboard' }">
                <template v-slot:prepend>
                  <v-icon>mdi-home</v-icon>
                </template>
                <v-list-item-title>Dashboard</v-list-item-title>
              </v-list-item>
              <v-list-item :to="{ name: 'profile' }">
                <v-list-item-title>Profile</v-list-item-title>
              </v-list-item>
              <v-divider />
              <v-list-item @click="logout">
                <v-list-item-title>Logout</v-list-item-title>
              </v-list-item>
            </v-list>
          </v-menu>
        </template>
        <template v-else>
          <v-btn
            variant="text"
            dark
            :to="{ name: 'login' }"
            class="mx-1"
          >
            Login
          </v-btn>
          <v-btn
            variant="outlined"
            dark
            :to="{ name: 'register' }"
            class="mx-1"
          >
            Register
          </v-btn>
        </template>
      </div>
    </v-app-bar>

    <!-- Navigation Drawer (Mobile) -->
    <v-navigation-drawer
      v-model="drawer"
      temporary
      app
    >
      <v-list>
        <v-list-item>
          <v-list-item-title class="text-h6 font-weight-bold">
            Food Ordering System
          </v-list-item-title>
        </v-list-item>
        <v-divider />
        
        <v-list-item :to="{ name: 'products.index' }">
          <template v-slot:prepend>
            <v-icon>mdi-food</v-icon>
          </template>
          <v-list-item-title>Menu</v-list-item-title>
        </v-list-item>

        <template v-if="user">
          <v-list-item :to="{ name: 'orders.index' }">
            <template v-slot:prepend>
              <v-icon>mdi-clipboard-list</v-icon>
            </template>
            <v-list-item-title>My Orders</v-list-item-title>
          </v-list-item>

          <!-- Admin Menu -->
          <template v-if="user.role === 'admin'">
            <v-list-item :to="{ name: 'admin.products.index' }">
              <template v-slot:prepend>
                <v-icon>mdi-food</v-icon>
              </template>
              <v-list-item-title>Products</v-list-item-title>
            </v-list-item>
            <v-list-item :to="{ name: 'categories.index' }">
              <template v-slot:prepend>
                <v-icon>mdi-tag</v-icon>
              </template>
              <v-list-item-title>Categories</v-list-item-title>
            </v-list-item>
            <v-list-item :to="{ name: 'inventory.index' }">
              <template v-slot:prepend>
                <v-icon>mdi-package-variant</v-icon>
              </template>
              <v-list-item-title>Inventory</v-list-item-title>
            </v-list-item>
            <v-list-item :to="{ name: 'roles.index' }">
              <template v-slot:prepend>
                <v-icon>mdi-shield-account</v-icon>
              </template>
              <v-list-item-title>Roles</v-list-item-title>
            </v-list-item>
            <v-list-item :to="{ name: 'user-roles.index' }">
              <template v-slot:prepend>
                <v-icon>mdi-account-cog</v-icon>
              </template>
              <v-list-item-title>User Roles</v-list-item-title>
            </v-list-item>
            <v-list-item :to="{ name: 'admin.reports.sales' }">
              <template v-slot:prepend>
                <v-icon>mdi-chart-line</v-icon>
              </template>
              <v-list-item-title>Reports</v-list-item-title>
            </v-list-item>
          </template>

          <v-divider />
          <v-list-item :to="{ name: 'dashboard' }">
            <template v-slot:prepend>
              <v-icon>mdi-home</v-icon>
            </template>
            <v-list-item-title>Dashboard</v-list-item-title>
          </v-list-item>
          <v-list-item :to="{ name: 'profile' }">
            <v-list-item-title>Profile</v-list-item-title>
          </v-list-item>
          <v-list-item @click="logout">
            <v-list-item-title>Logout</v-list-item-title>
          </v-list-item>
        </template>
        <template v-else>
          <v-divider />
          <v-list-item :to="{ name: 'login' }">
            <v-list-item-title>Login</v-list-item-title>
          </v-list-item>
          <v-list-item :to="{ name: 'register' }">
            <v-list-item-title>Register</v-list-item-title>
          </v-list-item>
        </template>
      </v-list>
    </v-navigation-drawer>

    <!-- Flash Messages -->
    <v-snackbar
      v-if="flash?.success"
      v-model="showSuccessSnackbar"
      color="success"
      timeout="5000"
      top
    >
      <v-icon left>mdi-check-circle</v-icon>
      {{ flash.success }}
    </v-snackbar>

    <v-snackbar
      v-if="flash?.error"
      v-model="showErrorSnackbar"
      color="error"
      timeout="5000"
      top
    >
      <v-icon left>mdi-alert-circle</v-icon>
      {{ flash.error }}
    </v-snackbar>

    <!-- Main Content -->
    <v-main>
      <v-container fluid class="pa-4">
        <slot />
      </v-container>
    </v-main>

    <!-- Footer -->
    <v-footer
      app
      color="grey-lighten-4"
      class="justify-center"
    >
      <div class="text-center">
        &copy; {{ new Date().getFullYear() }} Food Ordering System. All rights reserved.
      </div>
    </v-footer>
  </v-app>
</template>

<script setup>
import { ref, computed } from 'vue';
import { Link, usePage } from '@inertiajs/vue3';
import { router } from '@inertiajs/vue3';

const props = defineProps({
  user: {
    type: Object,
    default: null
  }
});

const page = usePage();
const drawer = ref(false);
const showSuccessSnackbar = ref(true);
const showErrorSnackbar = ref(true);

const user = computed(() => page.props.auth?.user);
const flash = computed(() => page.props.flash);

const capitalizeRole = (role) => {
  return role.charAt(0).toUpperCase() + role.slice(1);
};

const logout = () => {
  router.post('/logout');
};
</script>
